### ISSUE TITLE
Triggering exit while entering sets wrong CSS classes

### ISSUE THREAD

**Issue by Philipp91** [reactjs/react-transition-group#100]
**What is the current behavior?**
When the user triggers an exit transition(e.g. closing a popup/popover/etc.) while the "enter" transition is still ongoing, the element will have all four classes "-enter -enter-active -exit -exit-active" at the sime time. This may be intentional, though I'd consider it a bug because it's difficult to write CSS that handles this case gracefully (as it needs to work both wasy round, i.e. also re-opening while exiting).

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**
I can provide this if needed. The jsfiddle seems outdated.

**What is the expected behavior?**
Only the classes relating to the latest trigger are present.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
2.0.2

**Comment by jquense** [comment]
It's not intentional! Can you post a code example reproducung it? Just a gist is fine, I do need to update the issue template

**Comment by Philipp91** [comment]
https://jsfiddle.net/m4mb9Lg3/2/ I updated the jsfiddle and changed the duration (3 occurrences) to 5000. Change those numbers back and you'll have a jsfiddle for future use.

To reproduce, click "Add item" and then click the new item's X while it's still fading in. Observe it continue until it reaches full opacity, then suddenly disappear.

**Comment by jquense** [comment]
fixed!
