### ISSUE TITLE
Document Error

### ISSUE THREAD

**Issue by zyh825** [reactjs/react-transition-group#102]
**Do you want to request a *feature* or report a *bug*?**
Document Error
**What is the current behavior?**
![image](https://user-images.githubusercontent.com/8102750/28101602-1ae7fba6-66fc-11e7-92f7-3d64b95fc7e4.png)
![image](https://user-images.githubusercontent.com/8102750/28101593-08f51384-66fc-11e7-9004-aab673f2ff7f.png)

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
2.0.2

**Comment by jquense** [comment]
Yup thanks, you we have it fixed just not deployed yet!
