### ISSUE TITLE
TransitionGroup never unmounts children that left

### ISSUE THREAD

**Issue by jedwards1211** [reactjs/react-transition-group#103]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Even after a child of TransitionGroup has left, it remains mounted forever

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**
```js
import React from 'react'
import range from 'lodash.range'

import Transition from 'react-transition-group/Transition'
import TransitionGroup from 'react-transition-group/TransitionGroup'

const duration = 300;

const defaultStyle = {
  transition: `opacity ${duration}ms ease-in-out`,
}

const transitionStyles = {
  entering: { opacity: 1 },
  entered:  { opacity: 1 },
  exiting: {opacity: 0},
  exited: {opacity: 0},
};

const Fade = ({ in: inProp, children }) => {
  return (
    <Transition appear enter exit in={inProp} timeout={duration}>
      {(state) => (
        <div style={{
          ...defaultStyle,
          ...transitionStyles[state]
        }}>
          {children}
        </div>
      )}
    </Transition>
  );
}

class TransitionGroupBug extends React.Component {
  static renderChild = number => <Fade key={number}>Child {number}</Fade>
  static zeroToOneHundred = range(0, 100).map(BasicTest.renderChild)
  static even = range(0, 100, 2).map(BasicTest.renderChild)
  static odd = range(1, 100, 2).map(BasicTest.renderChild)
  static prime = [
    2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 39, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97,
  ].map(BasicTest.renderChild)

  state = {children: BasicTest.prime}

  render() {
    return (
      <div>
        <div>
          <button onClick={() => this.setState({children: BasicTest.zeroToOneHundred})}>0 - 100</button>
          <button onClick={() => this.setState({children: BasicTest.even})}>Evens</button>
          <button onClick={() => this.setState({children: BasicTest.odd})}>Odds</button>
          <button onClick={() => this.setState({children: BasicTest.prime})}>Primes</button>
        </div>
        <TransitionGroup enter exit {...this.state} />
      </div>
    )
  }
}
```

After the component mounts, click the `0 - 100` button, then the `Odds` button.

**What is the expected behavior?**
After transitions, `TransitionGroup` should have only 50 children.  Instead, it has 100 children, and the even numbers are merely faded out, leaving gaps between the odd numbers.

Yeah I know, adding `unmountOnExit` to `Transition` will make it **look** right.  *But that hides the fact that behind the scenes, an unbounded number of `<Transition in={false} />` components could accumulate!*

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome 59.0.3071.115 (Official Build) (64-bit)
Mac OS X

**Comment by jquense** [comment]
Hi there, I'm fairly certain you example doesn't work because you aren't passing all the props to the Transition, specifically it passes onExited which tells it when to remove it

**Comment by jedwards1211** [comment]
Oh I see.  We need to improve the docs then because they don't include any example of passing along the injected props.

**Comment by jquense** [comment]
yes  I made a point to note it in https://github.com/reactjs/react-transition-group/blob/master/migration.md#transitiongroup but it should be in the docs themselves as well
