### ISSUE TITLE
Exports should be consistent

### ISSUE THREAD

**Issue by LKay** [reactjs/react-transition-group#105]
**What is the current behavior?**

Exports for specific components are using ES6 modules, but the index.js exports everything in commonjs module style. 

**What is the expected behavior?**

Everything shold be exported either as ES6 modules or commonjs modules. The index.js file should look like:
```javascript
import CSSTransition from './CSSTransition';
import TransitionGroup from './TransitionGroup';
import Transition from './Transition';

export default {
  Transition,
  TransitionGroup,
  CSSTransition,
};
```
or just:
```javascript
export CSSTransition from './CSSTransition';
export TransitionGroup from './TransitionGroup';
export Transition from './Transition';
```

**Comment by jquense** [comment]
Hi there, It's exported as cjs to allow folks to pick which way they want to import it and not have an awkward api for folks using just cjs. I don't see any issue with doing it this way from  a technical perspective and the convenience is helpful to folks
