### ISSUE TITLE
Object.keys(Transition.propTypes) performance bottleneck

### ISSUE THREAD

**Issue by jedwards1211** [reactjs/react-transition-group#106]
I'm not sure why, but this statement seems to cost tenfold more than anything else in this library in some of my profiling results.  Perhaps it would be best to just write `delete` statements instead of relying on `Transition.propTypes`?

Performance seemed to improve when I did just that.  (I'm writing a component that staggers child entry/exit and feeding that into a TransitionGroup, and it seems to push performance to the limit.)

![screen shot 2017-07-12 at 10 09 40 am](https://user-images.githubusercontent.com/1448194/28124796-5191a39e-66ea-11e7-92e9-84620937c5e9.png)

**Comment by jedwards1211** [comment]
Not to mention that this wouldn't delete any props in production!

**Comment by jedwards1211** [comment]
In fact, I question whether `Transition` should pass through any props at all, for performance's sake.

**Comment by jquense** [comment]
If there is a perf issue it would be in the deleting of props not the iteration and `Object.keys` which is very optimized in browsers. I'm all for improving performance but is there any indication that this causes any issue? "slow" compared to the rest the library isn't necessarily an issue, if slow is still objectively fast.

**Comment by jedwards1211** [comment]
When I use it with my staggered entry/exit component I'm disappointed with the performance compared to staggered entry/exit without any animation.  Eventually I could whip up a demo

**Comment by jquense** [comment]
and removing the prop passthrough fixes the performance issue? A demo would be great if you can!

**Comment by jedwards1211** [comment]
@jquense yeah, I'll try to get a good quality demo together by this evening.

**Comment by jquense** [comment]
gonna close for now, let me know if you come up with a demo illustrating a perf concern thanks!

**Comment by jedwards1211** [comment]
yeah sorry, I've run out of time lately.
