### ISSUE TITLE
Standard ES6 imports fail

### ISSUE THREAD

**Issue by mosesoak** [reactjs/react-transition-group#109]
I'm using a standard npm install in an ES6 project that's compiled using typescript (ts-loader in webpack without babel), imports from docs fail for me:

```javascript
import TransitionGroup from 'react-transition-group/TransitionGroup';
```

While this works:
```javascript
import { TransitionGroup } from 'react-transition-group';
```

I might suggest updating the docs to use the 2nd syntax if it's less problematic, or listing both as options if it varies depending on the build environment.

**Comment by jquense** [comment]
It really should vary... I'm really not sure why typescript would work here. It works for normal es6 imports. Hmm

**Comment by wedelgaard** [comment]
I'm having an issue with this too. Although I'm trying to import Transition. TypeScript throws this error:

```error TS2604: JSX element type 'Transition' does not have any construct or call signatures.```

I'm using the docs import method

```import Transition from "react-transition-group/Transition";```.

Changing it to

```import { Transition } from "react-transition-group";```

doesn't work. It actually throws an extra error:

```error TS2497: Module '".../node_modules/@types/react-transition-group/index"' resolves to a non-module entity and cannot be imported using this construct.```

**Comment by jquense** [comment]
We don't control the `@types/react-transition-group` types so they are probably out of date

**Comment by varHarrie** [comment]
@wedelgaard same, how can you solve this issue?

**Comment by taion** [comment]
Closing as this is a TS-specific issue.
