### ISSUE TITLE
Thoughts on react-css-transition

### ISSUE THREAD

**Issue by cvle** [reactjs/react-transition-group#11]
Hi, I happen to have worked on a project making css transitions reliable in React and used it internally in my projects so far. I recently open sourced it. @gaearon has asked me to work with you guys: @taion and @jquense.

First check it out: https://wikiwi.github.io/react-css-transition/

It is quiet feature complete and solves most issues that users were complaining on the React issue list.

The projects resolves around a workaround to make `transitionEnd` more reliable by running a second transition that only lasts 1 ms to determine the start of the transition. The project also handles other edge cases like _phantom transitionEnd events_ that happens when a transition ends shortly before another transition starts.

By doing this it doesn't need to rely on timeouts which generally don't work well especially on low end mobile devices and can reliably notify the user of the end of the transition.

Though to provide this reliability it has to carefully track the current state of the transition in order to handle an interruption in the best way possible.

It comes as a `CSSTransition` Component that can transition between two states but also includes a `CSSTransitionGroup` that coordinates `CSSTransition` Components to achieve the features similar to yours.

Though at the moment I'm not sure how we would collaborate.

What are your thoughts?

**Comment by jquense** [comment]
I'm sorry I never responded here! I really like the approach to the API you take. I ~~stole~~ was inspired by it, in #24 

I'm not sure what the future holds but perhaps there is an opportunity to leave the css animation bits to you and work on providing good primitives to build that on top of (we may always provide a really simple css transition). I see ya'll are already use TransitionGroup, i'd love to get feedback on if the new api proposal makes that integration nicer, worse, or has little effect
