### ISSUE TITLE
Setting unmountOnExit to true does not prevent component rendering during exiting state

### ISSUE THREAD

**Issue by omallo** [reactjs/react-transition-group#112]
**Do you want to request a *feature* or report a *bug*?**
Based on my understanding, the current behavior is a bug.

**What is the current behavior?**
I'm setting the [`unmountOnExit`](https://reactcommunity.org/react-transition-group/#Transition-prop-unmountOnExit) property to `true` on a `Transition` component but my child component is still rendered during the `exiting` transition state.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**
https://jsfiddle.net/0syaL8ea/

**What is the expected behavior?**
I would expect that a  `Transition` with `unmountOnExit={true}` never renders my child component when the `in` property evaluates to `false`. Instead, my component is still rendered during the `exiting` transition state (it gets correctly unmounted before the `exited` transition state though).
In the jsfiddle example, the component should never get rendered when having the following state:
```
{
  "show": false,
  "transitionState": "exiting"
}
```

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
I'm using version 2.0.2. The problem is independent from the browser / OS and I haven't tested it with any previous version.

**Comment by jquense** [comment]
Hi there, the behavior your seeing is intended. The goal is to still do the exit transition and unmount once it's finished. If you want to avoid an exit transition entirely, you can set both `unmountOnExit` and `exit={false}` to disable the exit stage, and skip right too 'exitied'

**Comment by omallo** [comment]
Thanks for the feedback.

Actually, I do want to have an exit transition which means that setting `exit={false}` is no real option.

My use case is that I have a component which should only be rendered if some condition is met (like the `show` property in the example). If I didn't use the transition package, I would render my component as follows:
```javascript
<div>
  {this.state.show && <Example/>}
</div>
```

That way, React would mount a new instance of my component whenever the `show` property changes from `false` to `true` and unmount it whenever the property changes the other way round. When `show == false`, my component would never be rendered (which it shouldn't since `show == false` means that the data for my component is not available anymore for rendering).

Now, when using the transition package, the following does not work since the `Transition` component expects having a single, non `null` child element:
```javascript
<div>
  <Transition ...>{this.state.show && <Example/>}</Transition>
</div>
```

Similarly, the following does not work since the `Transition` component cannot be created/destroyed at the same time as the `Example` component for the transitions to take effect:
```javascript
<div>
  {this.state.show && <Transition ...><Example/></Transition>}
</div>
```

The only way I got it working was using an additional `TransactionGroup` wrapper:
```javascript
<div>
  <TransactionGroup ...>
    {this.state.show && <Transition ...><Example/></Transition>}
  </TransactionGroup>
</div>
```

When I read about the `mountOnEnter/unmountOnExit` properties in the documentation, I assumed that those properties were intended to support my use case above (which, apparently, is not the case).

Is there an easy way for supporting my use case when using the transition package without having to use a `TransitionGroup` (which feels like overkill)?

**Comment by jquense** [comment]
Sorry I'm not sure I understand how `unmountOnExit` (if it did what you expected) would help you here? Can you describe the behavior you want to see, not just what you've tried?

It sounds like you want to both animate something out and have it unmount before the animation start. That is not technically possible, React or otherwise. If the element is not mounted then it doesn't exist in any visible space, and is nothing to animate.

**Comment by omallo** [comment]
I'm sorry if I'm not able to explain it well but I'm rather new to React and even more to the transition package.

Based on the example above, the behavior I would like to achieve is the following in terms of state/transition changes:

1. The `show` property changes from `false` to `true`.
2. The `Transition` component mounts the `Example` component.
3. The `Transition` component triggers the `entering` and `entered` states for animations to take place.
4. The `show` property changes from `true` to `false`.
5. The `Transition` component unmounts the `Example` component w/o removing its DOM elements.
6. The `Transition` component triggers the `exiting` and `exited` states for animations to take place.

The key point is step 5 which should ensure that the `Example` component is never rendered when `show == false` (either by unmounting it or by some other means). But I guess that's what you mentioned in your comment as not being technically possible (makes kind of sense).

**Comment by jquense** [comment]
OK, so if I understand you, your options at **5** are:

- Unmount the component immediately when `show` switches, which means no exit transition (because it's unmounted), in which case `exit={false}` and `unmountOnExit` will do that
- Unmount after the exit transition finished (such fading out), in which case `unmountOnExit` does exactly that.

What you cannot do, from a strict technical perspective is both animate it out _and_ unmount the component immediately. Unmount means "destroy" and you can't animate something that doesn't exist :)

**Comment by omallo** [comment]
Thanks for the explanation. So it seems like I'm fighting against some kind of physical law :)

One thing which is still interesting, is that if I use a wrapping `TransitionGroup`, I'm actually getting the desired behavior. You can see this in [this jsfiddle](https://jsfiddle.net/wjury0qb/) where the custom `GuardedCSSTransition` component correctly triggers the CSS animation on `exit` but the component is always rendered with `"show": true`, even after the `show` property has actually changed to `false`. In the example, you see the difference between the custom `GuardedCSSTransition` component and and the `CSSTransition` component.

Can you explain why it seems to work as expected when using a wrapping `TransitionGroup`?

**Comment by jquense** [comment]
> Can you explain why it seems to work as expected when using a wrapping TransitionGroup?

It isn't, you are seeing the same behavior as if you used `unmountOnExit` on a single Transition. in fact it's the _exact_ same behavior because that's exactly what TransitionGroup is doing internally, it flags the inner transition with unmountOnExit.

**Comment by omallo** [comment]
Ok, but at least in the jsfiddle example the behavior during the `exit` transition is different since the `GuardedCSSTransition` component which uses a `TransitionGroup` renders with `"show": true` while, at the same time, the `CSSTransition` component which uses `unmountOnExit={true}` renders with `"show": false`.

In any case, I think I have to check the behavior in both cases in more detail and maybe also check how the different features are implemented. I guess it will then become a bit clearer to me :)

**Comment by jquense** [comment]
Yeah the reason your not seeing updates is an implementation side effect, its not a "
feature", nor is there logic to do that, it just happens because once a childf exits in a TransitionGroup **you** don't have access to it anymore and so cannot update it. This isn't true in the Transition case.

This fiddle demonstrates how to get what want and illustrates the point a bit: https://jsfiddle.net/wjury0qb/4/

**Comment by omallo** [comment]
Ok, I think I understand it now. I guess I should not rely on implementation side effects then :)

I will see whether I might go with the approach in your fiddle, thanks a lot for that and also for your time explaining me different things!
