### ISSUE TITLE
Export state constants from CSSTransition

### ISSUE THREAD

**Issue by katzoo** [reactjs/react-transition-group#120]
**Do you want to request a *feature* or report a *bug*?**
Feature / structure improvement

**What is the current behavior?**
`CSSTransition` module does not export state transition constants (`UNMOUNTED`, `EXITED` etc.), so in order to use it with functional children one needs to import them from `Transition` manually:
```jsx
import { EXITED } from 'react-transition-group/Transition';
import CSSTransition from 'react-transition-group/CSSTransition';

// ...

<CSSTransition
  timeout={123}
  classNames={{ ... }}
>
  {(state) => (
    state === EXITED
      ? null
      : (
        <Component />
      )
  )}
</CSSTransition>
```

**What is the expected behavior?**
Since `CSSTransition` imports (and wraps) `Transition` internally it would make sense to (re)export these constants so both have similar module api.
```jsx
import CSSTransition, { EXITED } from 'react-transition-group/CSSTransition';
```

**Comment by jquense** [comment]
Interesting...The function as a child isn't actually explicitly supported for CSSTransition, It really shouldn't allow it since its a higher level API. Is your usecase the one above? `unmountOnExit` should already cover that.

**Comment by katzoo** [comment]
Thanks for quick response and `unmountOnExit` hint. It did the trick (together with `in`).

My bad then. After seeing `Accepts all props from <Transition> unless otherwise noted.` in docs I thought it's a valid use case (and it works) and treated `CSSTransition` as a better way of animating with css classes, but for my particular use case I could also use 'plain' `Transition`.

I still feel that using these constants could be beneficial in some situations (eg. showing placeholder during enter/exit transitions), but I guess that's what additional callbacks(`onEntering`, `onExiting` etc.) are exposed for.

Feel free to close this issue.
