### ISSUE TITLE
onEnter/onEntering requires requestAnimationFrame

### ISSUE THREAD

**Issue by cusxio** [reactjs/react-transition-group#122]
**Do you want to request a *feature* or report a *bug*?**

Bug(?)/Feature(?)

**What is the current behavior?**

`requestAnimationFrame` is needed to simulate a "Next Tick" so that the element can be animated properly.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem.**

Please read the comments on the `onEntering` hook in:
https://codesandbox.io/s/o2LDVvqkB

**What is the expected behavior?**

The library should create a "next tick" for the `onEnter` or `onEntering` hooks?

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Chrome: Version 59.0.3071.115 (Official Build) (64-bit)
OS: Mac

**Comment by jquense** [comment]
Hi there, RAF in the `Transition` component is too specific, not all, or most use cases need it. You can implement things like this on top of it...like the `CSSTransition` does. In your use-case you also don't need RAF, reflowing the browser at the appropriate time is enough.
