### ISSUE TITLE
CSSTransition import is undefined in Jest snapshot test

### ISSUE THREAD

**Issue by ajgreenb** [reactjs/react-transition-group#130]
I first posted this question [on StackOverflow][so], but I haven't gotten any responses or many views, so I'm posting it here. Sorry if that's a problem, and please let me know if there's a better place for it!

**Do you want to request a *feature* or report a *bug*?**
Possible bug

**What is the current behavior?**
See below

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
I'm not sure how to provide an in-browser demonstration of this bug, since it only occurs in the test harness with Jest and Enzyme. I made a repository that demonstrates the possible bug: https://github.com/ajgreenb/react-transition-group-bug-demo. To see what I'm demonstrating, clone it, run `yarn` to get the dependencies, and then `yarn test`. Everything should be fine and the snapshot should match. Then fetch and checkout the `broken` branch. Run `yarn` to get the newer version of react-transition-group. Then run `yarn test` and you will see the unexpected behavior.

**What is the expected behavior?**
The component should appear in the snapshot and not be `undefined`.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
* react-transition-group v2.1.0
* Mac OS X Version 10.11.6
* Chromium Version 59.0.3042.0 (Developer Build) (64-bit)

This worked in version 1.2.0.

---

I'm using Jest and Enzyme to snapshot test a component that uses `CSSTransition` from `react-transition-group` (v2.1.0). When I create a snapshot of the component, `CSSTransition` appears `undefined`. This causes React to throw a warning:

    Warning: React.createElement: type is invalid -- expected a string 
      (for built-in components) or a class/function (for composite components) but got:
      undefined. You likely forgot to export your component
      from the file it's defined in.

Here is the broken snapshot diff:

    -  <CSSTransitionGroup
    -    transitionAppear={false}
    -    transitionEnter={true}
    -    transitionEnterTimeout={150}
    -    transitionLeave={true}
    -    transitionLeaveTimeout={150}
    -    transitionName="fade"
    -  />
    +  <undefined
    +    classNames="fade"
    +    in={false}
    +    mountOnEnter={true}
    +    timeout={150}
    +    unmountOnExit={true}
    +  >
    +    <div
    +      className="shadow"
    +      onClick={[Function]}
    +    />
    +  </undefined>

The error first appeared when I upgraded from react-transition-group v1.2.0 to v2.1.0. Here's the relevant part of the commit that first caused the break to appear:

    -import { CSSTransitionGroup } from 'react-transition-group';
    +import CSSTransition from 'react-transition-group/CSSTransition';

    -      <CSSTransitionGroup
    -        transitionName='fade'
    -        transitionEnterTimeout={150}
    -        transitionLeaveTimeout={150}
    +      <CSSTransition
    +        in={!!this.state.selectedCategory}
    +        classNames='fade'
    +        timeout={150}
    +        mountOnEnter
    +        unmountOnExit
           >
    -      { this.state.selectedCategory &&
             <div key='shadow' className='shadow' onClick={this.handleCancel} />
    -      }
    -      </CSSTransitionGroup>
    +      </CSSTransition>

[so]: https://stackoverflow.com/questions/45265821/import-is-undefined-in-jest-snapshot-test

**Comment by Honohonoho** [comment]
I got the same error too, but I try an another way to deal with it from [here](https://github.com/reactjs/react-transition-group/issues/109)

**Comment by ajgreenb** [comment]
Hey, thanks for the feedback @Honohonoho! I've been able to migrate my code successfully (the  behavior is correct). My problem is that the something is causing a `CSSTransition` import to appear `undefined` when I try to test it. Very odd! I think this *might* be the same issue that @LKay refers to in #132...

I'm not entirely sure whether the issue is in react-transition-group or the type definitions.

**Comment by taion** [comment]
Are you using TypeScript?

**Comment by taion** [comment]
Looks like you are – this is an issue with the TS definitions, not with this library.
