### ISSUE TITLE
Fix deprecation warnings for react >= 15.5.0

### ISSUE THREAD

**Issue by AdamTyler** [reactjs/react-transition-group#131]
When running tests or compiling code via webpack, warnings are thrown to console for accessing createClass and PropTypes from the main React package which are deprecated.

```Warning: Accessing createClass via the main React package is deprecated, and will be removed in React v16.0. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class v15.* is available on npm as a temporary, drop-in replacement. For more info see https://fb.me/react-create-class```

**Comment by jquense** [comment]
What version are you using? I think you may have an old version
