### ISSUE TITLE
Improve docs

### ISSUE THREAD

**Issue by VladShcherbin** [reactjs/react-transition-group#134]
Currently, v2 docs are horrible, there is no info on what's the difference between Transition and CSSTransition, very few examples of usage and existing examples are incomplete, like copy-pasted chunks from different places.

I really tried to understand, how new api is supposed to work, read the docs probably 10 times, read migration guide, checked storybook examples, experimented, but currently it is impossible to understand, how to properly use this library (at least for me).

Please, improve the docs, add complete tested examples and explanations. I can post here the questions that I have if this is needed.

Btw is there any chat or any place where questions can be asked about this package?

**Comment by jquense** [comment]
You'll have to be more specific about what you find insufficient, beyond "They are bad, Please make them good". From our perspective there are a bunch examples, including runnable ones in the storybook, so its not super helpful to say there aren't examples. 

Feel free to open specific issues with questions or propose (or better yet PR) changes or improvements to the docs. that would be plently appreciated :) we can't make improvements without actionable paths.

**Comment by VladShcherbin** [comment]
@jquense the problem is that the examples in the docs are incomplete. I'd love to improve the docs, but I can't understand the proper usage. I can ask questions here and improve docs if you answer.

For example, the first question is how to use [appear animation with Transition](https://github.com/reactjs/react-transition-group/issues/133)?
