### ISSUE TITLE
transitionEnterTimeout and transitionLeaveTimeout is not available for firefox environment

### ISSUE THREAD

**Issue by caolei12daxia** [reactjs/react-transition-group#137]
https://jsfiddle.net/t0ar0gmd/4/

react-with-addons.js  version: 0.14.9
JSXTransformer.js version: 0.13.3

In css file:
.example-enter.example-enter-active,
.example-appear.example-appear-active {
  opacity: 1;
  transition: all 5s ease-in;
}
In js file:
<CSSTransitionGroup transitionName="example" transitionAppear={true} transitionAppearTimeout={500} transitionEnterTimeout={500} transitionLeaveTimeout={300}>

expected: Click the "click me!" button, the number will increase and the timeout will be 300ms

Actual: 
On the firefox environment, the number change time is 5s, it is not correct behaviour.
On the chrome environment, the number change time is 500ms, it is correct behaviour.

**Comment by yaodingyd** [comment]
@caolei12daxia In FF, `react-transition-group` functions as expected to remove and add classname within assigned timeout. This seems to be a Firefox issue regards lingering transition effect, not specific related to `react-transition-group`.
I have created a test case with vanilla js https://jsfiddle.net/7aftqaka/ and if FF and Chrome it has the same behavior with your case.

**Comment by jquense** [comment]
You have a pretty old setup, judging from the versions, there. I'd suggest upgrading to something a bit more recent there isn't much we can do even if there is a bug as we aren't supporting v14 of react anymore

**Comment by yaodingyd** [comment]
@caolei12daxia I filed bug report https://bugzilla.mozilla.org/show_bug.cgi?id=1389201 for this behavior in Firefox, if you are interested in.

**Comment by caolei12daxia** [comment]
@yaodingyd Thank you for your response.
