### ISSUE TITLE
Callback is not called for not specified enter/exit timeouts

### ISSUE THREAD

**Issue by jjshinobi** [reactjs/react-transition-group#139]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
When timeout={{enter: 500}} is specified then exit callback is not gonna be called because 
the null condition was added in Transition.js in onTransitionEnd in v.2.2.0: 
 if (timeout != null) {
        setTimeout(this.nextCallback, timeout);
      }

As I understood the change that was introduced in 2.2.0 was to not require timeout if addEndListener
was provided. But enter/exit timeouts as a part of timeout object are optional.

The workaround is to explicitly specify not required timeout as 0: {{enter: 500, exit: 0}}

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

1. Add a transition with timeout={{enter: 500}} and unmountOnExit={true} into a transition group.
2. Remove the transition from the group.
3. Check that the element was not removed from DOM.

**What is the expected behavior?**
Enter/exit callback is called even if enter or exit timeout is not specified as a part of timeout object.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Worked in 2.1.0
The problem appeared in 2.2.0

**Comment by koba04** [comment]
I think `timeout` can omit only when `addEndListener` is specified.
If you do `enter/leave` animation, you should need to specify `enter/leave` timeout or `addEndListener`. Otherwise, ReactTransitionGroup can't detect the animation end.

**Comment by jjshinobi** [comment]
In my particular case I didn't need to use leave animation for Transition element inside TransitionGroup. This is why I only specified timeout={{enter:500}} without specifying exit timeout.
But, then, at some point I remove Transition element from TransitionGroup when some condition applies and Transition element should go to EXITED state anyway before being removed from the DOM even if I didn't specified exit:0 or addEndListener callback. May be I am wrong.

**Comment by koba04** [comment]
@jjshinobi 
Thank you for your explaining! I got it. it seems to make sense to add a warning for this if a part of `enter` or `leave` is not specified.

**Comment by jquense** [comment]
If you are providing addEndListener you are responsible for handling both enter and leave, or provide the timeout for each hotel stage
