### ISSUE TITLE
Issues with mountOnEnter

### ISSUE THREAD

**Issue by mochini** [reactjs/react-transition-group#140]
I'm having a hell of a time transitioning from v1.1.2 to v2.2.0. I'm using the following code:

```
import React from 'react'
import PropTypes from 'prop-types'
import { CSSTransition } from 'react-transition-group'

class Flash extends React.Component {

  static propTypes = {
    children: PropTypes.any,
    message: PropTypes.string
  }

  render() {
    const { children, message } = this.props
    return (
      <div className="flash">
        { children }
        <CSSTransition in={ message !== null } classNames="expanded" timeout={ 250 } mountOnEnter={ true } unmountOnExit={ true }>
          <div>{ message }</div>
        </CSSTransition>
      </div>
    )
  }

}

export default Flash
```

when I run it, I see the following error:

```
Uncaught TypeError: Cannot read property 'classList' of null
    at removeClass (vendor-dbd6286….min.js:201833)
    at vendor-dbd6286….min.js:201516
    at Array.forEach (<anonymous>)
    at removeClass (vendor-dbd6286….min.js:201515)
    at CSSTransition.removeClasses (vendor-dbd6286….min.js:201749)
    at Object.CSSTransition._this.onEnter (vendor-dbd6286….min.js:201685)
    at Transition.performEnter (vendor-dbd6286….min.js:116363)
    at Transition.updateStatus (vendor-dbd6286….min.js:116334)
    at Transition.componentDidUpdate (vendor-dbd6286….min.js:116297)
    at commitLifeCycles (vendor-dbd6286….min.js:174714)
```

and when I poke around in the `Transition` component, it appears to be a problem here:

https://github.com/reactjs/react-transition-group/blob/2693cb71a7c8b8fe6a7d1fa1d10e7df62c8e6c5c/src/Transition.js#L182

When react-dom attempt to find the child node, it returns a null - most likely because it has not yet been mounted.

Am I missing something? Is there some other way I should be invoking my transition? 

Thank you in advance for your help.

**Comment by yaodingyd** [comment]
@mochini There is a reduced test case https://jsfiddle.net/kqzce6b9/ and it works all good.
Are you sure your error is not related to other components? For example are you using transition wrapped react-router?

**Comment by mreishus** [comment]
I get the same error while using a transition wrapped `<Route` elements from react-router.  However, it did work in 1.x...

**Comment by mreishus** [comment]
It looks like there may be an answer here. https://github.com/ReactTraining/react-router/issues/5279

**Comment by sfentress** [comment]
@yaodingyd That test case does not work if the component is visible from the start:

https://jsfiddle.net/xj6vd3ey/

How can you perform a fade-in on a component that would normally start out mounted?

**Comment by yaodingyd** [comment]
@sfentress I'm not sure if that's possible. `in` toggling would trigger the enter or exit states, followed by their callbacks. If it's already mounted, then `in` is already `true`, there would be no change to `in`.

**Comment by sfentress** [comment]
@yaodingyd v1 had the ability to animate on the initial mount, and it works fine using that: https://github.com/reactjs/react-transition-group/tree/v1-stable#animate-initial-mounting

Is this feature not supported in v2?

(It seems that I misunderstood the `mountOnEnter` prop, though, and so this feature may be unrelated to that. If you want me to open a different ticket I can do that.)

**Comment by yaodingyd** [comment]
@sfentress  v2 does have this feature, and it's `appear`. It has the same usage as `transitionAppear `. But I don't think it's the same issue here.

What you were talking about before is essentially a mounted component triggering transition effects without unmounting it. I don't think it's possible unless you manually unmount it.

Initial mounting still has the process from 'unmount' to 'mounted'. So it's different. 

Although, in v2's official guide,
> Most commonly it's used to animate the mounting and unmounting of a component, but can also be used to describe in-place transition states as well.

I would love to see a *in-place* transition example in the official guide.

**Comment by raphi011** [comment]
Am I doing it wrong or does appear seem to not work?
https://jsfiddle.net/xj6vd3ey/

**Comment by jquense** [comment]
@raphi011 https://jsfiddle.net/nrb1g5hd/3/

see: https://github.com/reactjs/react-transition-group/issues/179#issuecomment-325196955

**Comment by silvenon** [comment]
In case usage is still unclear, please open a new issue providing a CodeSandbox demo and specifying exactly what you want to achieve.

**Comment by lifeiscontent** [comment]
@silvenon here's a CodeSandbox demo: https://codesandbox.io/s/late-snow-9f396?file=/components/index.js

if you click the accordion header, you'll notice the console.log returns `null` this is because CSSTransition doesn't wait for the element to be available after it's been mounted to call `onEnter` this issue is very apparent in SSR when doing mounting/unmounting in the CSSTransition.

if you click the accordion header again, the calculations are correct because at that point, the element is rendered.
