### ISSUE TITLE
[docs] missing description for `in` prop

### ISSUE THREAD

**Issue by tirli** [reactjs/react-transition-group#141]
Hi
In the documentation for the v2 there is no description for `in` prop for CSSTransition, but as I understand it is one of required. Maybe you should add its description or make link to [Transition prop `in`](https://reactcommunity.org/react-transition-group/#Transition-prop-in)

**Comment by yaodingyd** [comment]
`CSSTransition` is just one kind of `Transition`, so it is implied that `in` follow the same requirement. Also there is this:
> Props
Accepts all props from <Transition> unless otherwise noted.

**Comment by jquense** [comment]
yup thanks for jumping in
