### ISSUE TITLE
Allow import { ... } from 'react-transition-group'

### ISSUE THREAD

**Issue by tkrotoff** [reactjs/react-transition-group#142]
You advertise [this syntax](https://reactcommunity.org/react-transition-group/#Transition):

```JavaScript
import Transition from 'react-transition-group/Transition'
```

It feels awkward, a regular ES6 syntax should be:

```JavaScript
import { Transition } from 'react-transition-group'
```

And this is what other popular projects do:
- Redux: [`import { createStore } from 'redux'`](https://github.com/reactjs/redux#the-gist)
- Reselect: [`import { createSelector } from 'reselect'`](https://github.com/reactjs/reselect#reselect)
- React Router: [`import { Router, Route, Switch } from 'react-router'`](https://github.com/ReactTraining/react-router/tree/master/packages/react-router#installation)
- React/Create React App: [`import React, { Component } from 'react'`](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/src/App.js#L1)
- Enzyme: [`import { shallow } from 'enzyme'`](https://github.com/airbnb/enzyme#shallow-rendering)
- Angular: [`import { NgModule } from '@angular/core'`](https://angular.io/generated/live-examples/toh-pt6/eplnkr.html)
- Vue.js: [`import Vue, { ComponentOptions } from 'vue'`](https://vuejs.org/v2/guide/typescript.html#Using-Vue’s-Type-Declarations)
- Node.js: `import { join } from 'path'`
- Lodash: `import { range } from 'lodash'`

I understand the concern about size. Lodash does that too and still allow the regular `import { ... }` syntax.

webpack and Rollup now support [tree-shaking with ES6 modules](https://webpack.js.org/guides/tree-shaking/), it still not perfect though: https://github.com/webpack/webpack/issues/2867, https://github.com/webpack/webpack/issues/1750 so the size problem will eventually vanish.

All browsers will soon support ES6 modules:
- Chrome 61: https://www.chromestatus.com/feature/5365692190687232
- Safari: https://webkit.org/status/#feature-modules
- Edge (preview for now): https://developer.microsoft.com/en-us/microsoft-edge/platform/status/moduleses6/
- Firefox (behind a flag): https://bugzilla.mozilla.org/show_bug.cgi?id=568953
See https://github.com/paulirish/es-modules-todomvc

Related discussions:
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18550
- https://github.com/reactjs/react-transition-group/pull/40

Edit:

Related code in react-transition-group: https://github.com/reactjs/react-transition-group/blob/v2.2.0/src/index.js#L6

```JavaScript
module.exports = {
  Transition,
  TransitionGroup,
  CSSTransition,
};
```

Should be:

```JavaScript
export {
  Transition,
  TransitionGroup,
  CSSTransition
};
```

**Comment by jquense** [comment]
`import { Transition } from 'react-transition-group'` works fine, you can do that if you want. Most of those projects (especially lodash) also allow importing the specific thing you want as well.

The reason we don't recommend it is that it includes the entire package instead of just the files you want. Cherry Picking imports will **always** be better than tree-shaking, just give how tree-shaking works and when it needs to bail out of the optimization.

**Comment by tkrotoff** [comment]
@jquense
So `import { Transition } from 'react-transition-group'` is officially supported, right?

**Comment by jquense** [comment]
yup

**Comment by tkrotoff** [comment]
Thanks for the answer.

Is there any reason for writing:
```JavaScript
module.exports = {
  Transition,
  TransitionGroup,
  CSSTransition,
};
```

instead of:
```JavaScript
export {
  Transition,
  TransitionGroup,
  CSSTransition
};
```

https://github.com/reactjs/react-transition-group/blob/v2.2.0/src/index.js#L6

**Comment by jquense** [comment]
Yes, it better controls what the compiled output will be. Practically if you wrote the es6 syntax there the compiled code would end up looking just  like we have it now. e.g `module.exports = {...}`

**Comment by tkrotoff** [comment]
Thx.
I'm asking you all these questions because DefinitelyTyped authors (TypeScript definition files) don't want to support the `import { ... } from 'react-transition-group'` syntax.

And here current strange state:
\- the syntax is officially supported by you
\- it works with TypeScript
=> But is not allowed with the definition type because _It currently "works" by historical accident. This import you write that "works" will not work on real module implementations._

I suspect that if inside `index.js` `export { ... }` were used instead of `module.exports = { ... }` they would not question the `import { ... } from ` syntax.

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/18550

**Comment by jquense** [comment]
I think the TS type defs just need to be updated to correctly allow that syntax
