### ISSUE TITLE
isAppearing boolean is undefined when onEnter or onEntering is triggered

### ISSUE THREAD

**Issue by alonbt** [reactjs/react-transition-group#143]
I reproduce the issue here: https://jsfiddle.net/alonbt/no8c6yyw/

I'm trying to get the isAppearing parameter. it is always 'undefined'. Is it a bug or I might be using it wrong ?

```
  onEnter(node, isAppearing) {
    console.log('fade onEnter! node is', node, 'but why dont i see the appearing state?', isAppearing);
  }
  
  onEntering(node, isAppearing) {
    console.log('fade onEntering! node is', node, 'but why dont i see the appearing state?', isAppearing);
  }
```

**Comment by jquense** [comment]
its a bug, I'm not quite sure _why_ this is happening, if you want to take a crack at it go for it.

**Comment by alonbt** [comment]
I'll give it my best shot!

**Comment by alonbt** [comment]
fixed it: https://github.com/reactjs/react-transition-group/pull/144
