### ISSUE TITLE
<Transition> + React router v4: How to pass down callbacks?

### ISSUE THREAD

**Issue by Danetag** [reactjs/react-transition-group#150]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
Animation callbacks for the `<Transition />` elements are not passed to their children.

**What is the expected behavior?**
I would love to be able to pass down these callbacks to the children, especially with react router v4. Let me explain:

I have a basic `<App />` container that contains all the routes with the `<TransitionGroup />` and `<Transition />` element.

```routes.js

import Homepage from './containers/home-page/Homepage';
import Aboutpage from './containers/about-page/Aboutpage';

const routes = [
  {
    path: '/',
    exact: true,
    component: Homepage
  },
  {
    path: '/about',
    component: Aboutpage
  }
];

export default routes;
```

```App.js
onEnter() {

}

render() {
    return (
      <Layout {...this.props}>
       <Route {...this.props} render={({ location }) => (
          <TransitionGroup>
            <Transition onEnter={::this.onEnter} appear timeout={300} >
                <Switch location={location} key={location.key} >
                 {
                        routes.map((route, index) => (
                            <Route {...route} key={'route_' + index} />
                        )
                  )}
                  </Switch>
              <Transition>
          </TransitionGroup>
      </Route>
      </Layout>
    );
  }
```

My goal is to have custom function within each page (`<Home>`, `<About>`)...
The `onEnter()` works well, but as you see, with the router v4, I have to put the `<Transition>` element outside of the `<Switch>`, meaning I can't have custom `onEnter()` function for each page.

How can I pass down these callback so I can call them in my `<Home>`, `<About>` containers?

I found an ugly work around which consist in creating a custom `<Transition>` component by extending the current Transition class... And updating the render by passing . down the callbacks. It triggers an error on the first render (children are undefined), but ultimately it works fine.. 

I wonder if you could just remove the `delete()` in the `<Transition>` render.

```
delete childProps.in;
delete childProps.mountOnEnter;
delete childProps.unmountOnExit;
delete childProps.appear;
delete childProps.enter;
delete childProps.exit;
delete childProps.timeout;
delete childProps.addEndListener;
delete childProps.onEnter;
delete childProps.onEntering;
delete childProps.onEntered;
delete childProps.onExit;
delete childProps.onExiting;
delete childProps.onExited;
```

I'm sure there's an excellent reason I don't know about deleting these properties, but I'm taking a shot. 

Thanks for your amazing work!

**Comment by pronebird** [comment]
I am actually not able to make it work at all. Wrapping entire `Switch` in `<CSSTransitionGroup>` used to work in v1, but now it just skips the transition entirely.

**Comment by silvenon** [comment]
Could you please elaborate what exactly are you trying to achieve, i. e. what is the end result you're looking for? You don't have to refer to react-transition-group at all in your explanation, just the desired effect.

**Comment by silvenon** [comment]
I will reopen if more info is provided.
