### ISSUE TITLE
React 16 beta issue

### ISSUE THREAD

**Issue by oliviertassinari** [reactjs/react-transition-group#151]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

This is throwing an error:
> ReactBaseClasses.js:66 Uncaught TypeError: this.updater.enqueueCallback is not a function
    at Transition.ReactComponent.setState (ReactBaseClasses.js:66)
    at Transition.safeSetState (Transition.js:294)
    at Transition.performEnter (Transition.js:244)
    at Transition.updateStatus (Transition.js:213)
    at Transition.componentDidMount (Transition.js:157)
    at commitLifeCycles (react-dom.development.js:10888)
    at commitAllLifeCycles (react-dom.development.js:11670)
    at HTMLUnknownElement.callCallback (react-dom.development.js:1299)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:1338)
    at invokeGuardedCallback (react-dom.development.js:1199)

The behavior can be reproduced on the documentation of Material-UI

**What is the expected behavior?**

It shouldn't throw an error.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

- react-transition-group: latest
- react: next

Also related to https://github.com/facebook/react/issues/10294

**Comment by oliviertassinari** [comment]
Ok, the issue seems to be linked to a duplicate version of React. Could you update the peer dependency? Thanks!

**Comment by Unforgiven-wanda** [comment]
@oliviertassinari I'm experiencing this issue as well. Could you please explain what you mean by "update the peer dependency"? As far as I'm aware, all my dependencies are at their latest version

**Comment by wilhelma78** [comment]
I am having the same issue with latest versions:
react 16.0.0-rc.2
react-dom 16.0.0-rc.2
react-transition-group 2.2.0
material-ui 1.0.0-beta.9

> ReactBaseClasses.js:66 Uncaught TypeError: this.updater.enqueueCallback is not a function
>     at Transition../node_modules/react-transition-group/node_modules/react/lib/ReactBaseClasses.js.ReactComponent.setState (ReactBaseClasses.js:66)
>     at Transition.safeSetState (Transition.js:294)
>     at Transition.performEnter (Transition.js:244)
>     at Transition.updateStatus (Transition.js:213)
>     at Transition.componentDidMount (Transition.js:157)
>     at commitLifeCycles (react-dom.development.js:11511)
>     at commitAllLifeCycles (react-dom.development.js:12302)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:1309)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:1348)
>     at invokeGuardedCallback (react-dom.development.js:1205)
>     at commitAllWork (react-dom.development.js:12423)
>     at workLoop (react-dom.development.js:12695)
>     at HTMLUnknownElement.callCallback (react-dom.development.js:1309)
>     at Object.invokeGuardedCallbackDev (react-dom.development.js:1348)
>     at invokeGuardedCallback (react-dom.development.js:1205)
>     at performWork (react-dom.development.js:12808)
>     at batchedUpdates (react-dom.development.js:13262)
>     at performFiberBatchedUpdates (react-dom.development.js:1656)
>     at stackBatchedUpdates (react-dom.development.js:1647)
>     at batchedUpdates (react-dom.development.js:1661)
>     at Object.batchedUpdatesWithControlledComponents [as batchedUpdates] (react-dom.development.js:1674)
>     at dispatchEvent (react-dom.development.js:1884)

**Comment by plievone** [comment]
React 16 is RC now, so I guess the [peer dependencies](https://github.com/reactjs/react-transition-group/blob/8793a15/package.json#L43-L46) of this package should be updated to something like
```
"react": "^15 || ^16",
"react-dom": "^15 || ^16"
```
or `>=15` or similar, so that there is only one version of React in use. I have not tested the compatibility, however.

**Comment by koba04** [comment]
I can't reproduce this error on React v16.0.0-rc3.
Could you provide an example this error occur?

**Comment by tfuqua** [comment]
I get the error after upgrading to React V16.

**Current Versions**
"material-ui": "1.0.0-beta.12"
"react": "v16.0.0-rc3",
"react-dom": "v16.0.0-rc3"

**Error**
![image](https://user-images.githubusercontent.com/6877570/30873483-6c0ecfc8-a2bb-11e7-8640-18683d9f68da.png)

**Comment by gdi2290** [comment]
Here's a "fix"
add these resolutions to your package.json
```
  "resolutions": {
    "react": "16.0.0",
    "react-dom": "16.0.0"
  },
```
then `yarn install`

**Comment by tfuqua** [comment]
Hmm, not sure that resolves the issue for me. I've never used 'resolutions' before, how does this fix the issue?

**Comment by yoanisgil** [comment]
I added the resolutions section as suggested but still getting the same error.

**Comment by yoanisgil** [comment]
In my case I was able to work around this by downgrading to react v15.6.1

**Comment by fernandopasik** [comment]
As a workaround I added the following postinstall script:

```
"scripts": {
    "postinstall": "del-cli node_modules/react-transition-group/node_modules
}
```

**Comment by gdi2290** [comment]
yarn allows you to use resolutions which means only use one module. In this case, make sure everyone is using react 16 even though they didn't update their package's peer dep

**Comment by oliviertassinari** [comment]
Closed by #198 :)

**Comment by fernandopasik** [comment]
cool! Is there a release coming soon @jquense ?

**Comment by lukeapage** [comment]
and for v1...
https://github.com/reactjs/react-transition-group/pull/203
