### ISSUE TITLE
Appear and exit/disapear an Overlay

### ISSUE THREAD

**Issue by hmontes** [reactjs/react-transition-group#153]
I want to appear and disappear a Overlay for a Modal and Sidebar with animation. But i can't do the exit animation. Why?

https://jsfiddle.net/z4r6xu6m/

Where is my mistake? I want to put the animation inside of overlay component (if is possible) or maybe:

```
  <SomeWorkingAnimation>
    <Overlay>
   </SomeWorkingAnimation>
   <AnotherWorkingAnimation>
     <Modal>
   </Anot...>
```

Thank you

**Comment by jquense** [comment]
your conditional rendering removes the Overlay before the Transition component can exit it. you need to let the Transition component control when the component mounts or un mounts

https://jsfiddle.net/tf86ddab/

**Comment by hmontes** [comment]
Do you have another example for that? Your example doesn't work (And i really want to understand that.)

**Comment by jquense** [comment]
sorry typo: https://jsfiddle.net/1mxkuvmu/

**Comment by hmontes** [comment]
Thank you so much :)

Now i want to translate this css to style. I think i can with <Transition>

Thank you again

**Comment by hmontes** [comment]
Final and working version

https://jsfiddle.net/n2j01nx2/
