### ISSUE TITLE
Duplicate class names are removed from entering components

### ISSUE THREAD

**Issue by Metamist** [reactjs/react-transition-group#158]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Duplicate class names are removed.
When a component enters **after** the initial render, all duplicate class names are removed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

~~https://jsfiddle.net/e9nL8owh/2/~~
https://jsfiddle.net/o545sbbz/ (Better example using template)

Check the class names of the entered element with chrome's inspection tool, it should be `test derp test test` but instead results in `test derp`
The initial item that is added in the constructor has the proper class name.
When you add an item, the duplicate class names are removed from the new item.

**What is the expected behavior?**
Class names should remain the same.
Semantic UI relies on having duplicate class names for their grid component, like this:
```html
<div className='ui grid'>
  <div className='four wide tablet six wide computer column'>
  </div>
</div>
```
Instead, because of this bug it results in:
```html
<div className='ui grid'>
  <div className='four wide tablet six computer column'>
  </div>
</div>
```
Which breaks the grid completely.

If this is a chrome-only bug, which so far it seems like it, why does it **only** affect components that enter **after** the initial render (i.e. using setTimeout)? If I add some entries to the content state array in the constructor rather than setTimeout, the class names are still there.
If you get rid of the FadeTransition (CSSTransition) component, it works fine and the duplicate class names are not removed.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
I've got Chrome Version 60.0.3112.90 (Official Build) (64-bit) running on Arch Linux (don't think that matters imo)
No clue if it worked on previous versions.
It seems to be working fine in Firefox. The class names are still there. Maybe it only happens on chrome?
I will test it out on internet explorer and edge later today.
Edit: Seems like the component isn't even rendered in Internet Explorer, and I can't seem to figure out how to inspect elements in Microsoft Edge.

**Comment by jquense** [comment]
We don't do anything special here for deduping classes, I think you are just seeing the native browser behavior when you add multiple classNames via the DOM apis, e.g. 

```js
document.getElementsByClassName('container')[0].classList.add('container')
```

Only results in one class. I'm not sure we can support this case, and i'd venture to say that SemanticUI is depending on really undefined behavior here...

**Comment by Metamist** [comment]
Apparently their library supports the specifications, but it depends on the interpretation. I may be able to solve it using `semantic-ui-react` instead which will handle this for me.
