### ISSUE TITLE
Expected a string... 

### ISSUE THREAD

**Issue by Gmunker** [reactjs/react-transition-group#160]
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in. Check your code at index.js:19.

```
import React, { Component } from 'react'
import { CSSTransitionGroup } from 'react-transition-group';

let itemList = ["one", "two", "three"];

class About extends Component {

  render() {

    const items = itemList.map((item, i) => {
      return (
      <div key={item}>
        {item}
      </div>
    )});

    return (
        <div>
          <CSSTransitionGroup
            transitionName="example"
            transitionEnterTimeout={500}
            transitionLeaveTimeout={300}>
            {items}
          </CSSTransitionGroup>
        </div>
    )
  }
}

export default About;
```

This may be something simple i'm overlooking, but no matter what I try I keep getting this error. Could someone please lend a hand.

**Comment by jquense** [comment]
Sounds like you may be using the v1I with v2, there is no `CSSTransitionGroup` component anymore

**Comment by Gmunker** [comment]
https://reactcommunity.org/react-transition-group/

Is this what i should be working with now?

**Comment by xgzl87** [comment]
yes

**Comment by Gmunker** [comment]
These docs are confusing me like hardcore. I can see how useful this can be, but i just can't figure it out.

**Comment by mattcarlotta** [comment]
Just ran into the same error. I reverted back to:
`npm install --save react-transition-group@1.2.0`

**Comment by lichtamberg** [comment]
Yeah this is absolutely confusing, have the same problem. @mattcarlotta solution also doesn't work for me unfortunately :(

**Comment by jquense** [comment]
ya'll there is no CSSTransitiongroup component anymore, that's why the error happens.

**Comment by jhanstra** [comment]
@jquense what do you mean there is no CSSTransitionGroup anymore? How do I use this package? Is it still being supported? I am very confused.

**Comment by jquense** [comment]
> How do I use this package?

@jhanstra please read the documentation http://reactcommunity.org/react-transition-group/

**Comment by mystrdat** [comment]
Wasted a few hours with this, goddamn great job with this psychotic transition.

**Comment by mystrdat** [comment]
`transition-group` was always a bittersweet letdown limping behind competing systems, these confusing API changes and abysmal new documentation are a cherry on the cake.

**Comment by lichtamberg** [comment]
JFWIW I don't remember it exactly anymore, but I tried multiple old versions of this package and one of the old versions started to work with my react version.. It was a version missmatch, which didn't trigger any warnings but lead to this error.

**Comment by chinodt** [comment]
Hi! I was with the same Issue and according to the previous comments effectively that component is out of date, I was googling and found this migration guide, I hope you find this useful
https://github.com/reactjs/react-transition-group/blob/master/Migration.md
