### ISSUE TITLE
Add support for multiple css classes

### ISSUE THREAD

**Issue by orobert91** [reactjs/react-transition-group#162]
Please add support support for multiple CSS classes in the transition name, so we can do things like this:

`transition-name:"fade fade-slow"`

**Comment by koba04** [comment]
@orobert91 The above case, what do you expect to apply the className? `fade-enter fade-slow-enter`?

**Comment by orobert91** [comment]
This would seem the right naming to me

**Comment by jquense** [comment]
We aren't adding features to the v1 line anymore. V2 already supports specifying multiple classes if you specify for each stage

**Comment by koba04** [comment]
Right, something like this.

```
classNames={{
 enter: 'fade-enter fade-slow-enter',
 enterActive: 'fade-active-enter fade-slow-active-enter',
 exit: 'fade-exit fade-slow-exit',
 exitActive: 'fade-active-exit fade-slow-active-exit'
}}
```
