### ISSUE TITLE
Is there a way to exclude a node from transitions?

### ISSUE THREAD

**Issue by wwqrd** [reactjs/react-transition-group#166]
For example:

```
<TransitionGroup>
  { showSomethingInstantly && <div transition={false}>{node}</div> }
  { nodes.map(node => <div>{node}</div>) }
</TransitionGroup>
```

I realise that you could put it outside the `<TransitionGroup />`, but this is an inline list and that would affect the layout.

**Comment by jquense** [comment]
Not explictly but you can use different Transition components...something like:

```jsx
const InstantTransition (props) => 
  <Transition {...props} timeout={0} ><div>{props.children}</div></Transition>

<TransitionGroup>
  { showSomethingInstantly && <InstantTransition>{node}</InstantTransition> }
  { nodes.map(node => <Fade>{node}</Fade>) }
</TransitionGroup>
```

**Comment by wwqrd** [comment]
Ah thanks, I'm currently using the v1 spec, so perhaps this is a reason to upgrade! Unless there's a way to to do it with the old components?

**Comment by jquense** [comment]
No good way to do it with v1 unfortunately, it's on of the reasons for the API change :)

**Comment by wwqrd** [comment]
Well thanks for the knowledge!

When I get a chance to do the upgrade I'll see if I can contribute something to the docs.
