### ISSUE TITLE
Style instead of css classes

### ISSUE THREAD

**Issue by hmontes** [reactjs/react-transition-group#169]
Hi

```
import CSSTransition from 'react-transition-group/CSSTransition'

import './Opacity.css'

const Animation = ({ children, ...props }) => (
  <CSSTransition
    {...props}
    timeout={300}
    classNames="opacity"
  >
    {children}
  </CSSTransition>
)

Animation.defaultProps = {
  mountOnEnter: true,
  unmountOnExit: true
}
```

How can i do this without the css classes?? I want to do this in a EASY WAY with style inline in the component. (style={{ ....}})

I ask this because i'm using next.js and is a pain handle with external css.

Thank you

**Comment by jquense** [comment]
You can use the plain ol transition component and style
