### ISSUE TITLE
ReactCSSTransitionGroup - Animated component not removed from DOM

### ISSUE THREAD

**Issue by ladz** [reactjs/react-transition-group#17]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When ReactTransitionGroup is used like this (also compare http://codepen.io/ladz/pen/bgzYZG?editors=0010)
```
<CSSTransitionGroup
  transitionName="animatedFullscreenOverlay__anim"
  transitionEnterTimeout={0}
  transitionLeaveTimeout={0}
>...
```
(setting `transitionEnterTimeout` and `transitionLeaveTimeout` to zero) the children of `<CSSTransitionGroup/>` are not removed when the `leave`-animation completed. However, it can be fixed by settings both values to `1`.

**Which versions of React, and which browser / OS are affected by this issue?**
- React 15.4.2
- Safari on iOS 7.1.2 and native Android browser (Android 4.4.2)

CodePen: http://codepen.io/ladz/pen/bgzYZG?editors=0010

**Comment by jquense** [comment]
hey there, I took a look with the latest version and didn't this issue. From what I can see the div is removed fully on leave. http://codepen.io/anon/pen/QpOpKo?editors=0010

I'm gonna close (sorry about the delay) feel free to ping back though if I misunderstood the problem
