### ISSUE TITLE
Getting "Unknown props `onExited`, `appear`, `enter`, `exit` on <div> tag." warning on TransitionGroup

### ISSUE THREAD

**Issue by neginbasiri** [reactjs/react-transition-group#170]
**Do you want to request a *feature* or report a *bug*?**
I am trying to smooth adding/removing list items. I get the transition on show however on remove the transition is not working and I got a warning on Transition Group
**What is the current behavior?**
I am trying to smooth adding/removing list items. I get the transition on show however on remove the transition is not working and I got a warning on Transition Group.I have no properties passed to TransitionGroup!!!
"Unknown props `onExited`, `appear`, `enter`, `exit` on <div> tag."
I am getting warning on TransitionGroup Unknown props `onExited`, `appear`, `enter`, `exit` on <div> tag.
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

**What is the expected behavior?**
Having transition when list getting updated both for adding and removing

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
I am using Windows 10, Chrome latest version (auto update)

**Comment by jquense** [comment]
do you have an example where this is happening?

**Comment by neginbasiri** [comment]
Yes - Here is the code https://stackoverflow.com/questions/45750840/unknown-property-on-transitiongroup-react-animation?noredirect=1#comment78459065_45750840

**Comment by jquense** [comment]
You Transition (TripRow) component needs to be the direct children of the Transition group,which is injecting props into the div you have there instead
