### ISSUE TITLE
Uncaught ReferenceError: FadeTransition is not defined

### ISSUE THREAD

**Issue by Fadeoc** [reactjs/react-transition-group#171]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Nothing renders

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

The very example from https://reactcommunity.org/react-transition-group/, with React imported.

```
import React from 'react';
import TransitionGroup from 'react-transition-group/TransitionGroup';

class TodoList extends React.Component {
  constructor(props) {
    super(props);
    this.state = {items: ['hello', 'world', 'click', 'me']}
  }
  handleAdd() {
    const newItems = this.state.items.concat([
      prompt('Enter some text')
    ]);
    this.setState({ items: newItems });
  }
  handleRemove(i) {
    let newItems = this.state.items.slice();
    newItems.splice(i, 1);
    this.setState({items: newItems});
  }
  render() {
    return (
      <div>
        <button onClick={() => this.handleAdd()}>Add Item</button>
        <TransitionGroup>
          {this.state.items.map((item, i) => (
            <FadeTransition key={item}>
              <div>
                {item}{' '}
                <button onClick={() => this.handleRemove(i)}>
                  remove
                </button>
              </div>
            </FadeTransition>
          ))}
        </TransitionGroup>
      </div>
    );
  }
}

export default TodoList;
```

```
import React from 'react';
import ReactDOM from 'react-dom';

import TodoList from'./messaround/trans';

class Test extends React.Component {
  render() {
    return (
      <div>
        <TodoList />,
      </div>
    );
  };
}

ReactDOM.render(
  <Test />,
  document.getElementById('reactWrapper')
);
```

**What is the expected behavior?**
Run example on the official documentation normally.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome latest

**Comment by jquense** [comment]
You need to have a FadeTransition component somewhere, the error you getting is fairly clear as to what is wrong. The doc examples illustrate the API the and how to use stuff they aren't necessarily copy and pasteable

**Comment by Fadeoc** [comment]
@jquense Thanks for the reply, yes, you are quite right. 

But I googled that before new this issue, couldn't find any npm module supply a FadeTransition component, if I removed that ie

```
        <TransitionGroup>
          {this.state.items.map((item, i) => (
              <div key={item}>
                {item}{' '}
                <button onClick={() => this.handleRemove(i)}>
                  remove
                </button>
              </div>
          ))}
        </TransitionGroup>
```

the browser would tell that

`Warning: Unknown props "onExited", "appear", "enter", "exit" on <div> tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop`

Then, the page rendered, add item works but n

**Comment by jquense** [comment]
you need to write the Fade transition, or whatever transition you want. check out all the documentation: https://reactcommunity.org/react-transition-group/#CSSTransition

**Comment by gaoqiang19514** [comment]
```
const FadeTransition = props => (
  <CSSTransition
    {...props}
    addEndListener={(node, done) => {
      node.addEventListener('transitionend', done, false)
    }}
  />
)
```
then
```
     <FadeTransition key={state ? "Goodbye, world!" : "Hello, world!"}
       classNames='fade'
     >
       <button onClick={() => setState(state => !state)}>
         {state ? "Goodbye, world!" : "Hello, world!"}
       </button>
     </FadeTransition>
   </SwitchTransition>
```

**Comment by Fadeoc** [comment]
> ```
> const FadeTransition = props => (
>   <CSSTransition
>     {...props}
>     addEndListener={(node, done) => {
>       node.addEventListener('transitionend', done, false)
>     }}
>   />
> )
> ```
> 
> then
> 
> ```
>      <FadeTransition key={state ? "Goodbye, world!" : "Hello, world!"}
>        classNames='fade'
>      >
>        <button onClick={() => setState(state => !state)}>
>          {state ? "Goodbye, world!" : "Hello, world!"}
>        </button>
>      </FadeTransition>
>    </SwitchTransition>
> ```

Thank you

**Comment by rendomnet** [comment]
@gaoqiang19514 how can this be done with **Transition** and not the **CSSTransition**? There is 0 examples of this.
