### ISSUE TITLE
classname is error

### ISSUE THREAD

**Issue by hyy1115** [reactjs/react-transition-group#175]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

![image](https://user-images.githubusercontent.com/9842036/29706610-f9be3eaa-89b4-11e7-9e10-d8ebeb0b2992.png)
I have three animations, normal, left, right, use redux control animation default state is normal, when I click on a route, the implementation of a dispatch action operation, redux in the normal to left, enter part of the show normal, But exit shows normal-exit.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

This is the correct effect in V1：https://hyy1115.github.io/huangyongyue

**What is the expected behavior?**

In V1, the normal performance is that the default state is normal, when I click on the routing switch, the implementation of the action ('left'), then the DOM element shows
```html
<div class = "left-enter left-enter-active"> </ div>
<div class = "left-leave left-leave-active"> </ div>
```
In V2, it is the wrong state.
```html
<div class = "left-enter left-enter-active"> </ div>
<div class = "normal-exit normal-exit-active"> </ div>
```
I hope it is so：
```html
<div class = "left-enter left-enter-active"> </ div>
<div class = "left-exit left-exit-active"> </ div>
```

The problem here is that the entry and exit of the animation is not consistent, I do not know the problem caused by asynchronous action or V2 itself is a defect, because he is in the good performance of V1.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

 "react-transition-group": "^2.2.0"
chrome：60.0.3112.101

**Comment by jquense** [comment]
please post the actual code for the transition. I can't guess why you might be seeing this without an example reproducing it :)

**Comment by hyy1115** [comment]
I now have only one implementation of V1: https: //github.com/hyy1115/react-redux-webpack3/blob/master/src/App.js. I tried to follow the upgrade you provided V2 tutorials to modify the above problems.
The modification is probably like this:
```javascript
import {TransitionGroup, CSSTransition} from 'react-transition-group'

class A extends React.Component {
    render() {
        const {animateCls} = this.props
        return (
            <TransitionGroup>
                <CSSTransition 
                    key={location.pathname}
                    classNames={animateCls} 
                    enter={true}
                    exit={true}
                    timeout={{exit: 400, enter: 400}}
                >
                    <div>
                        <Route location={location} exact path="/" component={homeContainer} />
                        <Route location={location} path="/search" component={Search} />
                        <Route location={location} path="/bookList/:bookId" component={BookList} />
                    </div>
                </CSSTransition>
            </TransitionGroup>
        )
    }
}

```

**Comment by jquense** [comment]
Im sorry, it's just not possible to see what the error might be unless you post a complete example. Just looking at the above the problem is probably what animateCls is but I don't see a usage example so it's hard to know. Seeing the v1 code isn't helpful as you aren't using that API any

**Comment by hyy1115** [comment]
Well, I do not upgrade for the time being. I found that you have only one classname, such as example, or fade, but I want to implement a different classname when clicking on a different route. Perhaps you can publish a Related demo

**Comment by jquense** [comment]
There are a few examples in the issues here you can poke through for route transition examples yeah
