### ISSUE TITLE
Requires valid React-components for children

### ISSUE THREAD

**Issue by codeclown** [reactjs/react-transition-group#177]
**Do you want to request a *feature* or report a *bug*?**

Bug.

**What is the current behavior?**

When a non React component is among the children to `CSSTransition`, an error is thrown.

Common example of when a non React component is among the DOM would be a conditionally rendered component, like so:

```js
<CSSTransition>
  <div>Regular React component</div>
  {showLoading && <div>Loading...</div>}
</CSSTransition>
```

This convention is encouraged by [React docs](https://facebook.github.io/react/docs/conditional-rendering.html#inline-if-with-logical--operator).

> If it is false, React will ignore and skip it.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

https://jsfiddle.net/9gow6kfh/1/

**What is the expected behavior?**

No error should be thrown when a non React component is among the children to `CSSTransition`.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Not relevant.

**Comment by Chopinsky** [comment]
I think this may not actually be a bug, you need to wrap all the inner content under 1 single div for the `CSSTransition` component. The following code will compile and run correctly:

`
<CSSTransition>
  <div>
    <div>Regular React component</div>
    {showLoading && <div>Loading...</div>}
  </div>
</CSSTransition>
`

**Comment by jquense** [comment]
Yeah the problem is not the false, but the multiple children. CssTransition expects one child

**Comment by codeclown** [comment]
Oh, OK, my bad then. I suppose there is no `CSSTransitionGroup` equivalent to the old API?

**Comment by jquense** [comment]
There is is TransitionGroup, check out the migration guide as well, it may help.
