### ISSUE TITLE
`in` is a bad name, just like `class`.

### ISSUE THREAD

**Issue by trungdq88** [reactjs/react-transition-group#178]
I can't use `const { in, ...rest } = this.props;` because `in` is a reserved word. Imagine how inelegant the code is to get the `rest` variable.

```
const props = {...this.props};
const _in = props.in;
delete props.in;

<Transition in={_in} timeout={300}>
  <Component {...props} />
</Transition>
```

(React use `className` instead of `class` for the same reason)

This makes me feel so bad :(
Is there the other way...?

**Comment by jquense** [comment]
`{ in: _in, ...rest} = props` isn't so bad. I agree tho it's a bit inconvenient and we've gone through this a few times, but it's the most descriptive name so we're gonna stick with it. (btw react may actually switch to just class like practice and inferno)

**Comment by trungdq88** [comment]
Thanks, I'll stick with `{in: _in, ...rest}`.
