### ISSUE TITLE
CSS animations no effect during [ENTERING]

### ISSUE THREAD

**Issue by carllx** [reactjs/react-transition-group#179]
**Do you want to request a *feature* or report a *bug*?**
I'm not sure if I'm using it wrong (then it's a bug)  , the problem  similar in  #157 

**What is the current behavior?**
CSS animations disability effect during [ENTER] -- [**ENTERING**] --- [ENTERED]

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via jsfiddle**
[ Demo on jsfiddle ](https://jsfiddle.net/carllx/4kvmxjhe/5/)

**What is the expected behavior?**
The ball should be scaled up smoothly on ['ENTERING']  💪

**Comment by jquense** [comment]
Css transitions have a few quirks, you often have make sure classes are added between reflows. The CssTransition component handles this for you while the lower level Transition component requires you handle it. If your not super familiar with those quirks we recommend using the CssTransition

**Comment by carllx** [comment]
thx  @jquense , I will try Css transition , close#179
