### ISSUE TITLE
react-transition-group upgrade guide v1 to v2 clarification

### ISSUE THREAD

**Issue by kopax** [reactjs/react-transition-group#181]
I am trying to migrate `react-transition-group` from v1 to v2 following the [migration guide](https://github.com/reactjs/react-transition-group/blob/master/Migration.md#wrapping-transition-components) for this [component](https://github.com/reactstrap/reactstrap/blob/master/src/Fade.js#L67). 
 > The old <TransitionGroup> component managed transitions through custom static lifecycle methods on its children. In v2 we removed that API in favor of requiring that <TransitionGroup> be used with a <Transition> component, and using traditional prop passing to communicate between the two.

What does that mean for example in [reactstrap](https://github.com/reactstrap/reactstrap/blob/master/src/Fade.js#L67) they use `componentWillAppear` lifecycle method from v1...

For example, how is it possible to migrate this [Fade](https://github.com/reactstrap/reactstrap/blob/master/src/Fade.js#L67)?

**Comment by jquense** [comment]
https://github.com/react-bootstrap/react-bootstrap/blob/v4-support/src/Fade.js
