### ISSUE TITLE
Inner component renders multiple times

### ISSUE THREAD

**Issue by AlesMenzel** [reactjs/react-transition-group#185]
**Do you want to request a *feature* or report a *bug*?**
A bug.

**What is the current behavior?**
Component inside the transition component is rendered multiple times.
Only happens with react-router Route element. As i am not sure if the issue is caused by transition group or the router, i am posting it here.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
Reproduction: https://jsfiddle.net/AlesMenzel/ebmjL5fb/4/

![](http://g.recordit.co/c0ivsxXq1J.gif)

**What is the expected behavior?**
Inner component is rendered once after the transition.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
I am running on Chrome 60, Windows 10. But it might happen on other OS/browsers too.

**Comment by yaodingyd** [comment]
@AlesMenzel It's not a bug. Because `CSSTransition` would add and remove class on the transition component, surly it will re-render each time its class gets updated.  Also you missed `location={location}` on your `switch` so the entering and exiting component are actually the same one.

**Comment by AlesMenzel** [comment]
I was confused as why it was re-rendering 7 times, as there should only be 3 steps (i.e. add enter class -> add enter active class -> remove classes).

But you are right, i was missing location prop for the switch, which actually fixes the issue and renders the component correctly 3 times as expected.

**Comment by AlesMenzel** [comment]
Anyways, i have updated the example to show working animation with react-router v4. Hope this will be helpful to anyone looking for transitions with 2.x

https://jsfiddle.net/AlesMenzel/ebmjL5fb/6/

![](http://g.recordit.co/v0T1mFDncu.gif)
