### ISSUE TITLE
[v1] CSSTransitionGroupChild transition end event not firing in Chrome

### ISSUE THREAD

**Issue by jeffchan** [reactjs/react-transition-group#186]
**Do you want to request a *feature* or report a *bug*?**
Bug in v1.2.0 CSSTransitionGroupChild due to bug in [dom-helpers](https://github.com/react-bootstrap/dom-helpers/issues/31)

**What is the current behavior?**
The transitionEnd event is not correctly firing.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
See: https://github.com/react-bootstrap/dom-helpers/issues/31

**What is the expected behavior?**
transitionEnd event should fire.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome 61

**Comment by taion** [comment]
i'm going to close this out due to how long it's been open, given that v1 is no longer getting updated
