### ISSUE TITLE
Tested with react-router v4? Enter transition not happening for me

### ISSUE THREAD

**Issue by Noitidart** [reactjs/react-transition-group#19]
I just tested the current version on npm. And its not working with react router v4. Is the currently published version here: https://www.npmjs.com/package/react-transition-group

The leave and appear transitions happen, however the enter transition is not happening. Here is how we use it in react router v4 - http://stackoverflow.com/a/42042780/1828637

However the one shipping with react currently works great. I currently get from `react-addons-css-transition-group` - https://www.npmjs.com/package/react-addons-css-transition-group

**Comment by jquense** [comment]
try with the latest version, it should fix this issue on the RG side of things at least
