### ISSUE TITLE
Use without timeout?

### ISSUE THREAD

**Issue by wmertens** [reactjs/react-transition-group#191]
**Do you want to request a *feature* or report a *bug*?**

A feature, I suppose. It seems that currently a transition requires a timeout and there is no way to specify when the transition is complete from the components entering/leaving.

Having the transition be decided by the children would be useful when switching routes in an SPA and there is data that needs to be fetched. The new route gets loaded due to the URL, but the old child sticks around until the new route is loaded.

**Comment by jquense** [comment]
The `Transition` component allows this via [addEndListener](https://reactcommunity.org/react-transition-group/#Transition-prop-addEndListener) and when used timeouts are optional (but recommended). We intentionally though do not allow timeout-less usage in the CSSTransition case because of the flakiness of transitionEnd events.

**Comment by wmertens** [comment]
Ooh I see, I was thinking that the addEndListener was notified when the transition is over, not that it was used to signal the end. Perfect!

**Comment by piotr-cz** [comment]
IMHO timeout shouldn't be required by _CSSTransition_ as it's not implemented there and it's use is misleading (it's not specified in docs, either)

ATM _CSSTransition_ component is inheriting propTypes from _Transition_ [here](https://github.com/reactjs/react-transition-group/blob/v2.2.1/src/CSSTransition.js#L14)

**Comment by jquense** [comment]
The docs say it inherits the prop types from transition. The reason it is requires is explained above

**Comment by piotr-cz** [comment]
I see, these need to be set up for _CSSTransition_ too

**Comment by jquense** [comment]
we take doc PR's if you want to send over something to make it clearer :)
