### ISSUE TITLE
CssTransition not working

### ISSUE THREAD

**Issue by mouhsinelonly** [reactjs/react-transition-group#195]
no css classes are added to element eg fade-enter, fade-exit

`<CSSTransition
    in
    appear={false}
    classNames='fade'
    timeout={duration}>
    {children}
  </CSSTransition>`

**Comment by jquense** [comment]
Can you provide a working repro via the js fiddle template thanks

**Comment by alanwong22** [comment]
It works. The "appear" prop requires classes just like the "enter" states. It will conflict with the "in" prop if you are manually setting it due to how the classes fire. 
Here is my [Codepen Example](https://codepen.io/alanw/pen/LzxGRe)

**Comment by mouhsinelonly** [comment]
My bad a forgot that only new introduced elements will be transitioned

**Comment by MaxInMoon** [comment]
@mouhsinelonly can you provide a little working exemple please?
