### ISSUE TITLE
Add React 16 Support

### ISSUE THREAD

**Issue by emilyrohrbough** [reactjs/react-transition-group#199]
### Feature Request
`react-transition-group` provides support for `react  v^15.0.0`. React 16 is expected to be released soon and can currently be tested with `react 16.0.0-rc` (more information can be found on https://github.com/facebook/react/issues/10294).

`react-transition-group` is a dependency in a package in the [terra-core monorepo](https://github.com/cerner/terra-core), which will need to be React 16 compatible. From my initial assessment of our repository, it seems focus-trap behaves as expected with `react v16.0.0-rc`, but confirmed testing is needed.

**Comment by taion** [comment]
already have a PR in https://github.com/reactjs/react-transition-group/pull/198

**Comment by lukeapage** [comment]
@taion please can this be backported to v1 ? We have to use v1 because of velocity-react..
https://github.com/twitter-fabric/velocity-react/issues/224
