### ISSUE TITLE
ReactTransitionGroup: Rendering a Single Child

### ISSUE THREAD

**Issue by petermikitsh** [reactjs/react-transition-group#20]
**Do you want to request a *feature* or report a *bug*?** Bug

**What is the current behavior?** In the "Rendering a Single Child" [FB](https://facebook.github.io/react/docs/animation.html#rendering-a-single-child) documentation / [readme](https://github.com/reactjs/react-transition-group#rendering-a-single-child), coders are encouraged to pass in prop `component = null` for `ReactTransitionGroup` like so if `childrenArray[0]` is not truthy:

```js
function FirstChild(props) {
  const childrenArray = React.Children.toArray(props.children);
  return childrenArray[0] || null;
}

<ReactTransitionGroup component={FirstChild}>
  {someCondition ? <MyComponent /> : null}
</ReactTransitionGroup>
```

However, if `null` is passed in as `component`, e.g.,

```js
var ReactTransitionGroup = React.addons.TransitionGroup;

var Hello = React.createClass({
  render: function() {
    return <ReactTransitionGroup component={null}/>;
  }
});

ReactDOM.render(
  <Hello />,
  document.getElementById('container')
);
```

The following console error is thrown:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: null. Check the render method of `ReactTransitionGroup`.
printWarning @ npmcdn.com/react@15.4.2/dist/react-with-addons.js:5276
npmcdn.com/react-dom@15.4.2/dist/react-dom.js:17903 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: null. Check the render method of `ReactTransitionGroup`.
    at invariant (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:17896)
    at ReactCompositeComponentWrapper.instantiateReactComponent [as _instantiateReactComponent] (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:16037)
    at ReactCompositeComponentWrapper.performInitialMount (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:4821)
    at ReactCompositeComponentWrapper.mountComponent (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:4712)
    at Object.mountComponent (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:11542)
    at ReactCompositeComponentWrapper.performInitialMount (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:4825)
    at ReactCompositeComponentWrapper.mountComponent (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:4712)
    at Object.mountComponent (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:11542)
    at ReactCompositeComponentWrapper.performInitialMount (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:4825)
    at ReactCompositeComponentWrapper.mountComponent (npmcdn.com/react-dom@15.4.2/dist/react-dom.js:4712)
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar.** See https://jsfiddle.net/urLq585z/ and open your console.

**What is the expected behavior?** No error should be thrown when `null` is passed as the `component` prop to `ReactTransitionGroup`. Nothing should render. I'd also like to point out that if you don't explicitly set component to null, e.g., render ` <ReactTransitionGroup />` the error is not present the default component prop is a [span tag](https://github.com/reactjs/react-transition-group/blob/master/src/TransitionGroup.js#L15).

**Which versions of React, and which browser / OS are affected by this issue? Did this work in previous versions of React?** Latest version of React; I am on Chrome 56 on MacOS. Unsure about previous versions; presumably also broken.

(originally reported at https://github.com/facebook/react/issues/9056)

**Comment by jquense** [comment]
Hey @petermikitsh sorry for the delay responding. You aren't actually following the example correctly here. `component` **cannot** be null, but it can _render_ `null`. See the above. `FirstChild` is actually a react component that renders nothing, _or_ it's first child. This si different than setting the `component` to null! It's a pretty confusing suggestion i'll admit. Myself I have a hard time understanding why it works without really thinking about it :P

**Comment by hmontes** [comment]
@jquense Can you explain please? I cannot understand that option: <ReactTransitionGroup component={FirstChild}>

Do you have an example with code? (easy to understand)

**Comment by petermikitsh** [comment]
@hmontes Trying to help clarify here. There is a difference between:

```jsx
function FirstChild(props) {
  const childrenArray = React.Children.toArray(props.children);
  return childrenArray[0] || null;
}

<ReactTransitionGroup component={FirstChild}>
  {someCondition ? <MyComponent /> : null}
</ReactTransitionGroup>
```

and 

```jsx
<ReactTransitionGroup component={null}>
  {someCondition ? <MyComponent /> : null}
</ReactTransitionGroup>
```

In the first example, the provided component prop is function -- and more precisely, a stateless, functional React component.

In the second example, you're simply passing in `null`.

The API for `ReactTransitionGroup` expects the component prop to be, well, a component. So the error I was seeing and reported here is the expected behavior. `null` isn't a component.

And to further clarify, and this is probably what tripped me up at the time, is that components can *render* null.

So if you declare FirstChild like so:

```js
function FirstChild() {
  return null;
}
```

You can pass that in to `ReactTransitionGroup` as the `component` prop since it's a valid React component.

**Comment by silvenon** [comment]
@solonaarmstrong what do you mean by public-facing? Those docs are being deployed on each release, I think.

**Comment by silvenon** [comment]
I'm talking about the docs in the `www` directory, not Storybook.
