### ISSUE TITLE
x.1 TransitionGroup not firing special life cycle methods

### ISSUE THREAD

**Issue by nnnoel** [reactjs/react-transition-group#201]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

No feedback from the special life cycle hooks in my TransitionGroup child component.

https://stackoverflow.com/questions/44569424/react-transition-group-lifecycle-method-componentwillleave-not-being-called
https://stackoverflow.com/questions/43792079/transition-group-not-firing-life-cycle-methods

These haven't been answered yet regarding the same issue

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

https://codesandbox.io/s/wkon7xoxll

`components/Environment.js:46` -- Is where I have my TransitionGroup. Inside it is a getter for the component associated with the current url route.

I tried
```
        <TransitionGroup component='div'>
          {this.activeComponent}
        </TransitionGroup>
```
and
```
<TransitionGroup component={this.activeComponent}/>
```

**What is the expected behavior?**

I expect the extra hooks (componentWillEnter, componentWillUnmount) to be called whenever the child component is added or removed from the TransitionGroup.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

- react-transition-group 1.x
- react and react-dom 16
- Chrome latest version
- macOS 10.12.6

**Comment by jquense** [comment]
There are no extra hooks anymore in the TransitionGroup API since v2 (see the documentation and migration guide), however `componentWillUnmount` isn't special its a React hook and is called when the defining component unmounts not when its children do.

**Comment by nnnoel** [comment]
I meant ```componentWillLeave``` not ```componentWillUnmount```, that one works fine.

They're currently listed in the docs for 1.x, so it's confusing whether or not they still work for 1.x

**Comment by jquense** [comment]
they do work for v1. but they need to be specified on the child component not the parent

**Comment by nnnoel** [comment]
I have them specified on the child and they're not all working.

For example in ```/components/Home.js```, `componentWillEnter` logs fine, but `componentWillLeave` doesn't. Even after I manually invoke the callback.

**Comment by jquense** [comment]
I think the routing component is getting in the way, e.g. active component is wrapped. I'm not sure how to use it with RR but you might want to search for that

**Comment by nnnoel** [comment]
The routing is fine. The getter returns the correct react element, which is all it should be doing.

Turns out the only way I can get this to work is if I return the active component in an array.
