### ISSUE TITLE
React16 : react-transition-group@1.2.0 requires a peer of react@^15.0.0 but none is installed.

### ISSUE THREAD

**Issue by kopax** [reactjs/react-transition-group#207]
Currently, if you are using react-transition-group 1.2.0 with React16, the following warning will appear:

> npm WARN react-transition-group@1.2.0 requires a peer of react@^15.0.0 but none is installed. You must install peer dependencies yourself.
> npm WARN react-transition-group@1.2.0 requires a peer of react-dom@^15.0.0 but none is installed. You must install peer dependencies yourself.

Is it possible to release a 1.2.1 to remove these warnings ?

Thanks in advance,

**Comment by theskillwithin** [comment]
pleazzz

**Comment by momo28** [comment]
+1

**Comment by kopax** [comment]
I did a PR but apparently it's conflicting with a change made 1 day ago https://github.com/reactjs/react-transition-group/pull/209/conflicts
Seems like it's already resolved but not publish yet.

**Comment by landabaso** [comment]
+1

**Comment by LanguageXange** [comment]
anyone figured it out yet? I installed react-transition-group@1.2.1, same warnings
