### ISSUE TITLE
transitionEnter not working when animating from 0 to 1 child

### ISSUE THREAD

**Issue by rodrigobacelli** [reactjs/react-transition-group#21]
I'm trying to animate the first children enter, but it don't work proper. Ex:

```jsx
<CSSTransitionGroup
  transitionEnterTimeout={500}
  transitionLeaveTimeout={500}
  transitionName={'component'}
>
    {isSomeConditionTrue ? this.renderChildComponent() : null}
</CSSTransitionGroup>
```

When the child is rendered after condition is set to true, it doesn't trigger the `enter` animation, but `leave` animation works when the condition backs to true. The child has a unique key. I'm making a Fiddle file to demonstrate the bug.

I'm using npm's 1.0.0 version

**Comment by jquense** [comment]
try with the newest version (1.1.0) please?

**Comment by rodrigobacelli** [comment]
@jquense you can close this one. Now it's working.

Thanks!
