### ISSUE TITLE
Route component rendered twice in CSSTransitiongroup

### ISSUE THREAD

**Issue by ThunderboltSmile** [reactjs/react-transition-group#213]
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
When I wrap an routered component in CSSTransition , and when router has changed , the component which in Route will unmount twice:
```javascript
<TransitionGroup>
      <CSSTransition key={currentKey}
        timeout={timeout}
	unmountOnExit={true}
	mountOnEnter={true}
	classNames="fade">
		<section className="routes-container-section">
			<Switch>
				{
					routes.map(
					         (route,i)=><Route {...route} key={"route_"+i}/>
					)
				}
			</Switch>
		</section>
	</CSSTransition>
</TransitionGroup>
```

**Comment by iMerica** [comment]
For anyone experiencing this, add `exit={false}` to `<CSSTransition>`

**Comment by chen86860** [comment]
Add `location` props to `<CSSTransition location={location} />` resolve my problem.

**Comment by RTM909** [comment]
Hi, I have tried these solutions but still facing the same issue.

`<TransitionGroup>
  <CSSTransition
    key={window.location.pathname}
    classNames="fade"
    exit={false}
    unmountOnExit={true}
    mountOnEnter={true}
    timeout={300}>
    <Switch location={window.location}>
      {routes.map((page, key) => (
        <Route path={page.path} component={page.component} key={key} />
      ))}
      <Redirect exact from="/" to="/home" />
    </Switch>
  </CSSTransition>
</TransitionGroup>`

**Comment by RTM909** [comment]
Hi, I have tried these solutions but still facing the same issue.

```
<TransitionGroup>
      <CSSTransition key={currentKey}
        timeout={timeout}
	unmountOnExit={true}
	mountOnEnter={true}
	classNames="fade">
		<section className="routes-container-section">
			<Switch>
				{
					routes.map(
					         (route,i)=><Route {...route} key={"route_"+i}/>
					)
				}
			</Switch>
		</section>
	</CSSTransition>
</TransitionGroup>

**Comment by Felierix** [comment]
> For anyone experiencing this, add `exit={false}` to `<CSSTransition>`

Wait... If I set `exit` property to `false`, then what's the point of using transition group??? It doesn't even showing the transition...

**Comment by RTM909** [comment]
If anyone is still stuck then I found another github issue with the solution (will link it later, if I find it again).

```<PageContent>
                {routes.map(({ path, Component }) => (
                  <Route key={path} exact path={path}>
                    {({ match }) => (
                      <CSSTransition
                        in={match != null}
                        timeout={300}
                        classNames="page"
                        exit={false}
                        unmountOnExit>
                        <div className="page">
                          <Component history={this.props.history} />
                        </div>
                      </CSSTransition>
                    )}
                  </Route>
                ))}
              </PageContent>

This works for me. I don't get the exit animation but it's still good enough

**Comment by RTM909** [comment]
If anyone is still stuck then I found another github issue with the solution (will link it later, if I find it again).

```
<PageContent>
  routes.map(({ path, Component }) => (
    <Route key={path} exact path={path}>
      match }) => (
        <CSSTransition
          in={match != null}
          timeout={300}
          classNames="page"
          exit={false}
          unmountOnExit>
          <div className="page">
            <Component history={this.props.history} />
          </div>
          </CSSTransition>
        )}
      </Route>
    ))}
</PageContent>
```

This works for me. I don't get the exit animation but it's still good enough
