### ISSUE TITLE
Transitions on mount/unmount only work with CSS

### ISSUE THREAD

**Issue by Jpunt** [reactjs/react-transition-group#214]
Something like this works beautifully: 

```jsx
<TransitionGroup>
  {this.props.children &&
    <CSSTransition key={0} classNames="Modal" timeout={{enter: 200, exit: 150}}>
      <div style={styles.container}>
        <div style={styles.background} className="Modal-background" />    
        <div style={styles.content} className="Modal-box">{this.props.children}</div>
      </div>
    </CSSTransition>
  }
</TransitionGroup>
```

As soon as `children` get set/unset, the content is faded in and out (based on some css). But I'd want to do the same thing with a regular `Transition`: 

```jsx
<TransitionGroup>
  {this.props.children &&
    <Transition key={0} timeout={{enter: 200, exit: 150}}>
      {state => (
        <div style={styles.container}>
          <div style={{...styles.background, ...defaultStyle, ...transitionStyles[state]}} />
          <div style={{...styles.content, ...defaultStyle, ...transitionStyles[state]}}>{this.props.children}</div>
        </div>
      )}
    </Transition>
  }
</TransitionGroup>
```

This does not work. The children are shown immediately and when unset they instantly get removed, instead of waiting on the transition to finish. What am I doing wrong here?

By the way: My first instinct was to not use a `TransitionGroup`, but the combination of a `TransitionGroup` and a `CSSTransition` was the only way I could make this work.

**Comment by jquense** [comment]
When animating one component in and out you don't need TransitionGroup at all, you can just use a single Transition. As far as why you animation isn't working i'm not sure not seeing all the code, but it's probably due to needing to reflow between animations for the CSS transition to fire (see previous issues on this). You can checkl out the linked react-bootstrap transitions for an example on how to implement slightly more complicated css transitions with Transition (in the docs)

**Comment by Jpunt** [comment]
I've re-implemented this with `TransitionGroup` + `Transition` (instead of `CSSTransition`) and it does work now. I'm not sure what I've done differently, but it could be that it'll also work without the `TransitionGroup` 🤔 Will check that asap, thanks!

**Comment by sethbro** [comment]
This appears to me to be a legitimate & ongoing issue. Consider this minimal example, where I am attempting to fade in a component by hooking `onEnter` to an [anime.js](https://github.com/juliangarnier/anime/) function. 

```js
import anime from 'animejs';
import React from 'react';
import { Transition, TransitionGroup } from 'react-transition-group';

function animateIn(el, isAppearing) {
    debugger;
    anime({
        targets: el,
        duration: 5000,
        opacity: [0, 1]
    });
}

class AnimationTest extends React.Component {
    render() {
        return (
            <Transition
                appear={ true }
                key="animationTransition"
                onEnter={ (el, isAppearing) => { debugger; animateIn(el, isAppearing); } }
                onEntering={ (el, isAppearing) => { debugger; animateIn(el, isAppearing); } }
                onEntered={ (el, isAppearing) => { debugger; animateIn(el, isAppearing); } }
                timeout={ { enter: 0, exit: 500 } }
            >
                <div className="AnimationTest">
                    <span>I should fade in</span>
                </div>
            </Transition>
        );
    }
}

export default AnimationTest;

```
When I mount this component, no transition occurs & none of the `debugger` statements are ever fired. As soon as I wrap the `Transition` in a `<TransitionGroup>` (no props), everything works as expected.

I get the same behavior with versions `2.2.1`, `2.2.0`, `2.1.0`, and `2.0.0`.

**Comment by stmihai** [comment]
@sethbro looks like you're not setting the "in" prop anywhere. That's what's triggering the entering/entered states.
