### ISSUE TITLE
Update Lisence

### ISSUE THREAD

**Issue by withintheruins14** [reactjs/react-transition-group#221]
Is this still BSD 3-Clause License?

**Comment by jquense** [comment]
Yes... Why wouldn't it be?

**Comment by taion** [comment]
What is happening here exactly? This is BSD 3-Clause without the patent grant... was that the original license for the code here? Looks like this repo never had a patent grant.

**Comment by jquense** [comment]
The license is unchanged from when it was extracted. I have no idea what would be required to relicense tho

**Comment by withintheruins14** [comment]
@jquense Thanks, I wanted to be sure. I didn't know how or if this was effected by the recent license changes to react. I don't know this stuff *shrugs* 👍
