### ISSUE TITLE
rendering CSSTransitionGroup component failing using React v16

### ISSUE THREAD

**Issue by nchery** [reactjs/react-transition-group#226]
`**Do` you want to request a *feature* or report a *bug*?**
most likely a bug?

**What is the current behavior?**
I've upgraded to React v16. Since then rendering of the CSSTransitionGroup component is causing errors in the console and the component where it is used is not mounting.  
It returns 
"warning.js:33 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in."

Code is the 

```javascript
import React, { Component } from 'react';
import PropTypes from 'prop-types';
import { CSSTransitionGroup } from 'react-transition-group';

Class MainComponent extends Component {
 ...
  render() {
    const { someProp1, someProp2} = this.props;
    return (
      <div className="mt2 mb2">
        ...
        <CSSTransitionGroup
          component="div"
          transitionName="menuCtn"
          transitionEnterTimeout={300}
          transitionLeaveTimeout={300}
        >
          {someCondition && (
            ...some component
          )}
        </CSSTransitionGroup>
      </div>
    );
  }
}
```
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

**What is the expected behavior?**
should render as usual

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
"react": "~16.0.0",
"react-dom": "~16.0.0",
"react-transition-group": "~2.2.1",

**Comment by jquense** [comment]
CssTransitionGroup was removed in v2, check out the docs and migration guide for more info

**Comment by burgalon** [comment]
README.md still references CSSTransitionGroup
