### ISSUE TITLE
Any plans to support transitions of deeply nested components?

### ISSUE THREAD

**Issue by bdwain** [reactjs/react-transition-group#23]
It's currently difficult to do animations on unmount for deeply nested components if their parents are also unmounted because the transition group does not run componentWillLeave on them. Is there any plan to support this type of behavior (maybe using the context api?). I know it would greatly increase the complexity, but I'm just curious since it's a common issue I've seen people run into and current solutions I've seen involve making many unrelated pieces of the app aware of this transition.

**Comment by jquense** [comment]
We don't have any plans for that specifically since would add a lot of complexity. We do however, hope to get to a point where there are more exposed hooks that should make it easier to implement such things yourself (in ways that make sense for your specific use cases)

**Comment by bdwain** [comment]
cool. Thanks for the info. Is there anywhere I can see some examples of hooks you're planning to expose? I know nothing is finalized or anything, just trying to get a rough idea of the current direction.

**Comment by jquense** [comment]
#24
