### ISSUE TITLE
allow classNames to be omitted

### ISSUE THREAD

**Issue by WickyNilliams** [reactjs/react-transition-group#230]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

Currently a `classNames` must be supplied (despite it not being marked as isRequired).

**What is the expected behavior?**

It would be good for this to be _genuinely_ optional, where completely un-prefixed classes are used if `classNames` is not supplied. e.g. `enter`, `enter-active`, `exit`, `exit-active`.

In use with styled-components, the class prefixes are unnecessary, since all styling is encapsulated anyway. I can imagine cases outside of SC where people don't care about namespacing classes, and are happy to use compound css selectors e.g. `.my-component.enter`

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

N/A

**Comment by jquense** [comment]
in the SC case how would you write this without either specifying each class in `classNames` or writing global styles. If there was nothing specified you'd only be able to have one transition type, since you'd have the same classes being reused over and over again

**Comment by WickyNilliams** [comment]
Here's a reusable animation, using styled components. The "fade" part of classNames is completely redundant. 

```js
const Fade = styled(CSSTransition).attrs({
  classNames: "fade"
})`
  transition: opacity ${props => props.duration}ms ease-in;

  &.fade-enter {
    opacity: 0;
  }
  &.fade-enter.fade-enter-active {
    opacity: 1;
  }

  &.fade-exit {
    opacity: 1;
  }
  &.fade-exit.fade-exit-active {
    opacity: 0;
  }
`;
```

It would be better if I could omit classNames and have this:

```js
const Fade = styled(CSSTransition)`
  transition: opacity ${props => props.duration}ms ease-in;

  &.enter {
    opacity: 0;
  }
  &.enter.enter-active {
    opacity: 1;
  }

  &.exit {
    opacity: 1;
  }
  &.exit.exit-active {
    opacity: 0;
  }
`;
```

**Comment by jquense** [comment]
in the second case tho, the generated style names aren't actually going to be `enter` and `enter-active`, are they? I would think SC is going to prefix or hash them, meanwhile RTG is going to add the string 'enter' to the element node which won't be namespaced

**Comment by WickyNilliams** [comment]
No, it uses the classnames exactly as defined.

In any case, I just wanted to give you my use-case, but the feature request isn't specific to SC. It's perfectly reasonable to use a compound selector without the prefixed classnames, as I described.

**Comment by jquense** [comment]
If SC doesn't namespace classes how does it encapsulate styles? My point here is that allow in prefixed classes would mean you can only define one transition type per app. In your example above if you wanted a slide transition you couldn't because it would share the same classes names as Fade.

**Comment by jquense** [comment]
Ah duh sorry. I'm a bit dense today, you mean write them as descendant selectors.

**Comment by taion** [comment]
Hmm, is it a little odd that an empty string would give `.exited`, while e.g. `a` would give `.a-exited`?

Like I wonder if this is a niche enough use case that maybe users should just define a singleton constant object with the name mappings, then use that for `classNames` generically?

**Comment by WickyNilliams** [comment]
Yeah descendant or compound (`.my-component.enter`), since CSSTransition doesn't actually render anything right? The classes are applied to its child. I'm away from computer atm, so I could be wrong there...

I don't think it's particularly odd. I could reuse an object mapping but it involves extra effort in either remembering to pass the object each time, or remembering to always use your component that wraps it. In a team environment this can easily be forgotten.

If you decide to reject the proposal, you should mark the prop as required instead?

**Comment by WickyNilliams** [comment]
Hey @jquense, what did you decide?

**Comment by jquense** [comment]
gonna keep the same for now, but revisit in the future!

**Comment by WickyNilliams** [comment]
Cool. Are you going to at least mark classNames as a required prop?
