### ISSUE TITLE
Overriding dom elements w/ redux and react-transition-group

### ISSUE THREAD

**Issue by james-prado** [reactjs/react-transition-group#231]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Using redux with react-transition-groups causes dom elements to be overriden, [demo here](https://codesandbox.io/s/vvj1k1lqv3).

**What is the expected behavior?**
 The expected outcome is to have 1 child of `<div className="container"/>` per notification. What's actually happening, is only 1 child is being rendered and represents only the newest notification in the state. This causes problems when trying to display multiple notifications at once, and when animating them out before being unmounted.

The issue occurs in both v1, and v2, the v2 behaviour is described [here](https://github.com/reactjs/react-transition-group/issues/231#issuecomment-337713443) along with the [v2 demo](https://codesandbox.io/s/n0440xx3m0)

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
I'm testing this in google chrome, on macOS High Sierra 10.13, with react-transition-group v1.2.1 & v2.2.1

**Comment by WickyNilliams** [comment]
Why not upgrade to latest version of react-transition-group?

**Comment by james-prado** [comment]
I found react-transition-group through the react docs for animation, they referred me to the v-1 docs, I guess I just assumed that v1.x was stable, and v2 was still in beta or something.

**Comment by james-prado** [comment]
Ok so I forked the demo and migrated it to v2.2.1, [demo here](https://codesandbox.io/s/n0440xx3m0). The issue of only one child being appended to `<div className="container"/>` is fixed, but there is still a problem with elements being overridden. Now when you close the oldest notification (at the top), the element gets removed, before the animation occurs, then the most recent element (at the bottom) is duplicated and animated out instead of the original element.

**Comment by james-prado** [comment]
Ok, turns out the issue was using the notification index as a key is **VERY BAD** and messes up how data is displayed in react.

**Comment by WickyNilliams** [comment]
Yup, that'll be it. Same applies for anywhere you're using keys in react. They should be stable/consistent between renders
