### ISSUE TITLE
All CSSTransition's animate when a sibling is added or removed

### ISSUE THREAD

**Issue by james-prado** [reactjs/react-transition-group#233]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a list, each item is represented by a `<CSSTransition/>` and is a child of `<TransitionGroup/>`. Every time a transition is added or removed, all sibling transitions animate too. 

[Demo](https://codesandbox.io/s/n0440xx3m0)

**What is the expected behavior?**
I expect only the `<CSSTransition/>` that is added or removed should animate, not it's siblings.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Google Chrome, macOS High Sierra 10.13, react-transition-group v2.2.1, not sure if it occurs in earlier versions

**Comment by jquense** [comment]
Hi there, thanks for the codepen, could you please boil it down to just the Transition code demonstrating the problem. There is a lot of extra stuff there to wade through

**Comment by james-prado** [comment]
I abstracted all the redux stuff away into just the containers, all the transition code is in `components/notifications.js`. It should be easier to read now.

**Comment by yoadsn** [comment]
Don't recreate the `Transition` wrapper component upon every render. 
Extract it out of the render() method - This should solve it.
Here is a fixed fork.
https://codesandbox.io/s/6281wwwp8r

**Comment by james-prado** [comment]
@yoadsn Yup, your totally right. Thanks for the solution!
