### ISSUE TITLE
Any hints on performance for large lists? (200 items)

### ISSUE THREAD

**Issue by fernandofleury** [reactjs/react-transition-group#234]
Well, as the title says, it's more like a question.

I have a large list on my app (Which ATM can't be virtualised nor paginated, so I always render the 200 items), and I have some filters for that list, which is why I tried using the `transition-group`. But the unmounting of all items takes a while to be properly executed. I was trying to achieve a smooth transition if possible. Cause with my current implementation takes a couple seconds to fully update the UI.

**The sample was tested on Chrome, Safari and Firefox on OSX**

I was tinkering around with the options, cause it takes a while to unmount all components, **when a friend of mine tried adding the `onExited` callback to the `CSSTransition`, which noticeably increased the speed of the UI updating, is that intended?** (Please try removing the callback on the `list.js` file on the sandbox to see what I mean. (I've added a "footer" to show when all items are removed)

I've created a sandbox to mimic my current scenario: https://codesandbox.io/s/03w9y57j8n

What can I do to improve the speed overall? Is it possible to achieve a decent time on the UI update? Also, what about the `onExited` as I stated earlier, is that intended somehow?

Thanks!

**Comment by spbsamuel** [comment]
Faced the same issue. I figured I could just use TransitionGroup for the first few elements instead of the whole list. Doesn't solve the performance issue for large list but it's a good heuristic to improve the perceived performance.

```
<TransitionGroup>
  {listToRender.slice(0,6).map(item => <Fade>...</Fade>)}
</TransitionGroup>
{listToRender.slice(6).map(item => <div>...</div>)}
```

**Comment by fernandofleury** [comment]
Close due to staleness
