### ISSUE TITLE
Unnecessary re-rendering 

### ISSUE THREAD

**Issue by vietnogi** [reactjs/react-transition-group#235]
**Do you want to request a *feature* or report a *bug*?**
Performance issue

**What is the current behavior?**
When `TransitionGroup` children changes, its unchanged children re-renders.

**What is the expected behavior?**
When `TransitionGroup` children changes, its unchanged children should not re-renders.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
2.2.0

**Comment by taion** [comment]
That's really just how React components with children work. It'd be an odd violation of standard parent component guarantees to change that.
