### ISSUE TITLE
Can't set transition-duration conveniently

### ISSUE THREAD

**Issue by JesuisTong** [reactjs/react-transition-group#237]
**Do you want to request a *feature* or report a *bug*?**
maybe request a feature to control TransitionDuration
**What is the current behavior?**
Now this.props.timeout is just controlling the timing to trigger callback.
you should declare the true transition-duration in css, but both of them is totally same.
is there anyway to controll both of them but just use single parameter？It will be more concise.
THX
**What is the expected behavior?**
use one parameter to control duration.
**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome ver.61 | MAC

**Comment by taion** [comment]
The CSS animation duration is opaque from the component, so there's not a great way around this.
