### ISSUE TITLE
Elements not being properly animated / unmounted when TransitionGroup and CSSTransition are located in separate React components

### ISSUE THREAD

**Issue by parkroolucas** [reactjs/react-transition-group#240]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

`TransitionGroup` and `CSSTransition` cannot be physically located in two separate components.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

Say if I have this code:

```
<TransitionGroup>
  {this.state.stuff.map(() => <AnotherComponent />}
</TransitionGroup>
```

And inside of `AnotherComponent`, I have this:

```
<CSSTransition classNames={...} timeout={500}>
  <span>something</span>
</CSSTransition>
```

It won't animate; more correctly, it won't remove the element. All I need to do to get it working is put the `TransitionGroup` and the `CSSTransition` inside of the same component, and then it works. For example, combining the above two:

```
<TransitionGroup>
  {this.state.stuff.map(() => (
    <CSSTransition>
      ...
    </CSSTransition>
  )}
</TransitionGroup>
```

Will work.

**What is the expected behavior?**

It should animate, and should remove the element(s) as necessary.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Pretty sure it's just a logic issue, not a compatibility issue.

**Comment by jmca** [comment]
@parkroolucas This might resolve your issue. Make sure you are spreading props in your `AnotherComponent`. `TransitionGroup` passes down a few handlers via props.

Refer to this in the docs: 
https://reactcommunity.org/react-transition-group/#TransitionGroup-prop-children

Specifically this statement:

> children

> A set of <Transition> components, that are toggled in and out as they leave. the <TransitionGroup> will inject specific transition props, so remember to spread them through if you are wrapping the <Transition> as with our <Fade> example.

**Comment by parkroolucas** [comment]
Sounds good. I have not tested this yet, but it sounds logical to me. I'll close this issue until I'm 100% sure that it does not fix my use case. Thanks for the help.
