### ISSUE TITLE
Change the CSSTransition classnames on the go ?

### ISSUE THREAD

**Issue by aj120426394** [reactjs/react-transition-group#241]
[BUG]

What I try to achieve is the animation will depends on users' action. For example, when user click on the left, a new tab should fly from left in to the center and the current tab should fly out to the right. When users' next action is clicking on the right, a new tab will fly from the right into the center and the old tab should fly out to the left. 

With the previous version, CSSTransitionGroup allow me to change the applied transition style with the given condition.
```
import animationRight from './TabAnmiationRight.scss';
import animationLeft from './TabAnimationLeft.scss';
class Tab extends Component {
  render() {
    const { prevSelectedTab, index, selectedTab } = this.props;

    return (
      <CSSTransitionGroup
        transitionName={
          prevSelectedTab > selectedTab ? animationLeft : animationRight
        }
        transitionEnterTimeout={500}
        transitionLeaveTimeout={500}
      >
        {selectedTab === Number(index) &&
          <div
            className={classnames(scss.tabContainer)}
            key={`tab-${this.props.index}`}
          >
            {this.props.children}
          </div>}
      </CSSTransitionGroup>
    );
  }
}
```
Every time when selectedTab is changed, the CSSTransitionGroup will look for the matched animation. For my example here, if I click on **LEFT** first, the current tab will apply` animationLeft.exit -> animationLeft.exitActive ` and a new tab will apply `animationLeft.enter -> animationLeft.enterActive`. But when I click on the **Right** for the next step, the current tab will apply `animationRight.exit -> animationRight.exitActive` just like I expected .

Because of v1 doesn't provide onEnter, onExited function which is what I am looking for, I decide to switch to v2. 

With the v2, I try to do the similar stuff:
```
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import classnames from 'classnames';
import { Transition, CSSTransition, TransitionGroup } from 'react-transition-group';
import scss from './Tab.scss';
import animationRight from './TabAnmiationRight.scss';
import animationLeft from './TabAnimationLeft.scss';

class Tab extends PureComponent {
  shouldComponentUpdate(nextProps, nextState, nextContext) {
    if (this.props.selectedTab === nextProps.selectedTab) {
      return false;
    }
    return true;
  }

  render() {
    const { prevSelectedTab, index, selectedTab } = this.props;
    const animationClassName = prevSelectedTab > selectedTab ? animationLeft : animationRight;
    
    return (
      <TransitionGroup>
        {selectedTab === Number(index) &&
        <CSSTransition
          classNames={animationClassName}
          timeout={500}
          onEntered={() => {
            console.log("is out");
          }}
        >
          <div className={classnames(scss.tabContainer)} key={`tab-${this.props.index}`}>
            {this.props.children}
          </div>
        </CSSTransition>}
      </TransitionGroup>
    );
  }
}
```
It seems like the v2 core is written in the different way, once the transition is applied (enter -> enterActive) then the transition style is lock down. It won't be changed by any given condition until the transition is finished (exit -> exitActive). 

For the same example, if I click on **LEFT** first, the current tab will apply` animationLeft.exit -> animationLeft.exitActive ` and a new tab will apply `animationLeft.enter -> animationLeft.enterActive`. But when I click on the **Right** for the next step, the current tab will still apply `animationLeft.exit -> animationLeft.exitActive` instead of `animationRight.enter -> animationRight.enterActive`.

It doesn't work like the previous version, so I don't know if it is a bug or not? If there is any solution, please let me know, thank you.

**Comment by m-allanson** [comment]
@aj120426394 Have a look at the discussion in #182, I think this does what you want.
