### ISSUE TITLE
How to update/change timeout in rendered route?

### ISSUE THREAD

**Issue by Artimal** [reactjs/react-transition-group#247]
Hi,
I am ending my animated React Router basing on react-transition-group and GSAP. It works fine but there is a problem when user clicks quickly 2 times a browser back arrow - history back...

Then current route is showing without animation after timeout={2000} ms.

My solution for that is basing on component state that has boolean flag showing route animation ended or not called "**routeAnimating**". I want to call external function like when onEnter or onExit is called instead of timeout={2000} but if I use something like timeout={this.getTimeout.bind(this)} that function is not called. My goal is to have timeout={0} there when that function will check that actual (not when the route was rendered) this.state.routeAnimating is true.

**Comment by jquense** [comment]
If you need more nuanced control you can leave off the `timeout` entirely and use `addEndListener` which is essentially just a function that gets a callback you call when you want the transition to finish. you can put whatever you want in there, like a dynamic timeout

**Comment by Artimal** [comment]
1. Maybe is that possible to update transition={2000} of node in onExit?
2. If not - how can I update thaat timeout by addEndListener? I see documentation and that i can use done function callback but what to do in that callback to update timeout of exiting route from 2000 to 0?

**Comment by jquense** [comment]
you don't use the `timeout` prop at all and _just_ use `addEndListener` something like:

```js
addEventListener(node, done) {
  setTimeout(done, this.state.exitImmediately ? 0, 2000)
}
...

<Transition addEventlistener={this.addEventListener}>
```
