### ISSUE TITLE
CSSTransition Element is not unmounted after exit when using unmountOnExit

### ISSUE THREAD

**Issue by ajcf** [reactjs/react-transition-group#248]
**Do you want to request a *feature* or report a *bug*?**
**bug** - at least, I _think_ this should be supported from the docs.

**What is the current behavior?**
When a CSSTransition element is Exited, it remains in the DOM. This can cause unpredictable behavior for CSS :first-child or :last-child selectors, and poor performance if the list gets very large.

This may or may not be related to using a TransitionGroup to wrap my CSSTransition elements.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

https://codepen.io/ajcf/pen/RjoJbV?editors=0111

Notice how the "Current Children" count in the console keeps going up  - if you use the browser dev tools to inspect the items, those additional divs are also still in the dom.

**What is the expected behavior?**
CSSTransition items are removed from the DOM on exit when the unmountOnExit flag is set.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Here's what I'm using:
```
windows 10
chrome 62
react 15.6.1
react-dom 15.4.1
react-transition-group: 2.2.1
```

**Comment by jquense** [comment]
yes you need to include a `timeout` otherwise the component will transition out/in forever

https://codepen.io/jquense/pen/QOGVPx?editors=0111

**Comment by ajcf** [comment]
gotcha, thank you!
