### ISSUE TITLE
Transitions don't work after migration from v1 to v2

### ISSUE THREAD

**Issue by pronebird** [reactjs/react-transition-group#251]
**Do you want to request a *feature* or report a *bug*?**

bug

**What is the current behavior?**

Transitions do not work.

I migrated my code based on the migration guide, what I had:

```
// Cretes props to drive the right animation
//    { 
//      transitionName: name,
//      transitionEnterTimeout: duration,
//      transitionLeaveTimeout: duration,
//      transitionEnter: true,
//      transitionLeave: true
//    }
//
const transitionProps = getTransitionProps();

return (
<CSSTransitionGroup component="div" className="transition-container" { ...transitionProps }>
  <Switch key={ location.key } location={ location }>
    <LoginRoute exact path="/" component={ LoginPage } />
    <PublicRoute exact path="/settings" component={ SettingsPage } />
  </Switch>
</CSSTransitionGroup>
);
```

Now when I migrated this to v2 the code looks as following:

```
// Cretes props to drive the right animation
//  {
//    classNames: name,
//    timeout: {
//      enter: duration,
//      exit: duration
//    },
//    enter: true,
//    exit: true
//  }
//
const transitionProps = getTransitionProps();

return (
<TransitionGroup className="transition-container">
  <CSSTransition { ...transitionProps }>
    <Switch key={ location.key } location={ location }>
      <LoginRoute exact path="/" component={ LoginPage } />
      <PublicRoute exact path="/settings" component={ SettingsPage } />
    </Switch>
  </CSSTransition>
</TransitionGroup>
);
```

I don't get it, why it used to work and why it doesn't work now?

**What is the expected behavior?**

Transitions work.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Webkit

**Comment by astephenb** [comment]
I'm experiencing the same issue. I haven't been able to get the transition classes to be applied after following the migration guide. Any help would be appreciated!

**Comment by jquense** [comment]
Please search previous issues for usage with React-Router

**Comment by astephenb** [comment]
In my case, I was not using the transition group with react router. I ended up refactoring a bit more to use the `Transition` component directly and everything works fine now!
