### ISSUE TITLE
issues targeting childnodes 

### ISSUE THREAD

**Issue by axe-z** [reactjs/react-transition-group#253]
might be a feature ? 

not sure right now... 
i'm trying to Transition stuff in a TransitionGroup, but I'm having a hard time targeting childnodes . 

I'll use the second example (todoList) you have in the docs the explain... 

IM NOT USING CSS, 

so 

```jsx    
<TransitionGroup className='todo-list'>
          {this.state.items.map((item, i) => (
            <Fade key={item}>
              <div>
                {`${item} `}
                <button onClick={() => this.handleRemove(i)} className='remove'>
                  &times;
                </button>
              </div>
            </Fade>
          ))}
        </TransitionGroup>
```

gives both name and a button on the map , 

using Transition , i'm able the transition the in/out, but having a hard time targeting only let's say the remove button. 

```jsx
const Fade = ({ children, ...props }) => {
return   (
  <Transition
    {...props}
    timeout={1000}
    appear={true}
    addEndListener={(n , done ) => {
    const but = [...document.querySelectorAll('button.remove')]; //nodeList does not work 
  //  const but = n.childNodes[1].childNodes[1] , this works, but.... you know... 
       if (props.in) {
         inFx(n , done )
       } else {
         outFx(but , done )
       }
    }}
  >
    <div>  {children}  </div>
  </Transition>
)};
```

it should work with nodeList too, no ? or is there an easier way to acces  #HTMLCollection

Or what am I doing wrong here ? 
 also having issues here... hahaha

**Comment by jquense** [comment]
you can use whatever DOM api works to reach into the node argument. Ideally tho i'd put the Transition component around the node you want to animate instead of it's parent (where possible)

**Comment by axe-z** [comment]
What is definitely missing from the docs, since v1 is easier to comprehend with lifecycles (V2 onExit and others are not explained at all) , is an exemple using it with React-Router/router-dom . It's really hard to get when you've never played with either V1 or V2 prior. Any links ? State based animations cannot be the way for routing, at least i'm having a hard time imagining it . Sorry for my poor english skille ( an R-t-G... )

**Comment by jquense** [comment]
i don't use react-router so i have no real experience there. but there are a few issues in the repo here that cover it and (i think) have working examples

**Comment by axe-z** [comment]
so this repo as nothing to do with facebook really ? it's just been pointed out by the react docs ?

**Comment by jquense** [comment]
react-router isn't a facebook project either, but no this isn't related to FB. the reactjs github org is all community maintained projects. The code was originally part of React as an "addon" which was poorly maintained by FB. In light of that they decided to no longer maintain the addon and we took over. The project has evolved and grown from the original code base in the year since.

**Comment by axe-z** [comment]
ohhh my bad, always thought one of them was  (react-router).  Ok i'll cut you some slack then !! :) 
I've cracked animating the router (boy what a 2 day ride that was), all seems good, not sure if i'll hit bumps later, but with   "react": "^16.0.0", "react-router-dom": "^4.2.2" and GSAP, it seems ok, and simple enough. if only my english was better ...

**Comment by silvenon** [comment]
If you still think there's something we should change in our API, open a new issue. 😉
