### ISSUE TITLE
transitionName can't take multiple classes

### ISSUE THREAD

**Issue by JikkuJose** [reactjs/react-transition-group#255]
Reporting Bug.

**Current behaviour**
While specifying custom class for `transitionName` multiple classes can't be given.

**Demo**
[StackBlitz](https://stackblitz.com/edit/multiple-classes?file=examples/CSSAnimations.js)

**Version**
React 16.1.0 & corresponding librraries

```js
<ReactCSSTransitionGroup
  transitionName={{
    enter: "animated tada", // cannot take in multiple classes
    enterActive: "example-enter-active",
    leave: "example-leave",
    leaveActive: "example-leave-active",
    appear: "no-class",
    appearActive: "u",
  }}
  transitionEnterTimeout={500}
  transitionAppear={true}
  transitionAppearTimeout={500}
  transitionLeaveTimeout={300}
>
  {items}
</ReactCSSTransitionGroup>

```

**Comment by jquense** [comment]
yes v1 does not support this (and won't), v2 has added this feature tho, you can try the latest version
