### ISSUE TITLE
Transition Group: Re-calculate children with new props

### ISSUE THREAD

**Issue by mattkrick** [reactjs/react-transition-group#262]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**

Related to #238 I'm using Relay's QueryRenderer and I'm trying to animate between Loading & Ready state:
```
<TransitionGroup appear component={null} exit={false}>
    {error && <ErrorComponent/>}
    {renderProps &&
    <AnimatedFade key="1">
      <MyComponent viewer={renderProps.viewer}/>
    </AnimatedFade>
    }
    {!renderProps && !error &&
    <AnimatedFade key="2" unmountOnExit exit={false}>
      <LoadingView/>
    </AnimatedFade>
    }
  </TransitionGroup>
```

This works great for going from LoadingState to Ready state, but breaks going from Ready to Loading because the `renderProps` that power the Ready state get removed, but the TransitionGroup still thinks they're available. The TransitionGroup stores the children in its own state & doesn't re-evaluate whether it should still be showing each child. The result is after a variable change (without a dismount) instead of showing the LoadingView, it shows the MyComponent with a null renderProps, which breaks the app (renderProps.viewer is undefined). 

**What is the expected behavior?**
Abandon the animation when you don't have the necessary props. To do that, I'd suggest introducing a `requiredProp` on the TransitionGroup.
The TransitionGroup stores the `requiredProp` in its internal state alongside the children, and if the new `requiredProp` is falsey, then we know to ditch the children saved in state.
I can achieve this by using a HOC, but I want to first see if there's a better way & if not, get it in the main package.

```
<TransitionGroup requiredProp={renderProps}>
```
On first render, `renderProps` is null, and TransitionGroup#state.requiredProp == undefined. Set it to null. Standard mergeChildMappings.
On 2nd render, `renderProps` is an object, TransitionGroup#state.requiredProp == null. Set it to object. Standard mergeChildMappings.
On 3rd render, `renderProps` is null, TransitionGroup#state.requiredProp == object. Set it to null _and flush the children_.
On 4th render, `renderProps` is null, TransitionGroup#state.requiredProp == null. Standard mergeChildMappings.
On 5th render, `renderProps` is an object, TransitionGroup#state.requiredProp == null. Set it to object. Standard mergeChildMappings.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
All

**Comment by jquense** [comment]
Checkout the childFactory prop. It'll let you adjust props even on the exiting children

**Comment by mattkrick** [comment]
Just like #238, the `childFactory` can't be used to solve this issue. For anyone with the same problem, I made a component to watch the props coming in & sets a 1-way flag so if props ever go from truthy to falsy, it doesn't try to show the animation & bug out.

```
class RelayTransitionGroup extends Component {
  render() {
    const {error: errorEl, loading, ready, readyState} = this.props;
    const {error, props} = readyState;
    if (!props && this.renderProps) { // this is the magic part that react-transition-group doesn't do
      return Children.only(loading);
    } else if (!this.renderProps && props) {
      this.renderProps = true;
    }

    let child;
    let key;
    if (error) {
      key = 'Error';
      child = cloneElement(errorEl, {error});
    } else if (props) {
      key = 'Ready';
      child = cloneElement(ready, {viewer: props.viewer});
    } else {
      key = 'Loading';
      child = loading;
    }
    return (
      <TransitionGroup appear component={null}>
        <AnimatedFade key={key} exit={key !== 'Loading'} unmountOnExit={key === 'Loading'}>
          {child}
        </AnimatedFade>
      </TransitionGroup>
    );
  }
}
```
