### ISSUE TITLE
Animation with nested components

### ISSUE THREAD

**Issue by vkhotey** [reactjs/react-transition-group#264]
I have nested route component with CSSTransitionGroup

```
class AnimateRoute extends Component {
	render() {
		const { component, title, location, history } = this.props;

		return (
			<div style={{ marginTop: '0px' }}>
				<CSSTransitionGroup
					transitionName={getAnimateDirection(history, {
						PUSH: 'tab-left',
						POP: 'tab-right'
					})}
					transitionEnterTimeout={0}
					transitionLeaveTimeout={0}
				>
					<Route
						location={location}
						key={location.key}
						path={location.pathname}
						render={() => (
							<DefaultView
								location={location}
								title={title}
								key={location.key}
							>
								{component(location.pathname)}
							</DefaultView>
						)}
					/>
				</CSSTransitionGroup>
			</div>
		);
	}
}
```

For example products routes nested in  the store routes, when I change route it call transition. Store transition with inner components, and products transition by it self, result is that products call 2 times with componentDidMount and etc., how it fix ?

Thank you !

**Comment by jquense** [comment]
I'm not familiar with react-router v4 so don't have much advise, I'd suggest checking out the previous issues and solutions there on this topic thanks!
