### ISSUE TITLE
Code clean-up for Transition component

### ISSUE THREAD

**Issue by newyork-anthonyng** [reactjs/react-transition-group#265]
These are just 2 questions I had about the codebase for the `Transition` component.

* Are these static properties being used anywhere? (https://github.com/reactjs/react-transition-group/blob/master/src/Transition.js#L507-L511)

* Should [this](https://github.com/reactjs/react-transition-group/blob/master/src/Transition.js#L99-L101) read:
```js
  static childContextTypes = {
    transitionGroup: PropTypes.object,
  };
```

If these are valid changes, I can create a Pull Request for them.

<hr>

<details>

**Do you want to request a *feature* or report a *bug*?**
N/A

**What is the current behavior?**
N/A

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
N/A

**What is the expected behavior?**
N/A

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
N/A

<summary>Unused issue template</summary>
</details>

**Comment by billyjanitsch** [comment]
Looks like the static properties are [used in tests](https://github.com/reactjs/react-transition-group/blob/dcf0e5056e4fc0586d2e5bac5d5caaa0d4b877c6/test/Transition-test.js#L7).

**Comment by billyjanitsch** [comment]
Ah you're right, sorry!

**Comment by iamandrewluca** [comment]
@silvenon issue is obsolete. Can be closed.
