### ISSUE TITLE
Setting mountOnEnter stops enter animation from working

### ISSUE THREAD

**Issue by DouglasLivingstone** [reactjs/react-transition-group#266]
I would like to mount an element on the page, animate it in, then animate it out, and unmount it.

I noticed that the [example in the documentation](https://codesandbox.io/s/y26rj99yov?from-embed) has a 300ms delay before fading the component in, more obvious if the delay is bumped [up to 3000ms](https://codesandbox.io/s/q60ox7m74). There is a three second delay between the click and the start of the animation, and then another three seconds while it fades in, so the time from clicking the button to the animation finishing is double what would be expected.

The fix for this is to change the transition styles from this:

```
const transitionStyles = {
  entering: { opacity: 0 },
  entered: { opacity: 1 },
};
```

to this:

```
const transitionStyles = {
  exited: { opacity: 0 },
  exiting: { opacity: 0 },
  entering: { opacity: 1 },
  entered: { opacity: 1 },
};
```

Now in [the example](https://codesandbox.io/s/k56zz2y1ro) it fades in as soon as the user clicks the button, and fades out as soon as the user clicks the button.

However, I would like to `mountOnEnter` and `unmountOnExit`, but setting these properties causes the enter animation to no-longer fire, [example here](https://codesandbox.io/s/152p7qk43). The only difference between the top and bottom components is whether `mountOnEnter` and `unmountOnExit` are set or not.

I can partially work around this problem by setting `timeout` to 1, and animating after `entered` rather than between `entering` and `entered`, [see example](https://codesandbox.io/s/8y7r1n85r9), but this seems like a bug, as setting `mountOnEnter` affects whether the animation is shown or not.

**Comment by taion** [comment]
see https://github.com/reactjs/react-transition-group/issues/223
