### ISSUE TITLE
CSSTransition can't fade out

### ISSUE THREAD

**Issue by jdmswong** [reactjs/react-transition-group#267]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
when the `in` props of `CSSTransition` is set to false the element doesn't properly fade out

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
code from:
https://reactcommunity.org/react-transition-group/#CSSTransition

with line added to display the state:
https://codesandbox.io/s/nzjm741jp

**What is the expected behavior?**
when state.show is false the box should fade out, instead it blinks out and fades in again

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome Version 63.0.3239.84
react-transition-group v2.2.1

**Comment by jquense** [comment]
https://codesandbox.io/s/ymypv01939

and see https://github.com/reactjs/react-transition-group/issues/261 for more discussion

**Comment by jdmswong** [comment]
It fades in now but the pop in problem still persists, this is what I see:
https://imgur.com/a/eaJLQ

it fades in and out when it should, but doesn't stay transparent when faded out.  It also doesn't apply a class to the div to distinguish a faded out from faded in state.

**Comment by jdmswong** [comment]
the solution is that both the entering and entered states must have opacity set to 1.
