### ISSUE TITLE
How to fix React 15.5.3 PropTypes deprecated warning while using react-transition-group

### ISSUE THREAD

**Issue by dzhytomyrsky** [reactjs/react-transition-group#27]
Got  "Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead." while using React 15.5.3 "react-transition-group/CSSTransitionGroup" add-on.

It looks like this addon uses old PropTypes. Do somebody know how to avoid this Warning for this add-on? Or please fix it.

Added StackOverflow discussion:
http://stackoverflow.com/questions/43322476/how-to-fix-react-15-5-3-proptypes-deprecated-warning-while-using-react-transitio?noredirect=1#comment73709971_43322476

**Comment by taion** [comment]
track https://github.com/reactjs/react-transition-group/pull/28
