### ISSUE TITLE
Removing initial animation delay without timeout={0}

### ISSUE THREAD

**Issue by renshenhe** [reactjs/react-transition-group#271]
[Demo
](https://codepen.io/Renshenhe/pen/wpeemB) (boxes are clickable)

I can't seem to find a way around setting `timeout={0}` if I want the animation to start immediately but doing so I lose the proper timing(500ms) to use `onEntered` to change the visibility of the grey box. I can add another 500ms timeout function to the `onEntered` callback to toggle the grey boxes visibility using `timeout={0}` but I thought there may be better approaches to this than a timeout within a timeout.

**Comment by jquense** [comment]
hi there, sorry I'm not sure what the issue or concern is here and the demo seems to work without knowing what i'm supposed to be looking for

**Comment by renshenhe** [comment]
@jquense Sorry about not being clear.  I want to avoid having to use `timeout={500}` which the demo is currently set at.  This causes the animation to begin 500ms after an item is clicked instead of immediately. If I set `timeout={0}` I get the animation I want, which is immediately, but I lose the use of `onEntered` because it is called immediately rather than after 500ms which is what I want.

I'll try and rework the demo to see if it can provide better clarity in the meantime.

**Comment by jquense** [comment]
I think you are starting the animation to late then, the timeout is for when the animation is finished, not starts. so start the animation when state is `entering` and finish by `entered`

**Comment by renshenhe** [comment]
To further clarify my end goal it's to create shared element transition without actually having the element do any transitioning.  Instead a new layer is created and a clone of the targeted element is created over targeted element. The targeted element is hidden and the clone transitions towards the end position and after the animation is done(when the clone reaches end position) it is removed and the end element is then set to appear to create the illusion the targeted element transitioned to become the end element.

@jquense Regardless of whether the animation is set to `entering` or `entered` there is still a delay when the animation begins. The `origin` and `to` props in the demo will have to be swapped when setting `translate3d` to `entering` to get the appropriate transition. Logging the transitions it oddly always starts the animation when `entered` is called despite only `entering` containing the transform property. There's no transition delay styling anywhere in the code as far as I am aware to cause this.

I've edited the codepen changing the animation to `entering`, breaks exiting animation, but there doesn't seem to be any changes in animation startup.

**Comment by jquense** [comment]
do you think you could simplify the example to just the single animation that isn't working like you'd expect? It'll be easier to talk about without so much other code thanks!

**Comment by renshenhe** [comment]
My first and several guesses were I did something wrong somewhere but not wise enough to see :)

It's difficult to simplify the example considering it's a skimmed version of what I was experimenting with but for lack of better code example I'm mainly focused on the start time of the **red box**.  The one without the 500ms delay is what I am hoping to achieve but it's using `timeout={0}` to achieve that which means I lose access to an appropriately timed `onEntered` callback.  Only the `Hero` component should be of concern as it's the component in question the others are there to calculate the start position and end position.

If it is as you mentioned caused by javascript and css then it's not a big deal as I am currently experimenting animating with react and this was just one of the walls I hit.

**Comment by jquense** [comment]
can you at least remove the other example, and only have the "broken" one?

**Comment by renshenhe** [comment]
@jquense done.

**Comment by jquense** [comment]
sorry i've poked around and can't figure it out. It's look very much tho like the animation is not triggering when it needs at `entering`, and instead is happening incorrectly after the component things the transition is ended. My guess is that it's related to css not something in the component

**Comment by yaodingyd** [comment]
@renshenhe  Your FLIP animation is done in the wrong way.  See [demo](https://codepen.io/anon/pen/xpzOmm). 

One catch is to trigger reflow onEnter, otherwise there is no transition animation.

Also your test case is way too complicated for bug reporting any featured library. Try to write a reduced test case then you would realize your issue has nothing to do with this library.

**Comment by renshenhe** [comment]
@yaodingyd Thanks for the insight and fix I'll try to simplify the demos in the future. Would have bothered me for ages.
