### ISSUE TITLE
Are V1 and V2 Backward Compatible?

### ISSUE THREAD

**Issue by trevorwhealy** [reactjs/react-transition-group#272]
**Do you want to request a *feature* or report a *bug*?**
Neither, just think something should be clarified in the docs.

**What is the current behavior?**
I know that the "API in v2 is different" than in v1.

**What is the expected behavior?**
I need to know if I upgrade to v2 that my v1 code will be backward compatible.

**Comment by jquense** [comment]
no they aren't, we follow sematic versioning so a major version bump indicates there are breaking changes between v1 and v2 there is a migration guide here: https://github.com/reactjs/react-transition-group/blob/master/Migration.md
