### ISSUE TITLE
Make `.exit-active` styles remain while `in` is false

### ISSUE THREAD

**Issue by james-prado** [reactjs/react-transition-group#274]
**Do you want to request a *feature* or report a *bug*?**

No

**What is the current behavior?**

[current](https://codesandbox.io/s/n3792j2yw4) 

using the `in` property on `<CSSTransition>` toggles transitions, but when not actively transitioning, defaults to normal styles. In the case of the example, that means it defaults to an opacity of 1.

**What is the expected behavior?**

[expected](https://codesandbox.io/s/wk75r9yryw)

Ideally, `.exit-active` class should remain while `in` is `false`, so the exit styles (`opacity: 0;`) remain while the button is supposed to be hidden.

I think it would be a much better solution than what I'm required to do currently to get this behaviour

**Comment by jquense** [comment]
We just recently added `done` classes to cover this case. Should be in the next release

**Comment by james-prado** [comment]
@jquense Awesome, looking forward to the next release then!
