### ISSUE TITLE
cant npm i

### ISSUE THREAD

**Issue by m-salamon** [reactjs/react-transition-group#276]
**Do you want to request a *feature* or report a *bug*?**
*feature*
when installing the node packages you must do ```npm install``` and ```npm i``` wont work, (most packages these days work with ```npm i```)

**What is the current behavior?**
```npm install```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

**What is the expected behavior?**
```npm i``` or ```npm install```
**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

**Comment by jquense** [comment]
`npm i` is an alias for `npm install`, they are the same command, it's not possible that one works but not the other. In any case that would be a bug with npm not this library. Thanks!
