### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by Echelpoel** [reactjs/react-transition-group#277]
Getting "this.updater.enqueueCallback is not a function" error. Went through issues to find out it was a bug related due to lack of React 16 support, which was fixed.  So it's kinda confusing if React 16 is supported or not. Why was this reverted?

![screen shot 2018-01-19 at 18 20 34](https://user-images.githubusercontent.com/7335810/35163032-a1f883ba-fd45-11e7-8830-d94de0772251.png)

**Comment by jquense** [comment]
`"react": ">=15.0.0"` measn version 15 and up, so yes it supports react 16

**Comment by jcicero518** [comment]
So should we use v1 or v2 for React 16.x?
