### ISSUE TITLE
"Main documentation" page crashes on Chrome

### ISSUE THREAD

**Issue by mockdeep** [reactjs/react-transition-group#278]
**Do you want to request a *feature* or report a *bug*?**

Report a bug.

**What is the current behavior?**

When I visit the documentation page at https://reactcommunity.org/react-transition-group/ I see the documentation initially, but I quickly get an "Aw, snap!" error from Chrome. It appears to be caused by codesandbox.io, as when I disabled the JavaScript coming from there, the page does not crash. I tried it in an incognito tab with no plugins enabled, and still saw the issue.

![snap](https://user-images.githubusercontent.com/80543/35206079-db22ac74-feee-11e7-9bc4-dccfc5acbcf4.png)

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

Visit https://reactcommunity.org/react-transition-group/ in Chrome.

**What is the expected behavior?**

I can view the documentation.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

Chrome: Version 63.0.3239.132 (Official Build) (64-bit)
OS: Linux Mint 18.1 Cinnamon 64-bit (Kernel version: 4.4.0-71-generic)

I haven't tried this on other versions of Chrome, so not sure if it worked otherwise. I have not seen this issue on any other websites. It works fine for me on Firefox.

**Comment by jquense** [comment]
hmm it may be a linux specific bug with codesandbox/chrome i'm not seeing any crash on mac with the same version of Chrome. Might be worth mentioning on the codesandbox repo, in case they have any insight

**Comment by tswaters** [comment]
I've hit this a few times chrome on ubuntu.

**Comment by rgtk** [comment]
Same here for Chromium 63.0.3239.84.

Problem is caused by Codesandbox. Page always crashes on requesting these URLs from service worker:

https://codesandbox.io/monaco-typings-ata.1383fafa041b0c5876ae.worker.js
https://codesandbox.io/monaco-syntax-highlighter.c900a81d5350f8f4244b.worker.js
https://codesandbox.io/monaco-typings-ata.1383fafa041b0c5876ae.worker.js

**Comment by taion** [comment]
Do you have any further details on what's causing the crash? Or should we follow up on https://github.com/CompuIves/codesandbox-client/issues/471.

**Comment by rgtk** [comment]
I will contribute to issue you've mentioned since it is a problem in Codesandbox.

**Comment by AlesMenzel** [comment]
Can confirm. Documentation not found. 

![](https://image.prntscr.com/image/bDGSyO24TwCXDLsta94zRw.png)

**Comment by taion** [comment]
That's a different issue. @mjackson deleted the repo that hosted reactcommunity.org. I'm reaching out to GH support now to restore it.

**Comment by mjackson** [comment]
Oops, sorry. I didn't realize that domain was still hosting anything! I let the domain expire since I didn't think anyone was using it. Can we put up this site somewhere else?

**Comment by taion** [comment]
Yup. We'll use https://reactjs.github.io/react-transition-group/ for the time being. I'll fix up the CNAME tomorrow.

**Comment by mjackson** [comment]
@taion What domain name are you going to use?

**Comment by taion** [comment]
I meant just removing the CNAME there for now – just want to get the favicon because it looked nice.

Since nothing else is on there, maybe we'll move this to react-transition-group.js.org or something. @jquense's call.

**Comment by mjackson** [comment]
Well, I renewed reactcommunity.org and put the original repo back. Sorry again for the confusion. I think it'd actually be kinda nice to have all the @reactjs sites hosted at reactjs.github.io, but that's off-topic for this issue.

**Comment by taion** [comment]
Sure, that sounds good too. I'm fine either way. I just wanted to un-break things.

**Comment by taion** [comment]
Using reactjs.github.io, I mean. Thanks for renewing the domain, though!

**Comment by silvenon** [comment]
Can someone confirm if this is still happening?

**Comment by rgtk** [comment]
Works for Chromium 66.0.3359.181

**Comment by silvenon** [comment]
Thanks, I'll assume that this works now. Feel free to open a new issue if there are still problems!
