### ISSUE TITLE
Should be separate css class added when state transitions to 'entered'

### ISSUE THREAD

**Issue by rmacqueen** [reactjs/react-transition-group#283]
For `CSSTransition`s, right now the library adds the class `example-enter` and then, in the next tick, `example-enter-active`. However it doesn't then add any additional class when the transition completes. What this means is that the element being transitioned has the same CSS in the full `entered` state as it does in the full `exited` state, which doesn't really make sense. For example, if fading in a component, I want the full exited state to have opacity 0, and the full entered state to have opacity 1. There is no way to do this using the `CSSTransition` component (though you can achieve it using the lower-level `Transition` component).
Ideally it would add something like `example-entered` once in the entered state.

**Comment by taion** [comment]
This was resolved in https://github.com/reactjs/react-transition-group/pull/269.
