### ISSUE TITLE
React 16 regression

### ISSUE THREAD

**Issue by AlexanderEkdahl** [reactjs/react-transition-group#285]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Initial state is not rendered which creates odd behaviour with rendering

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

The following pen runs the same demo as the one on the official website but with React 15 instead of React 16 which works fine:
https://codesandbox.io/s/z2r5pwv893

However, when testing with the latest version of React it appears as if rendering is delayed until after the timeout instead of immediately:

https://codesandbox.io/s/y26rj99yov

**What is the expected behavior?**
Render the initial state before rendering `entering`.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Tested in Google Chrome and Safari on macOS

---

I believe this is the cause of #156 and #284.

I am not familiar with the inner workings of this library but I believe a small timeout(i.e. `setImmediate`) is necessary in order to ensure that the initial state is flushed to the DOM before rendering the `entering`-state.

**Comment by yaodingyd** [comment]
Your test case is not valid.

In your React 16 case:
```javascript
const transitionStyles = {
  entering: { opacity: 0 },
  entered: { opacity: 1 },
};
```

In your React 15 case:
```javascript
const transitionStyles = {
  entering: { opacity: 1 },
  entered: { opacity: 1 },
};
```

Make your style the same and you'll see the animation is the same.

**Comment by silvenon** [comment]
As I recall, our official example indeed had the mistake that @yaodingyd explained. Recently we revamped our docs with new examples and explained how timing works in #313, which will be on the site once we publish the next release. I'll gladly provide further explanations if this is not clear. 🙂

**Comment by AlexanderEkdahl** [comment]
All sounds good. I'm sorry for submitting an incorrect bug report.
