### ISSUE TITLE
CSSTransitionGroup child ref function called with CSSTransitionGroupChild

### ISSUE THREAD

**Issue by jliuhtonen** [reactjs/react-transition-group#29]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

`ref` function given to a `CSSTransitionGroup` child is called with both the child element refence and the CSSTransitionGroupChild component instance

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**

See console in https://jsfiddle.net/10sjj3so/6/

**What is the expected behavior?**

`ref` should only be called for the child given to `CSSTransitionGroup`, not the synthetic `CSSTransitionGroupChild` instance that is an implementation detail of `CSSTransitionGroup`

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

All browsers. Worked in React addons version.

**Comment by rayhatfield** [comment]
This is causing a problem in my project too.

**Comment by karl** [comment]
We've just spotted this as well.

String refs seem to work correctly (as in they reference the child element and not a `CSSTransitionGroupChild`). Although they work, using a string ref causes a warning saying they are not supported and will be ignored.

I'm not sure what the correct approach is at the moment, as callback refs seem to be broken, but string refs are supposedly not supported! Any advice would be great.

**Comment by karl** [comment]
We've worked around this for the moment by moving back to `react-addons-css-transition-group`version `15.5.2` which works correctly with string refs without a warning.
