### ISSUE TITLE
The TransitionGroup example does not work.

### ISSUE THREAD

**Issue by alecmce** [reactjs/react-transition-group#290]
https://github.com/reactjs/react-transition-group/blob/5007303e729a74be66a21c3e2205e4916821524b/src/TransitionGroup.js#L73

The embedded example does not work:

https://codesandbox.io/embed/43v5wj62q9?autoresize=1&fontsize=12&hidenavigation=1&moduleview=1

**Comment by taion** [comment]
Seems to work for me. What are you seeing?

**Comment by alecmce** [comment]
Oy. I guess codesandbox just crapped out for me. Sorry, please excuse the spam.
