### ISSUE TITLE
Can't get first example to work on ReactJS.NET

### ISSUE THREAD

**Issue by SoLegendary** [reactjs/react-transition-group#292]
Trying to get the first example of a button fading in and out the coloured div brings up a few issues:

```
const duration = 300;

const defaultStyle = {
  transition: `opacity ${duration}ms ease-in-out`,
  opacity: 0,
  padding: 20,
  display: 'inline-block',
  backgroundColor: '#8787d8'
}

const transitionStyles = {
  entering: { opacity: 0 },
  entered: { opacity: 1 },
};

const Fade = ({ in: inProp }) => (
  <Transition in={inProp} timeout={duration}>
    {(state) => (
      <div style={{
        ...defaultStyle,
        ...transitionStyles[state]
      }}>
        I'm A fade Transition!
      </div>
    )}
  </Transition>
);

class Example extends React.Component {
  state = { show: false }

  handleToggle() {
    this.setState(({ show }) => ({
      show: !show
    }))
  }
  
  render() {
    const { show } = this.state
    return (
      <div>
        <button onClick={() => this.handleToggle()}>
          Click to toggle
        </button>
        <div>
          <Fade in={!!show} />
        </div>
      </div>
    )
  }
}
```

'inProp' shows an error **"binding element 'inProp' implicity has an 'any' type."** This is the same for 'state'.

'transitionStyles[state] has error **"element implicitly has an 'any' type because { entering: { opacity: number }; entered: { opacity: number; }; }' has no index signature."**

'show' has error **"Type {} has no property 'show' and no string index signature"**

**Comment by jquense** [comment]
Hey there, we don't provide or maintain any typescript type defs. If your using them from DT I would open an issue there if they are wrong. Otherwise, you might have typescript misconfigured or this library just doesn't type well with it. I don't really know I don't use TS
