### ISSUE TITLE
Simplified CSSTransition API

### ISSUE THREAD

**Issue by LandonSchropp** [reactjs/react-transition-group#295]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

According to the documentation for `Transition`, there are four states a transition can be in:

* `entering`
* `entered`
* `exiting`
* `exited`

This makes perfect sense to me. It's clear from the names of these states what they mean and how they work.

However, the `CSSTransition` `classNames` property contains a different set of available classes for `classNames`. maybe it's just me, but I find the available classes a bit confusing. It's not clear to me how they map to the states above.

According to the documentation, I have the option of using these classes:

* `appear`
* `appearActive`
* `enter`
* `enterActive`
* `exit`
* `exitActive`

A few questions spring to mind with these:

* What does "active" mean? Why would I use that?
* Why don't the class names match the states in `Transition`?
* From the documentation, I gather that `appear` is used to signify the first transition. I'm personally struggling to think of a situation where I would need that. Why would I use that?
* How do I add classes for `entered` and `exited`? Am I missing something?

**What is the expected behavior?**

If I'm missing something obvious, please feel free to correct me. However, it seems like the API would be much more intuitive if `classNames` worked like this:

```
classNames={ {
  entering: "modal--opening",
  entered: "modal--open",
  exiting: "modal--closing",
  exited: "modal-exited"
} }
```

If I am missing something obvious, it would be great if the documentation could be updated with more details. A few more examples might help as well? It might also help if the lifecycle of `CSSTranstion` were explicitly laid out.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

I'm using React 16.2.0 and React Transition Group 2.2.1

**Comment by LandonSchropp** [comment]
Thanks for taking the time to read through this, and sorry if it's off-base. I'm just a little confused on how to use this library, and I wonder if others might be having similar troubles.

**Comment by LandonSchropp** [comment]
I took a stab at a simplified implementation of how I *expected* this to work having never used `CSSTransition` before:

```
import React from 'react';
import { Transition } from 'react-transition-group';

function addClass(node, classNames, state) {
  node.classList.remove(...Object.values(classNames));
  node.classList.add(classNames[state]);
}

function reflowAndAddClass(node, classNames, state) {
  node && node.scrollTop; // eslint-disable-line no-unused-expressions
  addClass(node, classNames, state);
}

export default function CSSTransition({ classNames, children, ...props }) {

  return <Transition
    { ...props }
    onEntering={ node => reflowAndAddClass(node, classNames, 'entering') }
    onEntered={ node => addClass(node, classNames, 'entered') }
    onExiting={ node => reflowAndAddClass(node, classNames, 'exiting') }
    onExited={ node => addClass(node, classNames, 'exited') }
  >
    { children }
  </Transition>;
}
```

This obviously isn't a completed implementation, but IMHO it's a little less confusing to use.

**Comment by jquense** [comment]
There are two big reasons for why the CSS api is the way it is. The first is that it predates the's the Transition api, and there are a **ton** of folks who have built transitions under this model. it's also fairly typical for this sort of thing: [angular](https://docs.angularjs.org/api/ngAnimate#css-based-animations) and {vue](https://vuejs.org/v2/guide/transitions.html). The other big reason is that this style is a bit more amenable to how css-transitions work, you define what animates, and then set the ending value, and wait for it to happen

> What does "active" mean? Why would I use that?

`active` means start the transition. e.g the class that defines the end states. like 

```
.enter {opacity: 0 }
.enter-active { opacity: 1 }
```

> Why don't the class names match the states in Transition?

Mostly legacy, but also because they are a bit more descriptive of how the classes affect the element.

> From the documentation, I gather that appear is used to signify the first transition. I'm personally struggling to think of a situation where I would need that. Why would I use that?

In case you need the mounting of the component to also transition. e.g. you want the initial list items to transition in as well as subsequent additions

> How do I add classes for entered and exited? Am I missing something?

there are also `enter-done` and `exit-done` classes but that hasn't been released yet, again mostly due to legacy apis.

> IMHO, this is a little less confusing than the current version of CSSTransition.

I think so too, in fact i use a version quite similar to this :P

**Comment by LandonSchropp** [comment]
Thanks for the reply, and sorry for taking so long to respond. This issue completely slipped off my radar.

> The first is that it predates the's the Transition api, and there are a ton of folks who have built transitions under this model.

That makes sense, but it is a bit unfortunate. I don't know if others struggled as much as I did in trying to get this to work, but it seems like it might discourage new years. In my opinion, a simpler interface would be worth the trouble, but I'm obviously only thinking about myself there, and you have a whole lot of other people to consider. 😃 

Thanks for taking the time to answer my questions! Your explanations cleared things up for me.
