### ISSUE TITLE
Bug: "Enter" transition doesn't always work when using mountOnEnter & unmountOnExit

### ISSUE THREAD

**Issue by afraser** [reactjs/react-transition-group#299]
**Do you want to request a *feature* or report a *bug*?**
Bug.

**What is the current behavior?**
Animation from `entering` to `entered` state does not always work when using `mountOnEnter` and `unmountOnExit`. Instead the content is just shown immediately.

**steps to reproduce**
The current behavior is best observed in Firefox, but also seems to occur in Chrome (though less frequently).
See the following codepen: https://codesandbox.io/s/r381x2pqm
Click the toggle button repeatedly and note that the content is not always animated in.

Notes: 
* Removing the `transform` animation makes no difference, I just found it's easier to notice the bug with the transform animation so I left it in.
* Try it with an enter timeout of anything over 20ms and note that the enter animation now works every time. It seems there's a race condition during the mounting of the component.

**What is the expected behavior?**
The enter animation should always play.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome 63.0.3239.132 (Official Build) (64-bit)
Firefox 58.0.2 (64-bit)
...not sure about other browsers/versions

**Comment by jquense** [comment]
You are running into an idiocracy doing CSS transitions from javascript, you need to reflow the browser at the right moment. https://codesandbox.io/s/k597pxr5

See past issues about this, or use CSSTransition to avoid it.

**Comment by afraser** [comment]
Ah, unfortunately this work is for a component library and if I remember correctly we can't use CSSTransition because it wasn't working with React 0.14 apps. :\

**Comment by jquense** [comment]
you don't have to switch, the sandbox i posted handles the case, but you do need to handle it.

**Comment by afraser** [comment]
Yeah, it took me a second to see the `onEnter={node => node.offsetHeight}`, but I'm no longer seeing the translate animation on enter.

**Comment by afraser** [comment]
Got it:

```js
onEntering={node => node.offsetHeight}
```

Thanks very much for your help @jquense

**Comment by brewern** [comment]
I'm experiencing the same problem. Sliding a panel in from the right, but it loads into place immediately onEnter rather than using the slide animation. The onExit animation works as expected.

I'm using anime.js to animate. https://codesandbox.io/s/v8k22j3p63
