### ISSUE TITLE
Losing scope using Transition in render

### ISSUE THREAD

**Issue by individual11** [reactjs/react-transition-group#300]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
I'm losing access to the root _this_ of the component when using the transition within the render function.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
```JavaScript
render(){
   return (
      <Transition in={this.props.in} timeout={duration}>
      {((state) => (
  
      <div id="quote" style={{
                           ...defaultStyle,
                           ...animationStyle[state]
                        }} 
                   className="container d-flex flex-column fill">
         <FormElement 
            ref="formElements"
            />
            <div className="d-flex flex-row fill justify-content-baseline pl-4 w-100">
                  <button className="p-2 btn btn-lg btn-primary mt-auto mb-5" type="button" onClick={(e) => this.handleSubmit(e)}>Next</button>
            </div>
       
      </div>
      )).bind(this)}
      </Transition>
    )
}
```
then in the handleSubmit
```JavaScript
handleSubmit(e){
   console.log(this.refs)
}
```
**What is the expected behavior?**
That I would see the ref _formElements_ instead of an empty Object. I can put a ref on the Transition, then reach in through that, but that's *super* annoying. I've tried binding a dozen ways, hoping someone has a solution.
**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Cross Browser/Mac Sierra latest build. New to using this lib, so not sure if it worked in previous builds.

**Comment by jquense** [comment]
The problem there is that you are using a string `ref` for `formElements`, not that `this` is getting lost. The ref is empty in `handleSubmit` because it's attached to the Transition component (the component that actually renders it). Your witnessing the "problem" with string refs and why the function callback signture exists :), use `ref={ref => this.formElements = r}` instead and it'll work

**Comment by individual11** [comment]
That makes total sense. If anyone runs into the same issue, @jquense code needs to be modified to `ref={ref => this.formElements = ref}` to work.
