### ISSUE TITLE
TransitionGroup as part of return statement will not reconcile as expected

### ISSUE THREAD

**Issue by DennisBaekgaard** [reactjs/react-transition-group#301]
**Do you want to request a *feature* or report a *bug*?**
Maybe a bug, maybe just me who is missing some point.

A create react app repo with the code in question can be found [here](https://github.com/DennisBaekgaard/react-transitiongroup-render-error). Just run yarn install yarn run, then it should work. 

I will try my best to explain this. It might also be an actual React issue.

**What is the current behavior?**
As far as I can read from the code, <TransitionGroup> is a fairly straight forward extension of <Component> and will return a div as default. Further, if I got my "list-items in react for dummies" then you supply explicit keys to lists, but not for standard components. With that in mind;

If I have this structure:
_map from lodash //Look at the 
gl = {key: [{},...] } 

The reason for lodash map is a particular solution to a problem i another project. Basically I group a list of items by date a date property nested in the items, and return it as:

    gl = {
        "2018-03-12": [items],
    }

    render(){
        return (
            <TransitionGroup className="container">
              {_map(gl, (people, group) => {
                return (
                  <React.Fragment key={group}>
                    <div key={group}><strong>Group: {group}</strong></div>
                    {people.map(person => <Animation key={person.id}><Item data={person} /></Animation>)}
                  </React.Fragment>
                );
              })}
            </TransitionGroup>
        )
    }

the result will basically be that any rendered data in the _map() will stay in the DOM, even if new props are passed down to the component. I have observed two different patterns. The first one, I can only replicate in a real project with Apollo and some actual server behaviour, the other i have replicated here. 
In this example, all items will stay in the DOM in the order you click them.

So if you click A, then C, then the DOM will contain A and C.

The other case with apollo is slightly more interesting. If you click A then the DOM contains A. If you click C, then the DOM contains C. If you then click back to A, the DOM will contain A+C. If you click B, then the DOM only contains B, and so on. 

It was quite a long road of debugging with this one, so some of the things I noticed on my way is that props are correctly handled to the component. So if you have an array, data with 10 elements, only 10 elements will be in that variable in that component. If you then click say, B and it contains 25 items, and then back to A, then the component will still, correctly, only have an array with 10 items, and map will only iterate over those 10 items. But it will still incorrectly render the contents of B. 

The image below show-cases the issue in a more visual way. The first image is the initial state, the second it when you have clicked "Group B" to show data.
https://i.imgur.com/pASerDD.png

https://i.imgur.com/Ineu8DV.png

If I have the same construction but instead wrapped in some UL / LI tags, then it works correctly. If I uncomment the key on the TransitionGroup, it works correctly. If I use a normal div (which TransitionGroup essentially is) then it works correctly. If I move the TransitionGroup out of the list component: 

    App.js:
    <TransitionGroup>
        <List data={data} />
    </TransitionGroup>

as opposed to:

    List.js:
    return(
        <TransitionGroup>
            {this.data.map(p => <Item data={p} />
        </TransitionGroup>
    );

 What is so special for React in terms of the <TransitionGroup> component, that makes this behaviour happen? 

**What is the expected behavior?**
That it renders each array passed down as props individually.

**Comment by jquense** [comment]
hey there,` TransitionGroup` expects a list of react elements for it's children, it needs them because it introspects its own `props.children` to calculate when items leave or enter and adds props to them. Your example here with `Fragment` wound't work because TransitionGroup sees fragments as elements, not as a transparent nested array, e.g. `React.Children.Count(<><div/><span/></>) // 1 not 2`

The second example with `List` doesn't work because the children of TransitionGroup is `List`, not the what List renders. You can change that though by telling the TransitionGroup to _be_ a List vs render one, like: `<TransitionGroup component={List}>`

Hope that helps!
