### ISSUE TITLE
Any way to reverse an animation?

### ISSUE THREAD

**Issue by corysimmons** [reactjs/react-transition-group#305]
https://codesandbox.io/s/3k03v9j7k6

Just forked docs first example, increased duration, and then clicked toggle button over and over. It seems to want to finish the animation, but I'd expect it to reverse each time the button is clicked.

Did the same thing with `CSSTransition` same result: https://codesandbox.io/s/7jv5lp2006

Is this functionality available somehow I'm overlooking?

**Comment by corysimmons** [comment]
Never mind, apparently adding `transition: ...` to `.greeting` fixes it.

**Comment by baughmann** [comment]
Well, *bump* I guess... the link is dead and I have no idea what this gentleman is talking about with 
> `transition: ...` to `.greeting`
