### ISSUE TITLE
using the Official website example  error

### ISSUE THREAD

**Issue by ldwstyle** [reactjs/react-transition-group#308]
**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
using the Official website example  error
Error message：Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
Check the render method of `TodoList`.

but When I modify the render：<div>123</div>,then it work
then I use the demo where https://reactjs.org/docs/animation.html ,it work ,
my react version is @15.6.2,my react-dom version is @16.2.0
**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**

**What is the expected behavior?**

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

**Comment by silvenon** [comment]
Which part of the `TodoList` causes an error? We updated our examples, please let me know what you have trouble understanding.

**Comment by silvenon** [comment]
For the time being I'm closing this. I will gladly reopen once we receive more information. 👍
