### ISSUE TITLE
Remove usages of unsafe lifecycle methods

### ISSUE THREAD

**Issue by Hypnosphi** [reactjs/react-transition-group#311]
React team recently published a blogpost: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

TL;DR: `cWM`, `cWRP`, and `cWU` methods are considered unsafe for future async rendering and will be deprecated soon. The recommended way for open source maintainers to deal with it is to use [`react-lifecycles-compat`](https://github.com/reactjs/react-lifecycles-compat) package and migrate to new `static getDerivedStateToProps` method

**Comment by m-allanson** [comment]
See #317
