### ISSUE TITLE
Unused dependencies on warning and chain-function

### ISSUE THREAD

**Issue by billyjanitsch** [reactjs/react-transition-group#314]
react-transition-group has unused dependencies on [`warning`](https://github.com/reactjs/react-transition-group/blob/c3279b5ca999abf5a56d5c0ffd025efe59753954/package.json#L59) and [`chain-function`](https://github.com/reactjs/react-transition-group/blob/c3279b5ca999abf5a56d5c0ffd025efe59753954/package.json#L55).

I would PR their removal but I haven't managed to get Yarn working in my environment so I can't update the Yarn lockfile.

**Comment by silvenon** [comment]
Thanks for pointing these out!
