### ISSUE TITLE
unmountOnExit does not allow transition from exiting to exited (?)

### ISSUE THREAD

**Issue by giggioz** [reactjs/react-transition-group#323]
**Do you want to request a *feature* or report a *bug*?**
*Bug* (even if i think it's something i did not understand about transitions...)

**What is the current behavior?**
Transiton does not work with unmountOnExit

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem **

https://codesandbox.io/s/l5nzrpvlym

**What is the expected behavior?**
The text should fade out before unmounting, if you comment unmountOnExit it works (but i does not unmount the component, of course).

**Comment by jquense** [comment]
your Transition is trying to start the fade out animation after it's already been run. CSS transitions work by setting the end value at the beginning and letting the browser animate to it. you are setting the end state `opactity: .5` on `exited` which is after the animation should have already finished.
