### ISSUE TITLE
Conditional rendering inside VelocityTransitionGroup error

### ISSUE THREAD

**Issue by tiffanytangt** [reactjs/react-transition-group#324]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
As of 1.4.0, when conditionally rendering children in a VelocityTransitionGroup, the presence of false values results in a javascript error:
> Uncaught TypeError: Cannot read property 'key' of null

```
<VelocityTransitionGroup>
   {visible && <Child/>}
</VelocityTransitionGroup>
```
https://codesandbox.io/s/myjy9v19q8

**What is the expected behavior?**
Conditionally rendering children works inside VelocityTransitionGroup

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Affects v1.4.0 with both React 15 and 16.

From what I can see, this change in velocity-transition-group.js in 1.4.0 introduced this:
```
 -    // Without our custom childFactory, we just get a default TransitionGroup that doesn't do
 -    // anything special at all.
 -    if (
 -      !this.constructor.disabledForTest &&
 -      !Velocity.velocityReactServerShim
 -    ) {
 -      transitionGroupProps.childFactory = this._wrapChild;
 -    }
 -
      return React.createElement(
        TransitionGroup,
        transitionGroupProps,
 -      this.props.children
 +      !this.constructor.disabledForTest && !Velocity.velocityReactServerShim
 +        ? React.Children.map(this.props.children, this._wrapChild)
 +        : this.props.children
      );
    }
```

**Comment by taion** [comment]
This isn't the library for `<VelocityTransitionGroup>`.

**Comment by tiffanytangt** [comment]
sorry this was a mistake
