### ISSUE TITLE
Attempting to update a tutorial example for latest versions

### ISSUE THREAD

**Issue by justrealmilk** [reactjs/react-transition-group#325]
**Do you want to request a *feature* or report a *bug*?**
False

**What is the current behavior?**
Unknown

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/m4mb9Lg3/4/).**
Not a bug but here's the demo https://codesandbox.io/s/73ymn2k911

**What is the expected behavior?**
Components render

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
I'm on Windows 10 and the original project used Yarn (I'm on NPM) and older versions of dependencies 

Clicking a nav link on codesandbox.io reveals errors in the cinsole that Chrome itself does not including
`Warning: Unknown event handler property `onExited`. It will be ignored.`
`Warning: Received `true` for a non-boolean attribute `in`.`

P.S. I'm a newb

**Comment by justrealmilk** [comment]
Based on my observations through dev tools, it initially knows where to place components but forgets to set opacity: 1 or remove the old components

**Comment by justrealmilk** [comment]
I've been reviewing the react-transition-group v1 to v2 migration guide and I think the problem is actually my transition components which I have no idea how to fix.

**Comment by jquense** [comment]
do you have a more paired down example? I'm not sure what to be looking at or where to suggest things. It seems tho like you are using the v1 api, but i also don't see the dependency in the codesandbox...

**Comment by justrealmilk** [comment]
Trying to take an example that used the v1 and update it to use v2

**Comment by jquense** [comment]
try reading: https://github.com/reactjs/react-transition-group/blob/master/Migration.md

**Comment by jquense** [comment]
ok...i'm not sure what you want us to do then i'll re say this:

> do you have a more paired down example? I'm not sure what to be looking at or where to suggest things

**Comment by justrealmilk** [comment]
"pared-down" is a colloquialism and the examples is already bare-bones.

**Comment by mayankpandav** [comment]
`<TransitionGroup>
      <CSSTransition
          timeout={500}
          >
           {Children}
            </CSSTransition>
      
        </TransitionGroup>`

You can add CSStransition  ... which leads to remove your Warning Like--

**Warning: Unknown event handler property onExited. It will be ignored.**
**Warning: Received truefor a non-boolean attributein.**

**Comment by mayankpandav** [comment]
```
<TransitionGroup>
      <CSSTransition
          timeout={500}
          >
           {Children}
            </CSSTransition>
      
        </TransitionGroup>

```
You can add CSStransition  ... which leads to remove your Warning Like--

**Warning: Unknown event handler property onExited. It will be ignored.**
**Warning: Received truefor a non-boolean attributein.**

**Comment by gorfadvijay** [comment]
@mayankpandav yaa It's Worked for Me
Thanks !!
