### ISSUE TITLE
Will it be a issue when addEventListener on node in addEndListener?

### ISSUE THREAD

**Issue by goldenyz** [reactjs/react-transition-group#326]
Suppose that we do the following like the example does:
```
<Transition
  ...
  addEndListener={(node, done) => {
    node.addEventListener('transitionend', done, false);
  }}
/>
```
If the transition triggered several times, the node will have multiple listeners for 'transitionend' event.
So when the transitionend triggered, all the listeners will be called? It is not a expected behavior, right?
What is the recommend usage for addEndListener?

**Comment by mgsergio** [comment]
I was wondering the same thing.

**Comment by nanxiaobei** [comment]
wondering too. 😟

**Comment by jquense** [comment]
in practice this works fine. nodes aren't in multiple transitions at once, and if you also add `transitioncancel` here and clean up in your handler. Or add a timeout on the listener that cleans itself up after the `duration`, you can call `done` as many times as you want without breaking anything.
