### ISSUE TITLE
Slide down animation 

### ISSUE THREAD

**Issue by Medsestrun** [reactjs/react-transition-group#330]
How to create slide down animation in https://jsfiddle.net/m4mb9Lg3/4/?
I tried setting height to 0 and my element height, max-height tricks and nothing worked for me for adding or removing item.
`
.fade-asset-enter {
  opacity: 0.01;
  height: 0;
}
.fade-asset-enter-active {
  opacity: 1;
  height: 45px;
  transition: all 500ms ease-in;
}
.fade-asset-exit {
  opacity: 1;
  height: 45px;
}
.fade-asset-exit-active {
  opacity: 0.01;
  height: 0;
  transition: all 500ms ease-in;
}
`

**Comment by silvenon** [comment]
This is more of a general CSS question. If you think there's something we should change in react-transition-group, let me know and I'll reopen.

**Comment by frankwallis** [comment]
you could also try https://github.com/frankwallis/react-slidedown

**Comment by nodox** [comment]
Good to know, but this should be a bit more visible. Spent 3 days in hopeless despair trying to make slide down/up animations work RTG.

**Comment by silvenon** [comment]
What exactly? That animating from `0` to `auto` is impossible in CSS?
