### ISSUE TITLE
Error in Internet Explorer 11 animation caused by npm dependency

### ISSUE THREAD

**Issue by kafeltz** [reactjs/react-transition-group#332]
There is a bug in `v1-stable` branch caused by `dom-helpers` dependency.

The fix is simple, update in package.json.
From: `"dom-helpers": "^3.2.0",`
To: `"dom-helpers": "^3.2.1",`

If you want to know what is happening in `3.2.0` that `3.2.1` fixed you can check my open issue here: https://github.com/react-bootstrap/dom-helpers/issues/40

**Comment by jquense** [comment]
Care to send a PR ? :)

**Comment by kafeltz** [comment]
No problem, here: https://github.com/reactjs/react-transition-group/pull/333
