### ISSUE TITLE
Nested CSSTransition

### ISSUE THREAD

**Issue by trevi** [reactjs/react-transition-group#336]
Tried to upgrade from version 1 to 2:

Has nested CSSTransition(s) such as following:
```
<CSSTransition
   in={in}
   timeout={400}
   classNames="modalWrapperTransition"
   unmountOnExit>
    <div>
      <CSSTransition
          timeout={{enter: 370, exit: 185}}
          classNames="modalTransition"
          unmountOnExit>
          ...
       </CSSTransition>
    </div>
</CSSTransition>
```

When the outer transition is exited (i.e. fade away), the exiting animation of inner transition is also get triggered. Is there a way to prevent the inner transition animation not get triggered?

Using version 1 with CSSTransitionGroup, the exiting animation of outer transition does not trigger the exiting animation of inner transition. 

Just wonder is there a way to do this in version 2?

**Comment by silvenon** [comment]
Could you provide a complete example on CodeSandbox? It would be easier to help if I knew what exactly is the desired effect.

**Comment by silvenon** [comment]
I'm closing this until a demo specifying the desired result is provided. Sometimes these things are not 1:1 portable, so I need a context.

**Comment by nurulakbaral** [comment]
` <CSSTransition key="1" nodeRef={refForm} in={showForm} timeout={500} classNames={`showForm`} unmountOnExit>
          <form ref={refForm} className={`px-8 py-6 mt-12 bg-gray-200 rounded-lg`}>
            <CSSTransition key="2" nodeRef={refTitleForm} in={showForm} timeout={4000} classNames={`showTitleForm`}>
              <h1 ref={refTitleForm} className={`text-center text-4xl font-medium text-blue-600`}>
                Create Post
              </h1>
            </CSSTransition>
          </form>
        </CSSTransition>`

**Comment by nurulakbaral** [comment]
<CSSTransition key="1" nodeRef={refForm} in={showForm} timeout={500} classNames={`showForm`} unmountOnExit>
          <form ref={refForm} className={`px-8 py-6 mt-12 bg-gray-200 rounded-lg`}>
            <CSSTransition key="2" nodeRef={refTitleForm} in={showForm} timeout={4000} classNames={`showTitleForm`}>
              <h1 ref={refTitleForm} className={`text-center text-4xl font-medium text-blue-600`}>
                Create Post
              </h1>
            </CSSTransition>
          </form>
        </CSSTransition>

Same case, my child h1 element cant use his transition class, but always follow form transition

**Comment by nurulakbaral** [comment]
`javascript
<CSSTransition key="1" nodeRef={refForm} in={showForm} timeout={500} classNames={showForm} unmountOnExit>
<form ref={refForm} className={px-8 py-6 mt-12 bg-gray-200 rounded-lg}>
<CSSTransition key="2" nodeRef={refTitleForm} in={showForm} timeout={4000} classNames={showTitleForm}>
<h1 ref={refTitleForm} className={text-center text-4xl font-medium text-blue-600}>
Create Post



Same case, my child h1 element cant use his transition class, but always follow form transition
`

**Comment by nurulakbaral** [comment]
<CSSTransition key="1" nodeRef={refForm} in={showForm} timeout={500} classNames={`showForm`} unmountOnExit>
          <form ref={refForm} className={`px-8 py-6 mt-12 bg-gray-200 rounded-lg`}>
            <CSSTransition key="2" nodeRef={refTitleForm} in={showForm} timeout={4000} classNames={`showTitleForm`}>
              <h1 ref={refTitleForm} className={`text-center text-4xl font-medium text-blue-600`}>
                Create Post
              </h1>
            </CSSTransition>
          </form>
        </CSSTransition>
Same case, my child h1 element cant use his transition class, but always follow form transition

**Comment by silvenon** [comment]
What do you mean? Please provide a CodeSandbox repro.
