### ISSUE TITLE
CSSTransition `in` breaks :hover transitions.

### ISSUE THREAD

**Issue by krabbypattified** [reactjs/react-transition-group#348]
Bug

See Demo
https://codesandbox.io/s/ojzkr98m4y

Actual behavior
When you hover over an item, a pink circle appears. If you hover/click the pink circle, it snaps to a new size.

Expected behavior
It should transition to a new size (Documents.css, line 39)

I'm using Chrome 66 on Mac

**Comment by krabbypattified** [comment]
Related to #216 ?

**Comment by silvenon** [comment]
Your `timeout` prop only has `exit` defined. This causes the class `Circle-enter-active` to stay forever, preventing `Circle-enter-done` from ever showing up. If you set `enter` to, say, `400` (to match the duration of your animation), transitions will work correctly.
