### ISSUE TITLE
TransitionGroup ignores `in` prop

### ISSUE THREAD

**Issue by krabbypattified** [reactjs/react-transition-group#350]
Bug

TransitionGroup ignores the `in` prop in a CSSTransition. If this is expected behavior, it's quite strange to totally ignore a prop.

```
<TransitionGroup>
  <CSSTransition key={1} in={false} unmountOnExit>
    <div className="Panel">Documents</div>
  </CSSTransition>
</TransitionGroup>
```

See this simple demo:
https://codesandbox.io/s/5w83k5qyon

Actual behavior:
Component is rendered

Expected behavior:
Component is not rendered

Using Chrome 66 on Mac

**Comment by jquense** [comment]
it doesn't ignore it, it control it directly. TransitionGroup managing the `in` state of it's children, as you add or remove them. I'm not sure what you want to accomplish here tho so it's a bit hard to make a recommendation. From your snippet tho i would remove `TransitionGroup` if you are interested in managing the child's visibility that way, it's not adding any value.

**Comment by krabbypattified** [comment]
My use case was a CSSTransition that has dynamic contents. If I change the key, it behaves as a different instance and triggers an enter/exit animation. In this case, it should be normal to express it like above. I suppose conditionally rendering the `CSSTransition` element works as well `{foo && <MyComponent/>}`. I guess this is a matter of opinion, so I'll close it.
