### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by bramjoosten** [reactjs/react-transition-group#352]
Missing apostrophe after `my-done-enter`
[https://reactcommunity.org/react-transition-group/css-transition](https://reactcommunity.org/react-transition-group/css-transition)

![image](https://user-images.githubusercontent.com/7580825/41289099-de598d3a-6e48-11e8-8675-64e2ed888b7c.png)

**Comment by taion** [comment]
This was fixed in https://github.com/reactjs/react-transition-group/pull/310. We just need to cut a release.
