### ISSUE TITLE
Typo on website.

### ISSUE THREAD

**Issue by knynkwl** [reactjs/react-transition-group#353]
Not sure if you guy manage this website, and I couldn't find anywhere to post this. Let me know and I can post elsewhere if this isn't the right place.

http://reactcommunity.org/react-transition-group/css-transition/

```
classNames={{
 appear: 'my-appear',
 appearActive: 'my-active-appear',
 enter: 'my-enter',
 enterActive: 'my-active-enter',
 enterDone: 'my-done-enter, <<<<<<< Missing end comma
 exit: 'my-exit',
 exitActive: 'my-active-exit',
 exitDone: 'my-done-exit, <<<<<<< Missing end comma
}}

**Comment by silvenon** [comment]
Thanks! [We fixed this already](https://github.com/reactjs/react-transition-group/blob/7a16b33995008bf56918b5970c3089cc1fc85c91/src/CSSTransition.js#L25-L33) it just hasn't been published yet. (#352)
