### ISSUE TITLE
Element type is invalid - check render method of 'TransitionGroup'

### ISSUE THREAD

**Issue by colemahatmccreary** [reactjs/react-transition-group#362]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Unable to import/use the components due to error on page load. 
I have copied the conventions from the documentation's example, as you'll see below. However when I run the program it throws this error:
 
> Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
> 
> Check the render method of `TransitionGroup`.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [CodeSandbox](https://codesandbox.io/) or similar (Template: https://codesandbox.io/s/lvnpplww9).**

```jsx
import React, { Component } from 'react'
import './App.css'
import { BrowserRouter as Router, Route, Link } from 'react-router-dom'
import {
  Transition,
  CSSTransition,
  TransitionGroup,
} from 'react-transition-group'
import Home from './components/Home'
import About from './components/About'
import Cases from './components/Cases'

class App extends Component {
  render() {
    return (
      <Router>
        <div id="app_wrapper">
          <div id="navbar">
            <ul id="navLinks">
              <Link to="/">
                <li className="navLink">Home</li>
              </Link>

              <Link to="/About">
                <li className="navLink">About</li>
              </Link>

              <Link to="/Cases">
                <li className="navLink">Cases</li>
              </Link>
            </ul>
          </div>

          <TransitionGroup>
            <CSSTransition classNames="page_transition" timeout={500}>
              <Route exact path="/" render={props => <Home {...props} />} />
              <Route path="/About" render={props => <About {...props} />} />
              <Route path="/Cases" render={props => <Cases {...props} />} />
            </CSSTransition>
          </TransitionGroup>

          <div id="footer">THIS IS THE FOOTER</div>
        </div>
      </Router>
    )
  }
}

export default App
```

**What is the expected behavior?**

each Route component simply renders a span containing the given page's title and i'm attempting to include a basic fade-in/out animation on the transition between pages. nothing crazy there, but I haven't been able to get past the initial error referencing the TransitionGroup component.

If I change the above code and remove the TransitionGroup component, instead using CSSTransition on around only ONE of the Route Components like this:

```jsx
<CSSTransition classNames="page_transition" timeout={500}>
  <Route exact path='/' render={(props) => <Home {...props} />} />
</CSSTransition>
```

it returns the same error but instead the last line changes to: 

> Check the render method of `App`.

can't seem to find any relevant discussion on solutions to the problem. 

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

**Comment by solonaarmstrong** [comment]
I have a similar issue. In my case, the error is only in an iframe. If I don't pass an element to the component prop of TransitionGroup and instead use `<TransitionGroup component={null}>` I get the following error:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: null.

Check the render method of `TransitionGroup`.
```

**Comment by silvenon** [comment]
You should wrap `Route` components into a `Switch`, because `CSSTransition` only takes a single component. That's the only error I had when I ran your code, so probably one of your files isn't exporting a valid React component.

If you can reproduce this error in CodeSandbox, I'll be happy to take a look.
