### ISSUE TITLE
Make `react-lifecycles-compat` optional

### ISSUE THREAD

**Issue by msluther** [reactjs/react-transition-group#375]
When updating from version 2.3.1 to 2.4.0, bundle size increased ~2KB due to `react-transition-group` dependency on `react-lifecycles-compat`.  If an app is solely on `react>16.3`, this dependency shouldn't be necessary as the new lifecycle methods will "just work" without any polyfilling.

**Comment by msluther** [comment]
Size difference can be visualized here: https://bundlephobia.com/result?p=react-transition-group@2.4.0

**Comment by jquense** [comment]
There isn't really a good way to make a dep optional for a web library. In this case the size difference is very small considering as well that in a reasonable sized app some dependency is very likely to contain this. If you really want to remove it'd 'id suggest using some webpack magic to alias the package to a noop

**Comment by msluther** [comment]
Ah, right, forgot I could just do:

```js
{
...
  resolve: {
    alias: {
      'react-lifecycles-compat$': path.resolve(__dirname, 'my-lifecycles-compat.js')
    }
  }
}
```

Thanks :)
