### ISSUE TITLE
After update to 2.4.0 got an error

### ISSUE THREAD

**Issue by kyjo2014** [reactjs/react-transition-group#384]
I have got an error after update to 2.4.0.  

Using 2.3.x or below are work fine . but after update to 2.4.0 . when i ran `npm run dev`  chrome get error:  Can only polyfill class components.
"message": "Uncaught Error: Can only polyfill class components\nat

Chrome 68.0.3440 (Mac OS X 10.13.6)
webpack 3.10.0

**Comment by silvenon** [comment]
Hi! Could you set up a repository reproducing this error? It's impossible for me to figure out what the problem is based on only that error message.

I suggest cloning your project, then removing piece by piece until the error doesn't happen anymore. That way you can narrow it down.
