### ISSUE TITLE
Typo in docs breaks syntax highlight

### ISSUE THREAD

**Issue by talyssonoc** [reactjs/react-transition-group#387]
At the value of the `classNames` in CSSTransition component docs (http://reactcommunity.org/react-transition-group/css-transition/#CSSTransition-prop-classNames) there are two missing single-quotes, one at `enterDone` value and the other at `exitDone` value, breaking the syntax highlight. I'd like to submit a PR to fix that but I couldn't find where they are in this repo.

**Comment by taion** [comment]
Did we forget to rebuild docs?

**Comment by silvenon** [comment]
@taion yep 😅
