### ISSUE TITLE
Add transition stage argument to addEndListener

### ISSUE THREAD

**Issue by mvasin** [reactjs/react-transition-group#389]
**Do you want to request a *feature* or report a *bug*?**
A feature.

**What is the current behavior?**
I'm trying to use RTG together with GSAP for route transitions. I need GSAP's timeline feature because transitions are pretty involved.

By the end of a GSAP timeline it would be sweet to call a callback to switch to the next transition state.

Currently, `done` callback is only available in `addEndListener` prop. Using it in context of lifecycle hooks (`onEntering` / `onExiting` etc.) requires a wrapper component, that's a complexity on the user side that could be avoided.

As a side note, requiring timeout prop doesn't look right when you come to rely on done callback.

**Comment by jquense** [comment]
I think we've got this covered by #327 ?

> As a side note, requiring timeout prop doesn't look right when you come to rely on done callback.

It's not required! you can leave off the timeout if you use an endListener, it maybe still be beneficial to use both tho depending on what the end listener is, not a problem with GSAP tho

**Comment by mvasin** [comment]
@jquense I don't understand how #327 addresses this case, that issue is about _classes_, and I'm interested in adding an extra `done` callback as parameter to _functions_ `onEnter`, `onEntering`, `onEntered`, `onExit`, `onExiting`. The goal is not to specify duration information twice, in `timeout` and on GSAP timeline.
> It's not required!

Oh, yes indeed, the warning isn't triggered when `addEndListener` is specified.

**Comment by jquense** [comment]
O see, no we won't add that, the callbacks are just that, callbacks. They are informative, not hooks for controlling the the flow. I think what you want is to avoid timeouts entirely and do all the work in the addEndListener, which can setup and control when the end callbacks are fired.

**Comment by jquense** [comment]
I'm happy to add the current t stage to the end listener, I think that's a good addition if you are up for sending a PR. Adding done handlers to the callbacks isn't feasible architecturually tho

**Comment by mvasin** [comment]
OK, I’ll try to come up with a PR.

**Comment by mvasin** [comment]
Closed due to [discovered workaround](https://github.com/reactjs/react-transition-group/pull/396#issuecomment-413791659).
