### ISSUE TITLE
Components are not properly transitioning in

### ISSUE THREAD

**Issue by alesmenzelsocialbakers** [reactjs/react-transition-group#390]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Components are not being properly animated in the "entering" phase.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [CodeSandbox](https://codesandbox.io/) or similar (Template: https://codesandbox.io/s/lvnpplww9).**

Here is a reproduction:
https://codesandbox.io/s/l52pklw797

**What is the expected behavior?**

Component is animated in the "entering" phase instead of the sudden skip.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Chrome: 67.0.3396.99 (Official Build) (64-bit) (Incognito Mode)
OS: Windows 10

**Comment by jquense** [comment]
The documentation is correct, but the pseudo example is not complete, it needs to reflow the browser, and the behavior your seeing is a bug in the example. @silvenon maybe we can find something really simple that works out of the box for the Transition example, or maybe we should use something like element.animate/jquery in that example to not suggest that css transitions are as easy as the example suggests?

@alesmenzelsocialbakers the issue with your pen is you are hitting the reflow pitfall noted in the callout in the Transition docs http://reactcommunity.org/react-transition-group/transition, consider using CSSTransition instead

**Comment by alesmenzelsocialbakers** [comment]
@jquense you are right, totally missed the note, thanks for explaining 👍

**Comment by alesmenzelsocialbakers** [comment]
For anyone looking for a quick and dirty hack, add `onEnter={node => node && node.scrollTop}` ([CSSTransition uses the same in order to force a browser repaint](https://github.com/reactjs/react-transition-group/blob/master/src/CSSTransition.js#L219))
