### ISSUE TITLE
Help with migrating to 2.4.0 CSStransitions

### ISSUE THREAD

**Issue by ZymantasPonelis** [reactjs/react-transition-group#392]
Hello, can someone please help me out ? I'm stuck for hours on this.
So i want to trigger an animation everytime the props/state changes. Example is in 1.2.1,it works.
https://codesandbox.io/s/vn18oxk64l
But i can't reproduce this functionality on 2.4.0v. I think im missing out something on migration documentation , or i am definitely stupid.
Thank you

**Comment by silvenon** [comment]
Instead of setting `key` on the `div` element, you should set it on the `CSSTransition` element.

```jsx
<CSSTransition
  key={this.state.name}
  classNames="example"
  appear
  in
  timeout={500}
>
  <div>{this.state.name}</div>
</CSSTransition>
```
