### ISSUE TITLE
CSSTransition - All props not documented.

### ISSUE THREAD

**Issue by densk1** [reactjs/react-transition-group#407]
**Do you want to request a *feature* or report a *bug*?**
**Feature:** Undocumented props on `<CSSTransition />`

[**Documentation Here**: /react-transition-group/css-transition](http://reactcommunity.org/react-transition-group/css-transition)

**What is the current behaviour?**
Have tested and the following props work, but are missing from documentation:
- `mountOnEnter`
- `unmountOnExit`
- `timeout={}`

I haven't tested these others, but are they also available as props on `<CSSTransition />`?
- `appear`
- `enter`
- `exit`
- `addEndListener`

**Comment by jquense** [comment]
See the line under the Props heading in the docs, it also accepts the same props as Transition, which are documented on that component
