### ISSUE TITLE
Callbacks in ReactCSSTransitionGroup

### ISSUE THREAD

**Issue by todorone** [reactjs/react-transition-group#41]
**Do you want to request a *feature***
Hi @jquense, at first thanks for maintaining this useful library. I'm using `ReactCSSTransitionGroup` on my project and i need to maintain logic after animation is finished. Yes, i read documentation note, that if i need callback, i should use `ReactTransitionGroup` instead, but looking at the sources it's not that hard to add callback prop to `ReactCSSTransitionGroup`. So is it possible to add simple callback if i do PR or it's not possible at all by some (architecture?) reasons? Thanks.

**Comment by trsh** [comment]
I also think componentWillAppear etc. should be working from CSSTransitionGroup. Need it a lot.

**Comment by jtorhoff** [comment]
I agree, especially if you don't need any special logic but just access to these callbacks, you would basically have to copy-paste the whole CSSTransitionGroup implementation along with CSSTransitionGroupChild to just add a couple of lines of code.

There is really no reason to hide these callbacks in the high-level API.

**Comment by jquense** [comment]
in v2 callbacks are accessible from CSSTransition, thanks!
