### ISSUE TITLE
Support className prop on Transition

### ISSUE THREAD

**Issue by jamesplease** [reactjs/react-transition-group#412]
**Do you want to request a *feature* or report a *bug*?**

A feature.

**What is the current behavior?**

`CSSTransition` renders a `div`, but you cannot specify a constant, custom `className` on it.

**What would you like to see changed?**

I use CSSTransitions in components that are meant to be shared. Users can pass a custom class name to those components.

It makes sense to use the CSSTransition as the root node, and to apply the custom class that is passed onto that root node. However, the only way I know to do that right now is via:

```jsx
classNames={{
  appear: `${className} dialog_transition-appear`,
  appearActive: `${className} dialog_transition-appear-active`,
  enter: `${className} dialog_transition-enter`,
  enterActive: `${className} dialog_transition-enter-active`,
  enterDone: `${className} dialog_transition-enter-done`,
  exit: `${className} dialog_transition-exit`,
  exitActive: `${className} dialog_transition-exit-active`,
  exitDone: `${className} dialog_transition-exit-done`,
}}
```

It would be preferable to do this instead:

```jsx
className={className}
classNames="dialog_transition"
```

**Comment by jquense** [comment]
there is nothing stopping you from doing that 👍 . it works like you are expecting

**Comment by jamesplease** [comment]
Whoops, this was my mistake. I see now that it modifies its first child. Sorry for the noise!
