### ISSUE TITLE
Docs inaccurate

### ISSUE THREAD

**Issue by Noitidart** [reactjs/react-transition-group#417]
Hi there,

I clicked the docs for CSSTransition and am seeing props like `in` and stuff not documented - http://reactcommunity.org/react-transition-group/css-transition/

I also checked the walkthrough for migration from v1, and it seems that is outdated/wrong - https://github.com/reactjs/react-transition-group/blob/master/Migration.md - please correct, or remove from readme.

**Comment by Noitidart** [comment]
The CodeBox apparently shows `CSSTransition` takes a child as a function or something.

I can't figure out how to use this. Please help.

**Comment by jquense** [comment]
As the docs say CssTransition inherits all of the props from Transition, one should read the API for both components

**Comment by Noitidart** [comment]
Oh thank you @jquense this is very nice. May you please show example of `<Transition>` without a functional child?

**Comment by Noitidart** [comment]
Thanks so much for sharing @silvenon !

So with react element,it is not possible to do any animation?

**Comment by silvenon** [comment]
Not with `Transition`, it's probably supported only because `CSSTransition` needs it, but it's not documented on purpose. You should use `CSSTransition` instead, then you can use classes to apply transitions.

**Comment by Noitidart** [comment]
Ohhh I got it now. Thank you so much @silvenon !!
