### ISSUE TITLE
Have the transitionName also applied to the CSSTransitionGroup component

### ISSUE THREAD

**Issue by Shywim** [reactjs/react-transition-group#42]
I'm using two differents CSSTransitionGroup, one for `enter` transition and the other for `leave` transition. I do this because I have the same `leave` transition for the children, but I have *different* `enter` transition depending on which children is mounted and these CSSTransitionGroup are nested deeper which cause my `enter` transition and my `leave` transition to happen both at the same time.

For now I just put a longer delay in CSS but when there's no leave animation to do (i.e. when first loading) there's a small noticeable delay where nothing happen.

I know I can workaround it directly in JS or with ReactTransitionGroup but it would be nice to have an option to add a class to the CSSTransitionGroup itself when it's animating so we can continue to work exclusively with CSS. 😄

**Comment by jquense** [comment]
That's a bit tough to do in the current API, but if you could check out https://github.com/reactjs/react-transition-group/pull/24 we probably could support that in the new proposed api, as it provides a lot more callback hooks. Maybe see if that could meet your use case? It might even avoid your need for two groups as it allows different animations per child

**Comment by Shywim** [comment]
Oh I didn't see when I was searching. That might do it, I'll forward to it, thanks!
