### ISSUE TITLE
CDN / External link Dead

### ISSUE THREAD

**Issue by joss-c** [reactjs/react-transition-group#420]
**Do you want to request a *feature* or report a *bug*?**

Bug

**What is the current behavior?**

Link at https://reactcommunity.org/react-transition-group/ for CDN produces error:

"Cannot find "/dist/react-transition-group.min.js" in react-transition-group@2.5.0"

**Comment by silvenon** [comment]
Removing `.min` should work. Do you mind submitting a PR to the docs to update this?

**Comment by silvenon** [comment]
Fixed in #421.
