### ISSUE TITLE
Content within dist folder changes

### ISSUE THREAD

**Issue by ahagelstein** [reactjs/react-transition-group#426]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
Folder "\react-transition-group\dist" contains only one file
- "react-transition-group.js" --> minified version

**What is the expected behavior?**
Folder "\react-transition-group\dist" should contain two files 
- "react-transition-group.js"
- "react-transition-group.min.js"

**Steps**
- npm install react-transition-group --save
- look into "\node_modules\react-transition-group\dist"

**Comment by iamandrewluca** [comment]
@silvenon I think this can be closed.
https://unpkg.com/browse/react-transition-group@4.4.0/dist/

**Comment by silvenon** [comment]
Indeed, thanks!
