### ISSUE TITLE
Avoid transition with boolean?

### ISSUE THREAD

**Issue by qodesmith** [reactjs/react-transition-group#433]
**Do you want to request a *feature* or report a *bug*?**
Feature - unless this can be done already...

**What is the current behavior?**
Transitioning between two components that are *the same* component (i.e. 2 `<Route>`'s in RR4 that render the same component) unmounts and remounts that component. It would be convenient to provide some flag that indicates "I know you want to transition right now but don't - I'm handling things."

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via [CodeSandbox](https://codesandbox.io/) or similar (Template: https://codesandbox.io/s/lvnpplww9).**

**What is the expected behavior?**

When providing some flag with a boolean, no transition should happen.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
I'm using 2.5.0 of this package, React Router 4.3.1, and the latest version of React (16.7.0-alpha.0 - hooks!).

**Comment by qodesmith** [comment]
My situation looks something like this:

```javascript
<TransitionGroup id="container">
  <CSSTransition
    key={location.key}
    classNames={TRANSITION_CLASSES}
    timeout={TRANSITION_TIME}
  >
    <Switch location={location}>
      <Route exact path="/" component={Home} />
      <Route exact path="/music" component={Music} />
      <Route path="/music/:album/:song" component={Album} />
      <Route path="/music/:album" component={Album} />
      <Route component={NotFound} />
    </Switch>
  </CSSTransition>
</TransitionGroup>
```

I'm in the predicament where the `Album` component renders for both an "album" page and a "song" page. I want to prevent the transitioning from happening when going from the album page to the song page, which use the same component. If I use vanilla RR4, the `Switch` does not remount the same component, so that's good. Unfortunately, in my case, the remounting *does* happen when wrapping it all in the transition group & friends as seen above. And this is normal, I get that. I just wish there were some way to pass in a flag that would indicate "don't transition, don't remount, don't do anything but simply render your children as is." I hope I communicated that correctly. Sorry if there's confusion!

**Comment by taion** [comment]
It's remounting because you're passing a new `key` into `<CSSTransition>`. Just don't do that.

**Comment by qodesmith** [comment]
@taion Thank you for the tip! What ended up working for me was this:

```jsx
...
<CSSTransition key={someCondition ? 'stay' : location.key}>
...
```
