### ISSUE TITLE
Text components in ReactTransitionGroup give "Element type is invalid"

### ISSUE THREAD

**Issue by gaearon** [reactjs/react-transition-group#45]
Not sure if this is still relevant (sorry!)
Moving https://github.com/facebook/react/issues/6365 here.

Original report by @spicyj  below.

-----

```js
<ReactTransitionGroup>Welcome to React</ReactTransitionGroup>
```

throws

```
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. Check the render method of ReactTransitionGroup.
```

Not sure what this should do, but at the very least the error message is terrible.

**Comment by juanca** [comment]
It is but only for IE (at least reproducible in 11).

I just uncovered this when trying to run my spec suite in IE 11. 

Wrapping the text in a `<span>` tag fixes it. 

I don't really have a use case for animating a text node so I don't think I would have run into this problem in production (but that woulda sucked).

I mean, are text nodes animatable? I would think it needs to be wrapped in some element.

**Comment by gaearon** [comment]
I think the actionable item here is to throw a better error early,

**Comment by jquense** [comment]
Maybe just change the propTypes for children to element?

**Comment by gaearon** [comment]
It's still an array though isn't it? And could be nested arrays too I think (not sure if TG can handle them).

**Comment by koba04** [comment]
I think this is already outdated. `TransitionGroup` now accepts `PropTypes.node` so this could be closed now.
But passing a string to TranstionGroup's children doesn't make sense. Should we warn about it?

**Comment by eko24ive** [comment]
cc: @gaearon @koba04 
Sorry to bother you guys, any updates so far?

**Comment by jquense** [comment]
As a general rule of thumb, if there is not activity on the issue, there are no updates.

**Comment by eko24ive** [comment]
Fair enough ¯\_(ツ)_/¯

**Comment by silvenon** [comment]
I tried this now with v2.3.1 and it works, it doesn't throw an error (I tried in IE 11, too). Please let me know if this is still a problem, preferably with a CodeSandbox demo.
