### ISSUE TITLE
You may need an appropriate loader to handle this file type.

### ISSUE THREAD

**Issue by atifaziz2** [reactjs/react-transition-group#452]
I am getting this error in all browsers.

in ./node_modules/preact-css-transition-group/src/CSSTransitionGroup.js 20:21 Module parse failed: Unexpected token (20:21) You may need an appropriate loader to handle this file type. | | export class CSSTransitionGroup extends Component { > static defaultProps = { | component: 'span', | transitionEnter: true,

**Comment by jquense** [comment]
I don't know what `preact-css-transition-group` is but it's not this package. it looks like it's not uncompiled code in it maybe?
