### ISSUE TITLE
Usage with transform-react-remove-prop-types 

### ISSUE THREAD

**Issue by Andarist** [reactjs/react-transition-group#46]
In the way `PropTypes` are structured here in the project [babel-plugin-transform-react-remove-prop-types](https://github.com/oliviertassinari/babel-plugin-transform-react-remove-prop-types) cannot remove them safely. I think its mainly because you import some definitions from other files. 

Could something be done with it? Desired behaviour would be ofc that the removing transform can work.

**Comment by jquense** [comment]
That seems like a limitation of the babel-transform. I'm not going to copy and paste the common propTypes everywhere to allow this. not everyone uses this plugin so it makes the more common case worse. Not sure if there is a middle ground on that though

**Comment by Andarist** [comment]
Will try to pursue this on the transform's side then. Thanks for the answer.

**Comment by taion** [comment]
In general you probably shouldn't be running this transform on library code yourself – libraries that don't use these at runtime should themselves use this transform.

**Comment by Andarist** [comment]
@taion Hm, actually I dont think thats the case. PropTypes are cool in dev mode but unneccessary in production in most cases. So in general libraries need to include them in their outputs. But maybe `wrap` mode in this transform is the way to go for libraries. Aint sure about this though

**Comment by taion** [comment]
That's precisely how it should work. In general, running Babel transforms on library code is not a good thing.

**Comment by Andarist** [comment]
yeah, sure it can be dangerous ;) no risk no fun though :trollface: 

the `prop-types` thing doesnt even bother me that much, im more interested if something can be done about duplication of babel helpers in each library, but thats another topic
