### ISSUE TITLE
The Transition doesn't work in the document

### ISSUE THREAD

**Issue by kk412027247** [reactjs/react-transition-group#473]
**Do you want to request a *feature* or report a *bug*?**
-  bug

**What is the current behavior?**
The **Transition** doesn't work in the document.

https://codesandbox.io/embed/741op4mmj0

![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/30715186/54259181-d9efd180-459f-11e9-96ea-6803050a713f.gif)

**Comment by taion** [comment]
Please provide more details on what you expect v. what you observe.

**Comment by kk412027247** [comment]
@taion I expect the text should fade in and fade out.But in the demo the text change without animation

**Comment by taion** [comment]
See the docs here: https://reactcommunity.org/react-transition-group/transition

You need to use styling to make things actually animate.

**Comment by kk412027247** [comment]
@taion  Thx.
After I change some code, it work well.

https://codesandbox.io/s/mm13zzkx0j?fontsize=14

![example](https://user-images.githubusercontent.com/30715186/54407428-c320ba80-4718-11e9-9931-78d007a4024c.gif)
