### ISSUE TITLE
v2.7.0 breaks legacy module import

### ISSUE THREAD

**Issue by kaidjohnson** [reactjs/react-transition-group#475]
> What is the current behavior?

```
var TransitionGroup = require('react-transition-group/TransitionGroup');
```
v2.7.0 returns an object `{ default: <TransitionGroup> }`

> What is the expected behavior?

v2.6.1 returns the `TransitionGroup` function directly.

`react-transition-group` is a ternary dependency from a few depths of our package tree, but I've confirmed that downgrading to 2.6.1 fixes the issue for us, but forces us to surface a ternary dependency in our package.json directly.

**Comment by TrySound** [comment]
Do you mean transitive dependency?

**Comment by TrySound** [comment]
@silvenon It's probably should be a major bump.

**Comment by silvenon** [comment]
@TrySound I don't get it, do you know why this is happening and if it should? I thought CJS build stayed the same and that we just linked to it via a generated `package.json`.

**Comment by silvenon** [comment]
@TrySound if this is expected and necessary behavior, then I'll revert the change in the next patch version and repeat the ESM commit as a breaking change.

**Comment by silvenon** [comment]
We'll publish a new patch version within the next few days.

**Comment by TrySound** [comment]
The problem is importing esm from cjs. Usually it's not a problem. But it is for example with material-ui.

**Comment by TrySound** [comment]
@kaidjohnson Though there should be interop in that package. Which package depends on react-transition-group?

**Comment by kaidjohnson** [comment]
@TrySound I believe I traced it to https://github.com/google-fabric/velocity-react/blob/master/src/velocity-transition-group.js#L56 v1.4.1 within Storybook v4.1.12

**Comment by kaidjohnson** [comment]
:laughing: Yes, transitive :roll_eyes: Fridays and words don't always mix good.

**Comment by TrySound** [comment]
Well, frontend projects written with commonjs is unexpected thing these days.
