### ISSUE TITLE
bug after the last commit you did the last friday !! 

### ISSUE THREAD

**Issue by hamzachaouch** [reactjs/react-transition-group#476]
this commit caused a problem in our work (attached in the first screenshot)  ... 
![bug](https://user-images.githubusercontent.com/22745729/54931220-e4538900-4f18-11e9-83d9-ba9771cc7668.PNG)

this screenshot shows the cmd error displayed when building our project : 

![err](https://user-images.githubusercontent.com/22745729/54931558-86737100-4f19-11e9-8047-5faf0d83273a.png)

need help !!

**Comment by Jasper-Hilven** [comment]
+1

**Comment by mateoholman** [comment]
+1 bump

**Comment by n0tus** [comment]
Does anyone have a work around? It seems like it is a dependency of a dependency or something. I tried specifying the previous version in my package.json butt it didn't address the problem.

**Comment by gonzozavala** [comment]
same.  `.../node_modules/react-transition-group/esm/Transition.js`is failing... damn.

**Comment by gonzozavala** [comment]
Reverting to 2.6.1 until further notice.

**Comment by varun-gaur** [comment]
@gonzozavala How did you revert to 2.6.1?
Please let me know.
Thanks.

**Comment by silvenon** [comment]
I reverted the breaking commit and released a patch version, [v2.7.1](https://github.com/reactjs/react-transition-group/releases/tag/v2.7.1) should be stable now. We need some more expertise on publishing modules correctly before we implement tree-shaking properly. Sorry everyone.

**Comment by Jasper-Hilven** [comment]
Thank you for the quick fix. Maybe an integration test which uses this package as library can avoid these problems in the future? (If only we had more time ;) )

**Comment by silvenon** [comment]
Definitely! 👍
