### ISSUE TITLE
current release has broken module entry point

### ISSUE THREAD

**Issue by TrySound** [reactjs/react-transition-group#477]
> What is the current behavior?

Seems like publish tool does not consider module field
  "main": "cjs/index.js",
  "module": "lib/esm/index.js",

> What is the expected behavior?

Publish tool should consider module field

**Comment by silvenon** [comment]
Reverted tree-shaking changes in [v2.7.1](https://github.com/reactjs/react-transition-group/releases/tag/v2.7.1).
