### ISSUE TITLE
Are components re-rendered before being transitioned out?

### ISSUE THREAD

**Issue by georgedumontier** [reactjs/react-transition-group#478]
I have a `<CSSTransition>` that animates out either to the left or to the right. (depending which button the user clicks).  It works basically like an image slider.

My state updates the classNames prop to tell the component which way to enter or exit. The problem is that the component being transitioned out doesn't seem to respond to the latest updates from state. My workaround is to set the classes manually with onExit and onExiting, making sure they're up to date.

```
<CSSTransition
    classNames={this.props.leftOrRight}
    key={key}
    timeout={{enter:300, exit:300}}

    //I'm using these functions to make sure the state matches the className :(
    onExit={(node) => exit(node,this.props.leftOrRight)} 
    onExiting={(node) => exiting(node,this.props.leftOrRight)} 
 >
   <ol className="defs">
        {def.map((def,idx) => (<li key={idx} >{def}</li>))}
    </ol>                          
</CSSTransition>
```
So is react-transition-group supposed to re-render a component before it's unmounted? Or is there a good way for me to force it to update before unmounting?

**Comment by georgedumontier** [comment]
This issue helped me. https://github.com/reactjs/react-transition-group/issues/182

The short answer is you can't update a component as it's leaving,  you need to pass in a (poorly named) child factory prop.

**Comment by silvenon** [comment]
If you have suggestions on how to improve the docs, please share them. 🙂

**Comment by georgedumontier** [comment]
Sorry! I didn't mean that child factory wasn't a clear name for the prop -- just that it reminds me of child labor. An admittedly confusing and bad joke.

**Comment by silvenon** [comment]
🤣😅 Still, feel free to update the docs to add this example use case so someone facing a similar challenge can figure it out from the docs.
