### ISSUE TITLE
Confusion over order lifecycle functions are called

### ISSUE THREAD

**Issue by mkalish** [reactjs/react-transition-group#48]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
willReceiveProps is run before both componentWillEnter and componentDidEnter but is called after componentWillLeave and componentDidLeave

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**
https://jsfiddle.net/8u3va7m2/

**What is the expected behavior?**
I would expect willReceiveProps to be called before componentWillLeave and componentDidLeave

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
Current version on all OS and browser; unsure if this worked in previous versions

**Comment by jquense** [comment]
The lifecycle hooks aren't part of the React components so its not really something I can coordinate or control unfortunately

**Comment by mkalish** [comment]
I can go ahead and close this then.  I'm guessing this is something to open in the react repo?

**Comment by jquense** [comment]
Honestly they can't really help either. It's just not something you can coordinate between the two. The aren't really related to each other aside from similar sounding names
