### ISSUE TITLE
TransitionGroup doesn't work

### ISSUE THREAD

**Issue by buyou0821** [reactjs/react-transition-group#484]
> What is the current behavior?

When I writed the `CSSTransition` component to a function component. `TransitionGroup` can't automatically manage the `in` prop.

> What is the expected behavior?

I hope `TransitionGroup` can automatically manage the `in` prop

https://codesandbox.io/s/j1408z2pn9

**Comment by jquense** [comment]
there is a few things here that aren't correct which is why it's not working: take a look at this: https://codesandbox.io/s/xvzyj1x8zo
