### ISSUE TITLE
Timing issue with `enter` transitions

### ISSUE THREAD

**Issue by kylpo** [reactjs/react-transition-group#5]
Sorry for not having a codepen to show this off, but when we switched from `react-addons-css-transtion-group` to this lib, we noticed the `enter` and `enter-active` styles were applied at the same time, resulting in no transition. From looking at differences in the libs, I see that this one is using a `raf` helper, and I'm wondering if that is the problem?

For example: with a fade-in style like:
```js
  enter: {
    opacity: 0,
    transition: 'opacity 3000ms ease',
  },
  enter-active: {
    opacity: 1,
  }
```
The `enter` items receive `opacity: 1` immediately and do not fade in.

This issue was found in the latest stable Chrome.

**Comment by koba04** [comment]
I have the same issue. I'm not sure the cause of this. But I'll work on this.
