### ISSUE TITLE
Easy way to use with react-router

### ISSUE THREAD

**Issue by honi** [reactjs/react-transition-group#50]
**Do you want to request a *feature* or report a *bug*?**
Feature

**What is the current behavior?**
I define my routes inside a `TransitionGroup` with a childFactory that wraps each child in a `Page` component that defines the TransitionGroup lifecycle methods.

```javascript
const One = () => <div>One</div>;
const Two = () => <div>Two</div>;

<TransitionGroup childFactory={child => <Page>{child}</Page>}>
    <Route exact path='/one' component={One} />
    <Route exact path='/two' component={Two} />
</TransitionGroup>
```

```javascript
class Page extends Component {
    componentWillAppear(callback) {
        console.log('componentWillAppear');
        callback();
    }

    componentDidAppear() {
        console.log('componentDidAppear');
    }

    componentWillEnter(callback) {
        console.log('componentWillEnter');
        callback();
    }

    componentDidEnter() {
        console.log('componentDidEnter');
    }

    componentWillLeave(callback) {
        console.log('componentWillLeave');
        callback();
    }

    componentDidLeave() {
        console.log('componentDidLeave');
    }

    render() {
        return this.props.children;
    }
}
```

**What is the expected behavior?**
Only valid childs should be wrapped in `Page` components. I understand each `Route` *is* a valid child for the `TransitionGroup`, though only one of them actually renders to a node, so I always get 2 `Page` components, which makes it impossible to animate in/out the routes.

I understand this issue might be out of scope for this library, in which case, anybody has any pointers on how this could work?

**Comment by jquense** [comment]
I am not sure honestly! But maybe this issue has some pointers? https://github.com/reactjs/react-transition-group/issues/37

**Comment by honi** [comment]
Thanks @jquense, I didn't see that issue. I've posted there hoping to get some more insights from the other users on that issue. Feel free to close this one.
