### ISSUE TITLE
Clear best practice related to timeouts on testing transitions 

### ISSUE THREAD

**Issue by ericschultz** [reactjs/react-transition-group#501]
> What would you like improved?
A clear way to handle transition timing for tests

When verifying that onExited is properly called on a Transition, one has to use an async test and use setTimeout to make sure the exit transition has had time to finish. This is rather inconvenient and slows down the testing time because we need to wait for a transition to finish that we don't actually care about.

Ideally, it'd be nice to have a single function call to adjust how timeouts should be handled during a test. For example, should they simply run immediately? Or should all timeouts be sped up by a particular multiple?

I appreciate that, given that we have to use css transitions timing as well as the timeout on the component, this could be quite difficult to do. In the event that such a change is impractical, it'd be helpful to have a set of best practices for testing. How do others handle this issue?

**Comment by jquense** [comment]
hey there, the timeouts are technically required, but if you are concerned just about speeding up tests, i'd lean on whatever your testing framework is for that. most mocking tools provide ways to make timers sync and give control over when they are run. for example `jest.useFakeTimers`, and `sinon` as well has tools
