### ISSUE TITLE
code splitting cause enter animation doesn't work

### ISSUE THREAD

**Issue by XvJX** [reactjs/react-transition-group#513]
> When I use code splitting into the page, I could only trigger the exit animation, and the enter animation doesn't work. Everything is ok when not use code splitting.

### react-transition-group   Component

```
<Route render={({ location }) => (
        <TransitionGroup>
            <CSSTransition
                key={location.key}
                classNames="route forward"
                timeout={350}
            >
                <Switch location={location}>{children}</Switch>
            </CSSTransition>
        </TransitionGroup>
    )}
/>;
```

### css

```
:global(.forward-enter), :global(.forward-appear) {
    transform: translate3d(100%, 0, 0);
}

:global(.forward-enter-active), :global(.forward-appear-active) {
    transform: translate3d(0, 0, 0);
    transition: all 0.35s cubic-bezier(0.36, 0.66, 0.04, 1);
}

:global(.forward-enter-done) {
    transform: translate3d(0, 0, 0);
}

:global(.forward-exit) {
    transform: translate3d(0, 0, 0);
}

:global(.forward-exit-active) {
    transform: translate3d(-100%, 0, 0);
    transition: all 0.35s cubic-bezier(0.36, 0.66, 0.04, 1);
}
```

### code splitting  @loadable/component

```
import Loadable from '@loadable/component';
const Index = Loadable(() => import('../pages/Index/Index'));
const Game = Loadable(() => import('../pages/Game/Game'));
export default (
    <BrowserRouter basename={prefixUrl}>
        <RouterTransition>
            <Route exact={true} path="/" component={Index} />} />
            <Route exact={true} path="/game" component={Game} />
        </RouterTransition>
    </BrowserRouter>
);
```

**Comment by taion** [comment]
What do you expect to happen, exactly? The only thing that could transition in here would be your loading indicator, right?

**Comment by XvJX** [comment]
What I hope is that both enter and exit animations will trigger. In my css code, I can only trigger "forward-exit", "forward-enter" can't trigger. but its both can trigger when without using code splitting.

**Comment by XvJX** [comment]
> What do you expect to happen, exactly? The only thing that could transition in here would be your loading indicator, right?

What I hope is that both enter and exit animations will trigger. In my code, I can only trigger "forward-exit", "forward-enter" can't trigger. but its both can trigger when without using code splitting.

**Comment by taion** [comment]
Well, it's rendering your loading indicator, right? Does your loading indicator accept those styles?

**Comment by XvJX** [comment]
> Well, it's rendering your loading indicator, right? Does your loading indicator accept those styles?

Of cause accept. Here are two GIF links to show you what problems I had happened.
success case: [https://www.stustep.com/gif/right.gif](url).

fail case: [https://www.stustep.com/gif/error.gif](url).

**Comment by taion** [comment]
This is almost certainly a bug in your code where your "loading indicator" component is not accepting the injected props. If you have further reason to suspect a bug here, please post e.g. a CodeSandbox or equivalent.

**Comment by GOGOGOSIR** [comment]
> > 好吧，它正在渲染你的加载指标，对吗？您的装载指示器是否接受这些样式？
> 
> 原因接受。这里有两个GIF链接，向您展示我发生了什么问题。
> 成功案例：[https](https://www.stustep.com/gif/right.gif)：[//www.stustep.com/gif/right.gif](https://www.stustep.com/gif/right.gif)。
> 
> 失败案例：[https](https://www.stustep.com/gif/error.gif)：[//www.stustep.com/gif/error.gif](https://www.stustep.com/gif/error.gif)。

老哥，问题解决了吗，我也遇到和你一样的问题

**Comment by shinvey** [comment]
> > When I use code splitting into the page, I could only trigger the exit animation, and the enter animation doesn't work. Everything is ok when not use code splitting.
> 
> ### react-transition-group Component
> ```
> <Route render={({ location }) => (
>         <TransitionGroup>
>             <CSSTransition
>                 key={location.key}
>                 classNames="route forward"
>                 timeout={350}
>             >
>                 <Switch location={location}>{children}</Switch>
>             </CSSTransition>
>         </TransitionGroup>
>     )}
> />;
> ```
> 
> ### css
> ```
> :global(.forward-enter), :global(.forward-appear) {
>     transform: translate3d(100%, 0, 0);
> }
> 
> :global(.forward-enter-active), :global(.forward-appear-active) {
>     transform: translate3d(0, 0, 0);
>     transition: all 0.35s cubic-bezier(0.36, 0.66, 0.04, 1);
> }
> 
> :global(.forward-enter-done) {
>     transform: translate3d(0, 0, 0);
> }
> 
> :global(.forward-exit) {
>     transform: translate3d(0, 0, 0);
> }
> 
> :global(.forward-exit-active) {
>     transform: translate3d(-100%, 0, 0);
>     transition: all 0.35s cubic-bezier(0.36, 0.66, 0.04, 1);
> }
> ```
> 
> ### code splitting @loadable/component
> ```
> import Loadable from '@loadable/component';
> const Index = Loadable(() => import('../pages/Index/Index'));
> const Game = Loadable(() => import('../pages/Game/Game'));
> export default (
>     <BrowserRouter basename={prefixUrl}>
>         <RouterTransition>
>             <Route exact={true} path="/" component={Index} />} />
>             <Route exact={true} path="/game" component={Game} />
>         </RouterTransition>
>     </BrowserRouter>
> );
> ```

```jsx
<Route render={({ location }) => (
  <TransitionGroup>
    <CSSTransition
      key={location.key}
      classNames="route forward"
      timeout={350}
    >
      {
        /*
       This div element is the key to solve the problem.
       We can make CSSTransition Component add classes on the div element
       to perform CSS transition effect.
       So whatever changes in Switch Component, It does not affect
       the div element. That's why it can solve the problem.
        */
      }
      <div className="transition-content">
        <Switch location={location}>{children}</Switch>
      </div>
    </CSSTransition>
  </TransitionGroup>
)}
/>;
```

**Comment by Jassu225** [comment]
This is happening to me as well.

**Comment by eunwoo** [comment]
I also have experienced this problem. Maybe react-traisition-group doesn't support code splitting by loadable.

Here is my code.

```
import React, { useRef, useEffect } from "react";
import { Routes, Route } from "react-router";
import { BrowserRouter, useLocation, Link } from "react-router-dom";
import ROUTES from "Constants/routes";
import loadable from "@loadable/component";
import { TransitionGroup, CSSTransition } from "react-transition-group";

// When I use loadable, 'enter' css doesn't apply.
// const Intro = loadable(() =>
//   import(/* webpackChunkName: "ContextMenuChunk" */ "Pages/intro/intro")
// );
// const Page2 = loadable(() =>
//   import(/* webpackChunkName: "ContextMenuChunk" */ "Pages/page2/page2")
// );
import Intro from "Pages/intro/intro";
import Page2 from "Pages/page2/page2";

export function App1() {
  const location = useLocation();

  return (
    <TransitionGroup component={null}>
      <CSSTransition key={location.key} classNames="fade" timeout={3000}>
        <Routes location={location}>
          <Route path={ROUTES.INTRO} element={<Intro />} />
          <Route path={ROUTES.PAGE2} element={<Page2 />} />
        </Routes>
      </CSSTransition>
    </TransitionGroup>
  );
}
```
