### ISSUE TITLE
Transition dos not wait for transitionEnd event.

### ISSUE THREAD

**Issue by mgsergio** [reactjs/react-transition-group#517]
## What is the current behavior?

Transition unmounts component before transition completes when addEndListener is used instead of timeout.

## What is the expected behavior?

Transition waits for transition end when addEndListener is used without a timeout.

## Demo

[Here](https://codesandbox.io/embed/csstransition-component-thl7g) you can find a modified example from the docs. I set all transitions to 700ms stress the difference in card showing and disappearing. When you press "Show Message" a card appears with transition and you can see the whole animation. When you press "Close" transition begins and then the card suddenly disappears.

**Comment by fkhadra** [comment]
Hey @mgsergio,

I don't think this is a bug. Your sandbox is using the `CSSTransition` component with `addEndListener` props which available only on the `Transition` component.

CSSTransition Props
![image](https://user-images.githubusercontent.com/5574267/68678400-2be95c80-055e-11ea-902c-87cd6f56da69.png)

TransitionProps
![image](https://user-images.githubusercontent.com/5574267/68678498-563b1a00-055e-11ea-8d10-8dd9247066aa.png)

Hope this can help.
