### ISSUE TITLE
One more element appear when exchange key in Animation Group

### ISSUE THREAD

**Issue by dlutwuwei** [reactjs/react-transition-group#52]
# bug

One more element appear when exchange key in Animation Group

Here is [example](http://codepen.io/dlutwuwei/pen/RVLxyP)

This example should only exchange element in list.

**Comment by jquense** [comment]
In your example it's because you are really creating 3 items as determined by their keys. Item keys should be unique and stable for items. If you change the key of a child it's considered a different item, hence the extra one
