### ISSUE TITLE
Transition and CSSTransition component files import prop-types incorrectly

### ISSUE THREAD

**Issue by InsaneViku** [reactjs/react-transition-group#529]
> What is the current behavior?

Currently, `Transition` and `CSSTransition` component files import `prop-types` as:

```
import * as PropTypes from 'prop-types';
```

> What is the expected behavior?

All other components and files are importing prop-types in the [expected way](https://github.com/facebook/prop-types#importing):

```
import PropTypes from 'prop-types';
```

I think a simple PR to just update these two files would suffice so there's consistent importing and usage of `prop-types` throughout.

**Comment by taion** [comment]
We'd be happy to take such a PR.
