### ISSUE TITLE
componentDidTransition

### ISSUE THREAD

**Issue by jmeas** [reactjs/react-transition-group#53]
**Do you want to request a *feature* or report a *bug*?**

Feature

**What is the current behavior?**

There are no callbacks when the transition ends.

**More detail**

Sometimes, you want to do something once an animation completes. I think it makes sense for this lib to provide this callback.

This was originally raised on the React repo here: https://github.com/facebook/react/issues/5914

And a PR was made here: https://github.com/facebook/react/pull/5915

I've been using a copypasta'd version of ReactTransitionGroup that adds this feature for a long time now, and it works great. I think the general approach is good; it just wasn't merged in because Facebook didn't want to maintain this lib (see https://github.com/facebook/react/issues/5914#issuecomment-228616321 )

For more on the justification, you can read the initial issue. But also you can imagine other cases where you might want to do some action after an animation completes.

**Comment by acusti** [comment]
I would also find this useful. Would the current maintainers be amenable to someone creating a new PR based on https://github.com/facebook/react/pull/5915 for this repo? If so, I’d be happy to do so.

**Comment by jquense** [comment]
The likely answer here is that this is covered by the proposed be API in #24 I'd check there and see if that works for your usecase

**Comment by acusti** [comment]
@jquense That’s exciting! The

```js
onEnter: PropTypes.func,
onEntering: PropTypes.func,
onEntered: PropTypes.func,

onExit: PropTypes.func,
onExiting: PropTypes.func,
onExited: PropTypes.func,
```

hooks on the `CSSTransition` component would definitely do the trick for me! @jmeas Are you able to tell from the PR description + files changed diff if #24 would be enough for your needs as well?

Related, should this issue stay open to track this particular need until that PR is merged, or should it be closed?

**Comment by jmeas** [comment]
It would. Thanks @jquense !

I'll close this issue out, then.
