### ISSUE TITLE
React.Children.only expected to receive a single React element child.

### ISSUE THREAD

**Issue by zhenjun115** [reactjs/react-transition-group#536]
here is my code: 
`import React from 'react';
import './Menu.css';
import { CSSTransition } from "react-transition-group";

class Menu extends React.Component {

    constructor( props ) {
        super( props );
        this.state = {
            'show': true
        };
    }

    toggle = () => {
        this.setState( prevState => ({
            'show': !prevState.show
        }))
    }

    render() {
        return (
            <ul className="Menu">
                <li onClick={this.toggle}>1
                    <CSSTransition
                        in={this.state.show}
                        timeout={400}
                        classNames="my-node"
                        key={1}
                    >
                        <div>
                            { "only"}
                        </div>
                    }
                    </CSSTransition>
                </li>
                <li>2</li>
                <li>3</li>
                <li>4</li>
            </ul>
        );
    }
}

export default Menu;`

here is error:
`React.Children.only expected to receive a single React element child.
./src/index.js
src/index.js:7

   4 | import App from './App';
   5 | import * as serviceWorker from './serviceWorker';
   6 | 
>  7 | ReactDOM.render(<App />, document.getElementById('root'));
   8 | 
   9 | // If you want your app to work offline and load faster, you can change
  10 | // unregister() to register() below. Note this comes with some pitfalls.

__webpack_require__
/Users/zhenjun/Documents/react_pgadmin/webpack/bootstrap:781

  778 | };
  779 | 
  780 | // Execute the module function
> 781 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  782 | 
  783 | // Flag the module as loaded
  784 | module.l = true;

fn
/Users/zhenjun/Documents/react_pgadmin/webpack/bootstrap:149

  146 | 		);
  147 | 		hotCurrentParents = [];
  148 | 	}
> 149 | 	return __webpack_require__(request);
      | ^  150 | };
  151 | var ObjectFactory = function ObjectFactory(name) {
  152 | 	return {`

**Comment by taion** [comment]
You're also passing in the `}` as a string after the `<div>`.

**Comment by zhenjun115** [comment]
sorry for my markdown, here is the link to my code.
https://github.com/zhenjun115/react_pgadmin/blob/master/src/Nav/Menu.js#L24-L34
I still do not know what's gonging wrong.

**Comment by BenQuirk** [comment]
@zhenjun115 have you tried putting a key into the li elements? I'm having the same issue as you, even though the key isn't solving the problem for me, but theoretically it looks like this might solve it for you. From the docs:

You must provide the key attribute for all children of ReactCSSTransitionGroup, even when only rendering a single item. This is how React will determine which children have entered, left, or stayed.
