### ISSUE TITLE
Difference in behaviour of TransitionGroup component

### ISSUE THREAD

**Issue by frankwallis** [reactjs/react-transition-group#54]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
When using TransitionGroup, calling the componentWillEnter callback in componentDidUpdate causes an undefined error. This does not happen with the original TransitionGroup from react-addons-transition-group, which means that react-transition-group; is not a *drop-in* replacement.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**
Can be seen in the example project in https://github.com/frankwallis/react-slidein (npm start). Pressing the toggle button before the animation has ended will trigger an exception when using the new TransitionGroup component.

**What is the expected behavior?**
The new TransitionGroup component should behave the same as the original TransitionGroup component. Calling the callback should terminate the animation and not error.

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
All versions in the new repository.

**Comment by jquense** [comment]
hi there, thanks for the report. can you provide a really simple reproduction of the error in the jsfiddle template so it's easier to troubleshoot, thanks!

**Comment by frankwallis** [comment]
I was not able to recreate it in jsfiddle, but I think that this issue is the same as #55 so I will try out the fix for that.

**Comment by frankwallis** [comment]
Confirmed that #56 fixes the issue so I will wait for that to land.
