### ISSUE TITLE
Ability to change scroll position between animations

### ISSUE THREAD

**Issue by ekfuhrmann** [reactjs/react-transition-group#566]
> What would you like improved?

I'm currently running into the problem that if I'm scrolled down my page, and then transition to a new page (via a simple fade), my site retains the prior page's scroll position.

Ideally I want it to be that current page fades out, window resets to top, and then new page fades in.

I tried to do this using `window.scrollTo(0,0)` and playing with a `setTimeout(() => {})`, but I could not get the timing to work consistently.

**Comment by nicbarker** [comment]
👀

**Comment by silvenon** [comment]
Depending on your setup and on when exactly you want the scrolling to happen, you can use `onEnter`/`onEntered` (or `onExit`/`onExited`) event handlers to do this.

I will close this issue because it's highly unlikely that it's an issue with react-transition-group, but if you provide a sample CodeSandbox, I will gladly show you how you can implement this.

**Comment by Keshavdulal** [comment]
Just Adding in an example of my case (NextJS + RTG)  for future references.
We wanted a simple fade-out-and-in transition while moving between internal pages.

Opposed to the OP's case, NextJS has default [scroll-restoration mechanism](https://nextjs.org/docs/migrating/from-react-router#scroll-restoration) which is great but was causing an issue when used with RTG.
Our current page would scroll to top first and only then the transition would kick in.

This wasn't we were looking after.
After fiddling around with for days,
-  we disabled `scroll` prop on every `Link` component and 
- added a manual scroll to top in `onEntered={() => window.scrollTo(0, 0)}` event handler of `Transition` Component of RTG.

The results were good.
