### ISSUE TITLE
SwitchTransition shows all routes and infinite loops with React Router

### ISSUE THREAD

**Issue by CliffWMiller** [reactjs/react-transition-group#569]
> What is the current behavior?

When you place a SwitchTransition in the suggested pattern for using CSSTransitions in React Router, all routes show at once and no transitions occur. If you do not put a key on the CSSTransition, you will get transitions in an infinite loop.

> What is the expected behavior?

One route plays an exit transition before the next enters with a transition ("out-in").

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

See: https://codesandbox.io/s/csstransition-react-router-lc6z9?fontsize=14
All I've done here is take the documented React Router example
- update React Transition Group to 4.3.0
- wrap the CSSTransition in a SwitchTransition
- apply a key to CSSTransition

To see the infinite loop, remove the key from CSSTransition and click one of the nav links to initiate.

**Comment by CliffWMiller** [comment]
So, I tried this with the TransitionGroup-Switch pattern used on the React Router documentation and it worked. See https://codesandbox.io/s/react-router-animated-transitions-nd9gl?fontsize=14

It seems this is more a problem with the pattern and documentation than perhaps the code. Based on the documentation, I'm not precisely sure why one pattern works and the other does not. In fact, according to the React Transition Group documentation, you should avoid using Switch.

**Comment by CliffWMiller** [comment]
After some time using the TransitionGroup-Switch pattern things seem mostly stable. 

However I am occasionally getting an infinite loop of Transition states entering and exiting, similar to what will happen in the first example I provided after removing the key on CSSTransition. 

If I can come up with a minimal example and consistent reproduction steps, I will provide them.  It seems like this loop primarily happens right after an ```npm start``` and possibly only on certain routes. Right now, we're only seeing this every once in a while.

**Comment by CliffWMiller** [comment]
I found steps to reproduce the infinite loop. It happens when manually changing routes by typing in the url as opposed to programmatically in the interface.

So, basically neither of these patterns are working if you want to use React Router and SwitchTransition together.

You can reproduce the infinite loop in the second TransitionGroup-Switch pattern here: https://codesandbox.io/s/react-router-animated-transitions-nd9gl?fontsize=14

Steps:

1. Navigate the example from Red to Green by pasting ```https://nd9gl.csb.app/hsl/120/100/40``` into the address bar. This'll actually happen outside the sandbox too if you just paste that link into your browser.

**Comment by CliffWMiller** [comment]
The problem turns out to be the same, React Router's example uses ```location.key``` for the Transition key. When you initially load the page using a url the key is ```undefined```. So, you end up with a Transition in your SwitchTransition without a key. You can work around that by giving a default if ```location.key``` is ```undefined```.  I'm not sure this is the best solution.

**Comment by laurencefass** [comment]
perhaps i misunderstand (new to react router)  but isnt use of the location the incorrect key and un-nestable? the location key updates for every new route so this is always going to re-render?

**Comment by silvenon** [comment]
I'm not very familiar with React Router either, but let's start with the first example: you're mapping every route to a separate `SwitchTransition`, instead you should have a single `SwitchTransition` with all routes inside, wrapped in `Switch`, like in your second example.

Now let's move to the 2nd example: I don't understand what is the idea behind using `TransitionGroup` here, this component should be used for animating the presence of its transition children, which is not the case here, `SwitchTransition` is not never being unmounted. I'm not sure what happens exactly when you nest a `CSSTransition` inside a `SwitchTransition` inside a `TransitionGroup`, but I'm not surprised that it's malfunctioning. If you just remove `TransitionGroup` I believe it works as expected.

Let me know if you have any more questions.

**Comment by swayok** [comment]
Just provide default `key`. This one worked for me:
```
<SwitchTransition mode="out-in">
    <CSSTransition
        key={location.key || location.pathname + location.search}
        classNames="page-switch"
        timeout={200}
    >
        <Switch location={location}>
            routes here
        </Switch>
    </CSSTransition>
</SwitchTransition>
```
