### ISSUE TITLE
Synchronize <CSSTransition timeout={500}> and transition: opacity 500ms ease-in;

### ISSUE THREAD

**Issue by ForeverYouth** [reactjs/react-transition-group#570]
So. What problem did i encounter? I wrote my component which take 3 parameters (animationType, animationDuration and children). I use TransitionGroup & CSSTransition like in [this example](https://reactcommunity.org/react-transition-group/transition-group). I would like adjust animation type and duration based on props. But! I cannot put prop animationDuration to css. I can control animationType by fabric and css styles. But a cannot control animationDuration(transition: 500ms || animation-duration: 500ms) in styles which i put from Parent component.
In [example which i reminded above](https://reactcommunity.org/react-transition-group/transition-group) you set duration in two separated places:
- `<CSSTransition timeout={500}>`;
- `transition: opacity 500ms ease-in`;
As for me it would be better if we could put 500 from 1 variable(props). But we cannot put animationDuration to CSS module :(

**Comment by taion** [comment]
You can export e.g. numbers and other values from CSS modules via `:export`

**Comment by ForeverYouth** [comment]
But i need export JS variable TO Css module because animationDuration comes from parent component;
