### ISSUE TITLE
React Router 5 example (with <switch>)  for nested routes.

### ISSUE THREAD

**Issue by laurencefass** [reactjs/react-transition-group#572]
> What is the current behavior?

I would like to use RTG with react router hooks 5.1+

http://reactcommunity.org/react-transition-group/with-react-router recommends not using switch and looks like a pre-hook example.  

Im a bit concerned using a solution advocating not using part of the core React router 5.1+ functionality. Are there any plans to integrate RR5.1 and RTG?

> What is the expected behavior?

Easy nested routing and animations with react router hooks integration. I am generally experiencing difficulties creating sub-route animations using React router and React Transition Group. 

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

none yet.

**Comment by CliffWMiller** [comment]
You might find some useful information here: https://github.com/reactjs/react-transition-group/issues/569

I went through some of the same issues. React Router's solution works despite the fact that it uses Switch: https://reacttraining.com/react-router/web/example/animated-transitions

You just have to be careful with your keying. I ended up using Transition/SwitchTransition at the Routing level and passing the state down to my components to be used in CSSTransitions.

Hope this helps.

**Comment by laurencefass** [comment]
I dont think the example works for nested transitions due to the use of location.key which updates on every re-route. Im trying to find a way of preventing re-renders on parent routes but that feels like a workaround to using of an incorrect choice of key.  Problem animation breaks with use of any other key.

**Comment by laurencefass** [comment]
all works fine with the switch example in official documentation only change required is to have a location key for each switch statement.

**Comment by bitshiftnetau** [comment]
@laurencefass I know this thread is a little old but are you provide an example of how you got this working? I am facing the same issue with nested routes using the transition group.
