### ISSUE TITLE
Use of SwitchTransition results in cross origin errors.

### ISSUE THREAD

**Issue by laurencefass** [reactjs/react-transition-group#573]
> What is the current behavior?

Use of <SwitchTransition> results in Error
`A cross-origin error was thrown. React doesn't have access to the actual error object in development. See https://fb.me/react-crossorigin-error for more information.
`
everywhere ive tried to use it.

> What is the expected behavior?

`<SwitchTransition>` just works

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

not yet.

**Comment by taion** [comment]
please provide a repro; this is more likely a bug in your code, given that switch transition itself doesn't try to do anything cross-origin
