### ISSUE TITLE
useRouteMatch breaks the "with react router" example on reactcommunity.org

### ISSUE THREAD

**Issue by laurencefass** [reactjs/react-transition-group#574]
> What is the current behavior?

I have forked the example at: http://reactcommunity.org/react-transition-group/with-react-router
Navigation breaks if upgrade to react router 5.1.2 and introduce hooks. 

Test

I added   const { path, url } = useRouteMatch() to the contact component.  this is the only change to the example and it navigation and history from this component.

```
import React from 'react'
import { useRouteMatch, useLocation } from 'react-router-dom'

function Contact() {
  const { path, url } = useRouteMatch()
  return (
    <>
      <h1>Contact</h1>
      <p>
        Aliquam iaculis a nisi sed ornare. Sed venenatis tellus vel consequat
        congue. In bibendum vestibulum orci et feugiat.
      </p>
    </>
  )
}
```

result: 

i can navigate freely between home and about but when i navigate away from the contact page is see error:

```
The above error occurred in the <Contact> component:
    in Contact (at src/index.js:47)
    in div (at src/index.js:46)
    in Transition (created by CSSTransition)
    in CSSTransition (at src/index.js:40)
    in Route (at src/index.js:38)
    in div (created by Container)
    in Container (at src/index.js:36)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:19)
    in Example (at src/index.js:60)
```
> What is the expected behavior?

I expect the modified example's routing to navigate without errors after upgrading to react router 5.1.2 and adding a hook to one of the sample pages. 

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

**https://codesandbox.io/s/csstransition-react-router-1q6qv**

**Comment by taion** [comment]
This is just a bug in your code. Once you navigate away, that route is no longer matched, so you can see that the hook is returning null, presumably as intended. You'd need to memoize that value or something.

**Comment by laurencefass** [comment]
i'm not accessing the hook when i navigate away. ?

**Comment by taion** [comment]
the component is still mounted, so it's still rendering and accessing the hook

**Comment by laurencefass** [comment]
Sorry if my questions appear ignorant I am trying to make sense how this works...

The CSSComponent wrapper has unmountOnExit set so why is it not unmounting?

**Comment by YungGabriel** [comment]
Ran across  the same issue. Did you find a solution?
