### ISSUE TITLE
TypeScript: Timeout prop is still mandatory while addEndListener is in use

### ISSUE THREAD

**Issue by Ronny25** [reactjs/react-transition-group#575]
# Timeout prop is still mandatory while addEndListener is in use in TypeScript

## Expected behaviour
- **timeout** prop shouldn't be required when **addEndListener** is used. According to docs.

## Actual behaviour
- **timeout** prop is always required

**Comment by lennerd** [comment]
Experienced the same. Any ideas how this could be solved?

**Comment by chpio** [comment]
would something like this work:
```typescript
{addEndListener: () -> void, timeout?: number} | {timeout: number}
```

also making it optional in `CSSTransition`

**Comment by sburba** [comment]
I've made this PR to support an optional timeout when addEndListener is specified:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42596

Unfortunately I think it's a breaking change due to how the union type is defined, so I'm not sure the best way to handle that.

**Comment by sburba** [comment]
DefinitelyTyped/DefinitelyTyped#42596 has merged. So update your types and timeout should now be optional if addEndListener is specified

**Comment by veles212** [comment]
after this type change addEventListener became a required parameter, although it should not be
