### ISSUE TITLE
Get HTMLDomNode of created component

### ISSUE THREAD

**Issue by SvanBoxel** [reactjs/react-transition-group#58]
Not sure whether this is a bug, a feature request or I am doing something completely wrong.

If I would like to get the node reference of a create element, I would use a ref callback like this:

```
return <div ref={node => this.parent = node}>
 <span> foo! </span>
</div>
  }
```
`this.node `returns the correct HTMLDivElement.

However, if I would like to get the reference to the div create by TransitionGroup, it returns the component (`ReactTransitionGroup`) itself, instead of the created HTMLDivElement.

      return <TransitionGroup ref={node => this.node = node} component="div" transitionName="foobar" className="foo">
      {component}
      {bubble}
    </TransitionGroup>;

I would like to get access to the HTMLDivElement created by TransitionGroup itself without using ReactDOM. It this even possible?

**Comment by jquense** [comment]
It's not not, that's how refs work on components. I'd use findDOMNode, that's what it's for :)
