### ISSUE TITLE
Importing CSSTransition fails 

### ISSUE THREAD

**Issue by manusiddhartha** [reactjs/react-transition-group#586]
Hi,

I understand this question has been asked before. 

However, the offered suggestion of re-compiling the project in Visual Studio hasn't worked for me, and any help is greatly appreciated. 

Installed react-transition-group using NPM (_npm isntall react-transition-group --save-dev_) 
and am importing CSSTransition as follows: 

_import { CSSTransition } from 'react-transition-group'_

This seems to fail with the following message - 

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Dev dependencies on package.json are:

_"@babel/core": "^7.8.3",
"@babel/polyfill" : "^7.8.3",
"@babel/preset-env" : "^7.8.3",
"@babel/preset-react" : "^7.8.3",
"babel-loader" : "^8.0.6",
"es6-promise" : "^4.2.8",
"react" : "^16.12.0",
"react-dom" : "^16.12.0",
"react-transition-group": "^4.3.0",
"webpack" : "^4.41.5",
"webpack-cli": "^3.3.10"_

And the import occurs here  - 

_import "@babel/polyfill";_
_import React from "react";_
_import { render as Render } from "react-dom";_
_import {CSSTransition} from "react-transition-group";_

_function app() {_ 
_return (_
_<CSSTransition in={inProp} timeout={200} classNames="my-node"><div>test</div>__</CSSTransition>_
_)
}_

_Render(app(), document.getElementById("root");_

**Comment by taion** [comment]
Please provide a runnable example in e.g. a CodeSandbox.
