### ISSUE TITLE
React.createContext(null) is not a function

### ISSUE THREAD

**Issue by nitinsharmacs** [reactjs/react-transition-group#594]
i'm trying to use transitions using "react-transition-group" package but the following error is coming 

TypeError: __WEBPACK_IMPORTED_MODULE_0_react___default.a.createContext is not a function
![error](https://user-images.githubusercontent.com/48169425/76055600-1af3a980-5f9a-11ea-88ec-5084bc8269a6.jpg)

My code is following:

import React, { Component } from "react";

import "./App.css";
import Modal from "./components/Modal/Modal";
import Backdrop from "./components/Backdrop/Backdrop";
import List from "./components/List/List";
import {Transition} from "react-transition-group";

class App extends Component {
  state = {
    modalIsOpen: false
  }

  showModal = () => {
    this.setState({modalIsOpen: true});
  }

  closeModal = () => {
    this.setState({modalIsOpen: false});
  }
	componentDidMount(){
	console.log(Transition)
	}
  render() {
    return (
      <div className="App">
        <h1>React Animations</h1>
        <Transition in={true} timeout={1000}>
        	{state => <p>state</p>}
        </Transition>
        <Modal show={this.state.modalIsOpen} closed={this.closeModal}/>
        <Backdrop show={this.state.modalIsOpen} />
        <button className="Button" onClick={this.showModal}>Open Modal</button>
        <h3>Animating Lists</h3>
        <List />
      </div>
    );
  }
}

export default App;

**Comment by taion** [comment]
You need to update your version of React.
