### ISSUE TITLE
componentWillEnter、componentDidEnter not working

### ISSUE THREAD

**Issue by lemonleon** [reactjs/react-transition-group#60]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

i want  before and after ReactCSSTransitionGroup run a function, but only  componentWillAppear、componentDidAppear run, componentWillEnter、componentDidEnter、componentWillLeave、componentDidLeave not working. 

this is my code

``` javascript

import React, { Component, Children } from 'react';
import ReactCSSTransitionGroup from 'react-addons-css-transition-group';
import TransitionGroup from 'react-transition-group/TransitionGroup';
import ReactDOM from 'react-dom';

class TestAnimation extends Component {
    state = {
        color: ['red', 'blue', 'yellow'],
        active: 0
    }
    componentDidMount() {
        let i = 0;
        setInterval(function (){
            i = (i+1)%3;
            this.setState({
                active: i
            });
        }.bind(this), 3000);
    }
    render() {
        let {color, active} = this.state;
        return (
            <div className='content'>
                <ReactCSSTransitionGroup transitionName='fade' transitionEnterTimeout={1300} transitionLeaveTimeout={1300}>
                    <TransitionGroup key={active}>  // if delete key={active} all of component function will run, but it a wrong effect.
                        <TransitionGroupUl color={color} active={active} key={active}/>
                    </TransitionGroup>
                </ReactCSSTransitionGroup>

            </div> 
        );
    }
}

class TransitionGroupUl extends Component{
    componentWillAppear() {
        console.log(1,'componentWillAppear');
    }
    componentDidAppear() {
        console.log(2,'componentDidAppear');
    }
    componentWillEnter() {
        console.log(3,'componentWillEnter');
    }
    componentDidEnter() {
        console.log(4,'componentDidEnter');
    }
    componentWillLeave() {
        console.log(5, 'componentWillLeave');
    }
    componentDidLeave() {
        console.log(6, 'componentDidLeave');
    }
    render() {
        return (
            <div style={{background: this.props.color[this.props.active]}} key={this.props.active}></div> 
        );
    }
}

ReactDOM.render(
    <TestAnimation />,
    document.getElementById('app')
);

```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**

**What is the expected behavior?**

i just hope: `before and after the transition effect run a function`, what should i do?

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

**Comment by humanPursuit** [comment]
same issue, react-with-addons v0.14.8
our child component is wrapped by build in Component `ReactCSSTransitionGroupChild`,  our hooks can't pass to new instance. so is there any idea to solve this ?

**Comment by jquense** [comment]
I'm not sure what the bug report here is for, we don't provide support for the older versions of React.Addons, and can't backport any fixes to those. IF you are looking for a component replacement for the addons, use v1 of react-transition-group. Ideally though I would upgrade to v2 and the new API which is more flexible and addresses a bunch of the flaws in older versions
