### ISSUE TITLE
Where to put conditional rendering in the transition JSX?

### ISSUE THREAD

**Issue by ilyador** [reactjs/react-transition-group#600]
I am trying to have 2 components mutually exclusive, and seems like putting `condition &&` anywhere in the JSX removes them without triggering an animation.

This is the original:

```jsx
<Transition in={loading} timeout={duration}>
  {state => (
    <div style={{ ...defaultStyle, ...transitionStyles[state] }}>
      <SyncIcon className={c.loadingIcon} />
    </div>
  )}
</Transition>
<Transition in={success} timeout={duration}>
  {state => (
    <div style={{ ...defaultStyle, ...transitionStyles[state] }}>
      <SuccessIcon className={c.successIcon} />
    </div>
  )}
</Transition>
```

The condition is `loading`, I tried
```jsx
<Transition in={loading} timeout={duration}>
  {state => (
    loading && <div style={{ ...defaultStyle, ...transitionStyles[state] }}>
      <SyncIcon className={c.loadingIcon} />
    </div>
  )}
</Transition>
```
and
```jsx
<Transition in={loading} timeout={duration}>
  {state => (
    <div style={{ ...defaultStyle, ...transitionStyles[state] }}>
      {loading &&  <SyncIcon className={c.loadingIcon} />}
    </div>
  )}
</Transition>
```
In bot cases, once `loaing` was false, the item disappeared without anumation. The enter animation worked though.

**Comment by taion** [comment]
if you have multiple components that you need to fade in or out, use transition group; alternatively, use switch transition

single transitions are to manage an individual component fading in or out; it doesn't handle this use case
