### ISSUE TITLE
New mode for SwitchTransition - `in-out-at-once`

### ISSUE THREAD

**Issue by jtomaszewski** [reactjs/react-transition-group#601]
Currently `SwitchTransition` has only [two modes](https://github.com/reactjs/react-transition-group/blob/cfd0070765d631112c5da817cef82742566d2ed0/src/SwitchTransition.js#L78-L79):

>  * If the `out-in` mode is selected, the `SwitchTransition` waits until the old child leaves and then inserts a new child.
>  * If the `in-out` mode is selected, the `SwitchTransition` inserts a new child first, waits for the new child to enter and then removes the old child

What I'd like to have, is: "insert a new child first, animate both old and new child at once, and then remove the old child".

What do you think? I could make a PR for that.

**Comment by taion** [comment]
You don't need `<SwitchTransition>` for that. That's just the behavior you'd get if you used a normal `<TransitionGroup>`.

**Comment by jtomaszewski** [comment]
Thanks, you're right. Somehow I haven't thought about this. Maybe I'll suggest some small PR with an update to the documentation instead.
