### ISSUE TITLE
ng-animate link in css-transition doc page leads to an unsafe page

### ISSUE THREAD

**Issue by paulintrognon** [reactjs/react-transition-group#603]
In this page: https://reactcommunity.org/react-transition-group/css-transition
the link on ng-animate leads to a website (www.nganimate.org) marked as fraudulent[1] 

Maybe it should point to this site instead? https://docs.angularjs.org/api/ngAnimate

[1] https://transparencyreport.google.com/safe-browsing/search?url=http:%2F%2Fnganimate.org%2F

**Comment by jquense** [comment]
sounds good wanna send over a PR changing it?

**Comment by paulintrognon** [comment]
ok i'm on it
