### ISSUE TITLE
Using TransitionGroup & useEffect to animate / transition a single child in and out at the same time. 

### ISSUE THREAD

**Issue by rey-wright** [reactjs/react-transition-group#607]
So I'm having a lot of trouble figuring out if it's even possible to animate out a child with TransitionGroup, when the id for CSSTransition is being generated inside of a useEffect.

If you click on the button, and then click on the blue square, you will see that a new purple square is coming in, and the blue square is supposed to leave. However if you look closely, you will see that the blue square as it's leaving turns purple. I'd like it to stay the same.

Any ideas?

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

https://codesandbox.io/s/optimistic-stallman-d3f0b

**Comment by taion** [comment]
Not the way you write it. You need to change the key before or at the same time as you change the color. If you're doing it in `useEffect` there, then it's too late – you've already changed the color of the component _before_ you've marked it as hidden.
