### ISSUE TITLE
Add `withTransitions` Higher Order Component

### ISSUE THREAD

**Issue by josepot** [reactjs/react-transition-group#61]
**Do you want to request a *feature* or report a *bug*?**

I would like to request a new *feature*.

**What is the current behavior?**

The current behavior is awesome.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**

It's not a bug.

**What is the expected behavior?**

To have a HOC with named `withTransitions` (or something like that). It could be very useful for projects using css-in-js libraries.

I just published [this library](https://github.com/josepot/react-with-transitions) and then it occurred to me that perhaps it would be worth it to add a HOC like that one to the `react-transition-group` library.

If you like that idea I wouldn't mind sending a PR for that.

A fancy usage of that HOC could be:

```js
import R from 'ramda';
import { compose, mapProps } from 'recompose';
import { styled } from 'styletron-react';
import { withTransitions } from 'react-transition-group';

const withStyles = styles => Component => styled(Component, styles);

export const HoverBox = compose(
  withTransitions(R.propEq('isHovering', true), 200),
  withStyles(({ transitionState }) => {
    const [opacity, top] = transitionState === 'NORMAL'
      ? [1, '10px']
      : [0, '15px'];
    return {
      padding: '10px',
      position: 'absolute',
      width: '83%',
      right: '0',
      opacity,
      top,
      transition: 'all 0.2s ease',
    };
  }),
  mapProps(R.omit(['transitionState', 'isHovering']))
)(`div`);
```

**Comment by InventingWithMonster** [comment]
```
import React from 'react';

export default function addLifecycleTransitions({
  componentWillAppear,
  componentDidAppear,
  componentWillEnter,
  componentDidEnter,
  componentWillLeave,
  componentDidLeave
}) {
  return function createComponentWithTransitions(Component) {
    class ComponentWithTransitions extends React.Component {
      componentWillAppear(...args) {
        if (componentWillAppear) componentWillAppear.call(this, ...args);
      }

      componentDidAppear() {
        if (componentDidAppear) componentDidAppear.call(this);
      }

      componentWillEnter(...args) {
        if (componentWillEnter) componentWillEnter.call(this, ...args);
      }

      componentDidEnter() {
        if (componentDidEnter) componentDidEnter.call(this);
      }

      componentWillLeave(...args) {
        if (componentWillLeave) componentWillLeave.call(this, ...args);
      }

      componentDidLeave() {
        if (componentDidLeave) componentDidLeave.call(this);
      }

      render() {
        return (
          <Component {...this.props} />
        );
      }
    }

    return ComponentWithTransitions;
  };
}
```

**Comment by jquense** [comment]
in v2 this should be easier to write with Transition being a bit more declarative and not relying on static methods. I think we can close this for now since it's easy enough to write something specific to your needs, but harder to get the general case right.
