### ISSUE TITLE
Appear animation not firing correctly in SSR

### ISSUE THREAD

**Issue by lifeiscontent** [reactjs/react-transition-group#614]
> What is the current behavior?

currently it doesn't seem like there is a way to animate a component with the `mountOnEnter` and `unmountOnExit` props

> What is the expected behavior?

I'd expect a way to be able to animate components on mount

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

https://codesandbox.io/s/hello-world-nvjwn?file=/pages/index.js

**Comment by silvenon** [comment]
I'm not sure why you closed the issue. `appear` only works if both `appear` and `in` are initially set to `true`, in your case they are _both_ `false` so there is no enter animation. If you set them both initially to `true` (when calling `React.useState`) you can see the enter animation. 😉
