### ISSUE TITLE
Nested CssTransition

### ISSUE THREAD

**Issue by Vanguardo66** [reactjs/react-transition-group#615]
> What is the current behavior?

The inner transition seem to not work as it has a slide effect but will enter just like the outer one (Fades in).

> What is the expected behavior?

The inner transition should slide.

> Reproducing the issue:

Here is the [Sandbox](https://1gevi.csb.app/) of the nested transitions.

**Comment by taion** [comment]
Take a look at the nested transition example in our Storybook. Both transitions fire simultaneously, so it works as expected

**Comment by yes1am** [comment]
@Vanguardo66 

try add appear in you nest CSSTransition

i find below code in the nested transition example, pay attention to the comments
```js
<CSSTransition timeout={FADE_TIMEOUT} unmountOnExit in={showNested} classNames={styles2}>
  <div>
    <div>I will fade</div>
    {/*
        We also want to scale in at the same time so we pass the `in` state here as well, so it enters
        at the same time as the Fade.

        Note also the `appear` since the Fade will happen when the item mounts, the Scale transition
        will mount at the same time as the div we want to scale, so we need to tell it to animate as
        it _appears_.
    */}
    <CSSTransition timeout={SCALE_TIMEOUT} appear in={showNested} classNames={styles1}>
      <div>I should scale</div>
    </CSSTransition>
  </div>
</CSSTransition>
```
