### ISSUE TITLE
Package cannot  be installed using yarn

### ISSUE THREAD

**Issue by jhefreyzz** [reactjs/react-transition-group#617]
When installing `react-transition-group` using yarn, the installation cannot be completed because an error occurred .  I try removing the node_modules and reinstalling the dependencies but still it does not work.

> What is the current behavior?
```
➜  client git:(master) ✗ yarn add react-transition-group
yarn add v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@babel/plugin-proposal-className-properties/-/plugin-proposal-className-properties-7.8.3.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/hei/projects/kaiwa/client/yarn-error.log".
```

> What is the expected behavior?

The package should be installed without error.

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

 Uses create-react-app generator.

**Comment by ferdaber** [comment]
It looks like this is an issue with the registry being unable to install babel, so this is unrelated to this package.
