### ISSUE TITLE
Nested Transitions with React Router

### ISSUE THREAD

**Issue by laurencefass** [reactjs/react-transition-group#625]
Nested transitions dont appear to work in an intuitive manner using TransitionGroup and CSSTransition and there are lots of open threads on various forums with no answers and no guidance in your documentation.

example here: the outer route classnames override inner route so not working as expected.

https://codesandbox.io/s/react-router-animated-transitions-lihls?file=/example.js:2437-2438

Are nested routes supported as a first class feature? Im not finding much help online. If so it would be great to see some documentation on how to do it.

thanks

**Comment by laurencefass** [comment]
solved by adding a key per component and refreshing it on Link clicks. The default example using the using location.pathname is not very useful for beginners or nested component trees.

**Comment by JulsRicketti** [comment]
@laurencefass I know this thread is almost a year old, but it seems like I am having essentially the same issue (see full issue on #713)

Unfortunately the solution that worked for you, doesn't do much for me, unless I misunderstand it. You say to add a key per component, so in my case for this [sandbox](https://codesandbox.io/s/nostalgic-smoke-w4mok?file=/src/pages/about.js), would it be something like the following?

```javascript
function Example () {
  const { params } = useRouteMatch() || {}
  const history = useHistory()

  return (
    <>
    [EXAMPLE]

      <button onClick={() => history.push('/example/[someOtherNestedRoute]')}>Change Routes</button>

      <Route path="/example/:nestedId">
        {({ location }) => {
          const { pathname } = location
          return (
            <CSSTransition
              in={pathname.includes(params?.nestedId)}
              timeout={500}
              classNames="nested-animation"
              mountOnEnter
              unmountOnExit
            >
              <div className="nested-animation" key={params?.nestedId or something unique?}>
                <h3>Current Nested Route: {params?.nestedId}</h3>
              </div>
            </CSSTransition>
          )
        }}
      </Route>
    </>
  )
}
```

See especifically the div:

> <div className="nested-animation" key={params?.nestedId or something unique?}>

Anyway, as mentioned above, this unfortunately does nothing, so just wanted to double check if I am applying the solution correctly.
