### ISSUE TITLE
findDOMNode is depreciated. Use a ref instead.

### ISSUE THREAD

**Issue by bluefire2121** [reactjs/react-transition-group#628]
> What is the current behavior?
When using React.StrictMode, a warning appears that indicates findDOMNode is depreciated.

> What is the expected behavior?
The expected behavior is the error/warning doesn't exists. Facebook recommends adding a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?
With Material-UI, place <App /> inside <React.Strict /> and include a <Drawer></Drawer/> component or any component that utilizes a transition (since Material-UI transitions are based on react-transition-group).

**Comment by bluefire2121** [comment]
![image](https://user-images.githubusercontent.com/4358275/82158076-4caaab80-983a-11ea-8275-5f017cb89a55.png)

Added screenshot of error

**Comment by jquense** [comment]
please search before opening new issues, thanks!

**Comment by bluefire2121** [comment]
Please link to the duplicate prior to closing issue
