### ISSUE TITLE
"../../node_modules/@types/react-transition-group"' has no exported member 'CSSTransitionGroup'

### ISSUE THREAD

**Issue by hansifer** [reactjs/react-transition-group#632]
> What is the current behavior?

When npm installing this lib as per readme and importing as follows:

`import { CSSTransitionGroup } from 'react-transition-group'`

The build produces the error

`Module '"../../node_modules/@types/react-transition-group"' has no exported member 'CSSTransitionGroup'`

> What is the expected behavior?

build without error when following readme instructions.

**Comment by hansifer** [comment]
Fixed by using current version instead (react documentation links to old version).

**Comment by kahlan88** [comment]
> Fixed by using current version instead (react documentation links to old version).

I just ran a fresh install and this still happens in v1 stable?
