### ISSUE TITLE
TransitionGroup example not working.

### ISSUE THREAD

**Issue by vince1995** [reactjs/react-transition-group#633]
> What is the current behavior?
 
The example on https://reactcommunity.org/react-transition-group/transition-group doesn't work.

**Comment by pxwee5** [comment]
Does not work on CSSTransition as well.

**Comment by w3bdesign** [comment]
@vince1995 

What browser are you using?

Make sure you are using the latest version of a modern browser like Firefox or Chrome.

**Comment by mcgaffin** [comment]
I've just started using `react-transition-group` and discovered the same thing when I tried to figure out why that sample works in codesandbox, but very similar code in my project fails. It looks like the demo is based on `react-transition-group@2.7.0`. The current version is `4.4.1`. The demo uses `<CSSTransition>` which is no longer available in the current version. 

I'm still trying to get things working in my project, but I believe this is why it's not working as expected for you.

**Comment by vince1995** [comment]
I'm using latest Chrome and FF. But it's working now.
