### ISSUE TITLE
Update comments on `reflowAndAddClass`

### ISSUE THREAD

**Issue by stephenlin35** [reactjs/react-transition-group#634]
> What would you like improved?

Hi, I'm currently using this library for a project. I was browsing through https://reactcommunity.org/react-transition-group/css-transition and followed a link to learn more on how CSSTransition `forces a reflow`. It seems one of the comments description says `This is for to force a repaint`

Screenshot:
<img width="903" alt="Screen Shot 2020-06-03 at 9 28 21 AM" src="https://user-images.githubusercontent.com/12617861/83642271-9d314100-a57c-11ea-97ea-d6e611e70793.png">

I think it would be more clear if we removed `for` so the comment became `This is to force a repaint...` instead.

If this is a valid reason to change, can I tackle this? It would be a great first OS contribution for me 👍 .

**Comment by jquense** [comment]
sure , that's a good change. Go for it 👍
