### ISSUE TITLE
Can not use Transition component in strict mode

### ISSUE THREAD

**Issue by shotikot** [reactjs/react-transition-group#642]
I'm trying to smoothly route between pages(components) using Transition component but I get this error

>Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference.

**Comment by taion** [comment]
use the new `nodeRef` functionality from 4.4: https://github.com/reactjs/react-transition-group/blob/master/CHANGELOG.md#features
