### ISSUE TITLE
Error using with Typescript

### ISSUE THREAD

**Issue by adarshaacharya** [reactjs/react-transition-group#659]
As per  [version 4.4.0](https://github.com/reactjs/react-transition-group/blob/master/CHANGELOG.md#features)
we can ref to DOM node using `nodeRef`. But when I tried to use it with Typescript it gives the following error.

```ts
Type '{ ref: MutableRefObject<null>; post: IPost; }' is not assignable to type 'IntrinsicAttributes & Props & { children?: ReactNode; }'.

  Property 'ref' does not exist on type 'IntrinsicAttributes & Props & { children?: ReactNode; }
```

Code looks something like this :+1: 

```ts
const nodeRef = React.useRef(null);

return (
    <>
        <TransitionGroup>
            posts.map((post) => (
                      <CSSTransition key={post._id} timeout={500} classNames='item'>
                          <PostItem post={post} ref={nodeRef} />
                      </CSSTransition>
                  ))
        </TransitionGroup>
    </>
)
```

**Comment by jquense** [comment]
does your `PostItem` component accept a ref?

**Comment by adarshaacharya** [comment]
@jquense Yeah it does.
it's something like this.

```ts
type Props = {
    ref: React.Ref<HTMLDivElement>;
};

const PostItem: React.FC<Props> = React.forwardRef(( ref) => {

    return (
        <>
            <div className='post__item' ref ={ref}>
                        Post item...
            </div>
           
        </>
    );
});
```

Now it doesn't show wrror but dom nodes aren't showing after searching post item. Have i done some mistake ? Especially I've not used forwardRef that much.

**Comment by jquense** [comment]
it looks like its wrong yes. I would suggest reading hte React docs for how to use it correctly. It doesn't seem like this an issue with React-bootstrap though
