### ISSUE TITLE
Classes not applying with Portal

### ISSUE THREAD

**Issue by qasimalyas** [reactjs/react-transition-group#660]
> What is the current behavior?

Current behavior is that transition classes aren't being applied in use with createPortal.

> What is the expected behavior?

The expected behavior is that transition classes are applied when an element is added to the DOM with createPortal.

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

Demo is here https://codesandbox.io/s/hidden-water-n6qec

Ideally, my aim is to append an element to the DOM via portal and animate it.  Are there any know examples with portals? I've had the same struggles with `Transitions` as well.

**Comment by HelloAny** [comment]
The principle of `react-transition-group` is dependent on the `life cycle` of the component. I guess it may not be possible to use `createPortal` to generate a complete component, so rendering operations cannot be performed.
