### ISSUE TITLE
CSSTransition using findDOMNode which is deprecated in React 16.13.1

### ISSUE THREAD

**Issue by david-forster10** [reactjs/react-transition-group#668]
A warning regarding the deprecation of findDOMNode is shown when using the SwitchTransition & CSSTransition in Strict mode (React v16.13.1).

> What is the current behaviour?

`Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://fb.me/react-strict-mode-find-node`

> What is the expected behavior?

No console messages

> Could you provide a CodeSandbox demo reproducing the bug?

Can be recreated using the demo sandbox and changing the React version to 16.13.1.
![Screenshot (7)](https://user-images.githubusercontent.com/26306667/92927016-d9562680-f434-11ea-8c3c-95cef99df46d.png)

**Comment by mznet** [comment]
@david-forster10 [Version 4.4.0](https://github.com/reactjs/react-transition-group/releases/tag/v4.4.0) have already resolved using `findDOMNode`.

**Comment by david-forster10** [comment]
@mznet Running on the same CodeSandbox, v4.4.0 same result
![Screenshot (8)](https://user-images.githubusercontent.com/26306667/93205011-fea5a600-f74e-11ea-95ed-1aea9de3bace.png)

**Comment by david-forster10** [comment]
Looking at the stack trace, the issue is actually occurring at the Transition object which is created by the CSSTransition. There are 3 references to the findDOMNode method still in that file:

[Line 229](https://github.com/reactjs/react-transition-group/blob/c3caa7ae111c24169c6b4c735caadb19fb5c942b/src/Transition.js#L229)

[Line 260](https://github.com/reactjs/react-transition-group/blob/c3caa7ae111c24169c6b4c735caadb19fb5c942b/src/Transition.js#L260)

[Line 321](https://github.com/reactjs/react-transition-group/blob/c3caa7ae111c24169c6b4c735caadb19fb5c942b/src/Transition.js#L321)

**Comment by david-forster10** [comment]
> Looking at the stack trace, the issue is actually occurring at the Transition object which is created by the CSSTransition. There are 3 references to the findDOMNode method still in that file:
> 
> [Line 229](https://github.com/reactjs/react-transition-group/blob/c3caa7ae111c24169c6b4c735caadb19fb5c942b/src/Transition.js#L229)
> 
> [Line 260](https://github.com/reactjs/react-transition-group/blob/c3caa7ae111c24169c6b4c735caadb19fb5c942b/src/Transition.js#L260)
> 
> [Line 321](https://github.com/reactjs/react-transition-group/blob/c3caa7ae111c24169c6b4c735caadb19fb5c942b/src/Transition.js#L321)

Adding in some cheap logging to find out where in the flow the error is thrown... I would guess it's [Line 229](https://github.com/reactjs/react-transition-group/blob/c3caa7ae111c24169c6b4c735caadb19fb5c942b/src/Transition.js#L229) as the error is thrown before the transitions finish.

![Screenshot (9)](https://user-images.githubusercontent.com/26306667/93206281-08300d80-f751-11ea-8a4c-dd7ff1a7789d.png)

**Comment by nt4f04uNd** [comment]
I'm just wondering why tf would close the issue #429 when it is not resolved even with 4.4.1? 
![image](https://user-images.githubusercontent.com/39104740/93463030-d5704b80-f8ef-11ea-8161-3f54120258d5.png)

**Comment by pixel-fixer** [comment]
From 4.4.0 release notes:
> react-transition-group internally uses findDOMNode, which is deprecated and produces warnings in Strict Mode, so now you can optionally pass nodeRef to Transition and CSSTransition, it's a ref object that should point to the transitioning child:

You can fix this like this
```
import React from "react"
import { CSSTransition } from "react-transition-group"

const MyComponent = () => {
  const nodeRef = React.useRef(null)
  return (
    <CSSTransition nodeRef={nodeRef} in timeout={200} classNames="fade">
      <div ref={nodeRef}>Fade</div>
    </CSSTransition>
  )
}
```

**Comment by nt4f04uNd** [comment]
I think the library must show it's own warning about this and not confuse people and make them search for the solution by themselves

**Comment by david-forster10** [comment]
I think to also avoid confusion, the demos (using the older version of the library) need to be updated to show the use of the refs to further reinforce the idea for people who skim the docs

**Comment by nt4f04uNd** [comment]
@jquense please consider or suggestion

**Comment by ahmedzubaca** [comment]
The solution proposed by @jquense removes warning, but also prevents animation to play.

**Comment by Samk13** [comment]
the solution of @pixel-fixer works for me, but when adding `ref ` to a complex child component it will not work, you need to wrap your complex component with a div then the transition will play with no errors🙌🏼.
`<Transition nodeRef={nodeRef} key={id} timeout={{ enter: 800, exit: 500 }}>
    <div ref={nodeRef}>   👈🏼
       <CardItem/>
     </div>
 </Transition>`

**Comment by ahmedzubaca** [comment]
Smak13, thank You so much, this works for me, too.

**Comment by Szlavicsek** [comment]
Thanks Smak13, it works. What a shame this library needs hacks like this...

**Comment by italodom** [comment]
Thanks @Samk13 🙌🏼

**Comment by dziul** [comment]
Erro continua. usando `react-router-dom`,  [example on the React Router website](https://reactrouter.com/web/example/animated-transitions).

my code: 

```html
<TransitionGroup>
          <CSSTransition key={location.key} timeout={300} nodeRef={nodeRefTransition}>
            <div ref={nodeRefTransition}>
              <Switch location={location}>
                <Route path='/' exact component={UploadComponent} />
                <Route path='*'>
                  <Redirect to='/' />
                </Route>
              </Switch>
            </div>
          </CSSTransition>
        </TransitionGroup>
```

![image](https://user-images.githubusercontent.com/19353873/123489421-4f083900-d5e8-11eb-976f-4fce8afca5b9.png)

**Comment by nguyentran-se** [comment]
thanks a lot @pixel-fixer. This works for me!

**Comment by emkayy** [comment]
@jquense Why is this closed? The "fix" from pixel-fixer is not a fix but a workaround, that doesn't work in all cases (e.g. it breaks the animation for me and other developers as you can read above). It's also not fixed in 4.4.2
Please re-open

**Comment by talkenson** [comment]
Not fixed, when I add 
![image](https://user-images.githubusercontent.com/24260024/128917656-4b8cf820-4072-4c85-a250-59fa67fdd163.png)

I got something like a piece of unknown

![image](https://user-images.githubusercontent.com/24260024/128917785-b2c7b536-f84d-4bb8-99d1-f2fc55ab0c4f.png)

It slides or pops up without applying exit animations

**Comment by jiaxfrank** [comment]
@talkenson Is it possibly because there is styling on that div with the ref? I tried "w-full h-full" given 100vw and 100vh respectively on my own app, it looked something like yours.

**Comment by aswanevelder** [comment]
Jip, this does not work, the nodeRef just removes the animation.

**Comment by Wesselvdp** [comment]
One caveat of using `nodeRef` as a prop, is that `node` is no longer passed to the callback functions. [It's explained here in the docs](http://reactcommunity.org/react-transition-group/transition#Transition-props)

@khan94, this might explain your error.

Example:
```Typescript
// not using nodeRef
const onEnter = (node: HTMLDivElement) => {
	// do something with node
}
// Using nodeRef
const nodeRef = useRef<HTMLDivElement>(null)
const onEnter = () => {
	const node = nodeRef.current
	// do something with node
}
```

**Comment by quynt-anrakutei** [comment]
doesn't work when I try with SwitchTransition
```
  return (
    <SwitchTransition mode={"out-in"}>
      <CSSTransition
        nodeRef={nodeRef}
        key={currentCategoryCode}
        addEndListener={(done) => {
          nodeRef.current?.addEventListener("transitionend", done, false);
        }}
        classNames="fade"
      >
        <div ref={nodeRef}>
          <div
            id="menu-list"
            data-swipe-threshold="20"
            data-swipe-timeout="1000"
            data-swipe-ignore="false"
            ref={menuListDiv}
          >
            {ListOfGenres}
          </div>
        </div>
      </CSSTransition>
    </SwitchTransition>
  );
}

```

**Comment by sakkelaaksonen-siili** [comment]
Please fix this and provide a clear instructions for using nodeRefs

**Comment by rattkin** [comment]
Is it possible to do this ref trick with `SwitchTransition`? In my case it contains `Transition`, not `CSSTransition`

why is this nonsense necessary?

**Comment by tculig** [comment]
import React from "react"
import { CSSTransition } from "react-transition-group"

const MyComponent = () => {
  const nodeRef = React.createRef<HTMLDivElement>()
  return (
    <CSSTransition nodeRef={nodeRef} in timeout={200} classNames="fade">
      <div ref={nodeRef}>Fade</div>
    </CSSTransition>
  )
}

Using createRef instead of useRef seems to make it finally work as expected.

**Comment by tculig** [comment]
```
import React from "react"
import { CSSTransition } from "react-transition-group"

const MyComponent = () => {
  const nodeRef = React.createRef<HTMLDivElement>()
  return (
    <CSSTransition nodeRef={nodeRef} in timeout={200} classNames="fade">
      <div ref={nodeRef}>Fade</div>
    </CSSTransition>
  )
}
```

Using createRef instead of useRef seems to make it finally work as expected.

**Comment by emkayy** [comment]
> ### [<img alt="@jordanarldt" width="20" height="20" src="https://avatars.githubusercontent.com/u/19815878?s=60&amp;u=96dd73de249f3b24f541f4699b391cc8423945ee&amp;v=4">](/jordanarldt) ** [jordanarldt](/jordanarldt) **

I think this could be problematic as it creates new refs during each render. And I was also reading that you can't use useRef() and or createRef() in loops. Not sure if that's true.

I solved it by creating a component that handles the creation of the refs. It works well but you need that extra element 👎

**Comment by huangjihua** [comment]
Encounter the same problem.
Can be solved with set CSSTransitions component   property nodeRef

**Comment by FroDK** [comment]
> > ### [<img alt="@jordanarldt" width="20" height="20" src="https://avatars.githubusercontent.com/u/19815878?s=60&amp;u=96dd73de249f3b24f541f4699b391cc8423945ee&amp;v=4">](/jordanarldt) ** [jordanarldt](/jordanarldt) **
> 
> I think this could be problematic as it creates new refs during each render. And I was also reading that you can't use useRef() and or createRef() in loops. Not sure if that's true.
> 
> I solved it by creating a component that handles the creation of the refs. It works well but you need that extra element 👎

I also tried using nodeRef in a loop, but I have a problem with deleting elements. The very last element is always deleted and then everything is redrawn. It's just that I pass the ref by reference to the child component
I've already tried everything, I don't know how to solve this problem:(

**Comment by aquaductape** [comment]
To add on @Samk13 [workaround](https://github.com/reactjs/react-transition-group/issues/668#issuecomment-791003824), instead of polluting your components with useless refs, here's a wrapper. 

I'm not sure how to use refs with children props, I came across this [SO answer](https://stackoverflow.com/questions/63654496/is-it-possible-to-add-ref-to-the-props-children-elements) which is used in the wrapper.

```ts
import { CSSTransition as _CSSTransition } from 'react-transition-group';

import { CSSTransitionProps } from 'react-transition-group/CSSTransition';

const CSSTransition = (props: CSSTransitionProps) => {
  const nodeRef = useRef(null);

  return (
    <_CSSTransition {...props} nodeRef={nodeRef}>
      <>
        {React.Children.map(props.children, (child) => {
          // @ts-ignore
          return React.cloneElement(child, { ref: nodeRef });
        })}
      </>
    </_CSSTransition>
  );
};

export default CSSTransition;

```

**Comment by vonbalaji** [comment]
@aquaductape I'm new to  react world. I'm facing similar problem by using the reactstap . Is there a way to inject this when using reactstrap ?

**Comment by krinoid** [comment]
If you're dealing with multiple elements/nodes, the solution is a bit different. @aquaductape shared useful pointers but I had problems with this approach, as my animations weren't working. I think it's related to `nodeRef.current` being directly accessed (cf. https://github.com/reactjs/react-transition-group/blob/740b1dd0b4502dcb107a88261927b5069ac0b3af/src/Transition.js), and if you use `useRef([])` or `useRef({})` you'll then need to pass e.g. `nodeRef={myRefs.current[id]}`, so doesn't seem "compatible".

In the end, @ljc-dev solution in https://github.com/reactjs/react-transition-group/issues/675 (check the [codesanbox example](https://codesandbox.io/s/thirsty-rgb-dbgxl) they shared) helped. Basically, you need to `createRef` dynamically for each node, for example:
```jsx
const Example = ({ items }) => {
  return (
    <TransitionGroup>
      {items.map(() => {
        const itemRef = createRef(null); // <- THIS
        return (
          <CSSTransition nodeRef={itemRef}>
            <YourComponent ref={itemRef} />
          </CSSTransition>
        );
      })}
    </TransitionGroup>
  );
};

```
Note: if `YourComponent` is a function component, you might need to use `forwardRef` in its declaration.

**Comment by krinoid** [comment]
> @krinoid when I use this my animation does not work correctly in functional components.

Are you using [`forwardRef`](https://reactjs.org/docs/forwarding-refs.html) in your functional component? For example:
```jsx
const YourComponent = React.forwardRef((props, ref) => (<div ref={ref}>stuff</div>));
```

Otherwise passing `ref` won't work as expected (unless you have class component).

**Comment by aryankarim** [comment]
I can't find any convincing solution. If anyone knows an alternative library/solution, tag me plz. If there is no alternative and you're interested in developing a much simpler library for fixing animation during mounting and unmounting, then hmu.

**Comment by AlexSND** [comment]
I solve this for SwitchTransition
I use useMemo hook for create new ref when key (activeIndex in example) changed

```
const renderCards = useMemo(() => {
    const nodeRef = createRef();
    return <SwitchTransition>
      <CSSTransition
        nodeRef={ nodeRef }
        key={ activeIndex }
        addEndListener={(done) => nodeRef.current.addEventListener('transitionend', done, false)}
        classNames='fade'
      >
          <CaseCard
            ref={ nodeRef }
            key={ cases[activeIndex].id }
            title={ cases[activeIndex].title }
          />
      </CSSTransition>
    </SwitchTransition>;
  }, [activeIndex]);
```

**Comment by Juanma-NaN** [comment]
The initial animation doesn't show (`translateY(0`). Just the out one.

```javascript
const Modal: FC<ModalProps> = ({ show = false, title, message, action, onClose }) => {
  const portalDiv = document.getElementById('app')!;
  const nodeRef = useRef(null);

  return ReactDOM.createPortal(
    <CSSTransition in={show} unmountOnExit timeout={{ enter: 0, exit: 300 }} nodeRef={nodeRef}>
      <div ref={nodeRef} className={`modal ${show ? 'show' : ''}`} onClick={onClose}>
        <div className="modal-container" onClick={(e) => e.stopPropagation()}>
          <div className="modal-header">
            <Title title={title} />
            <AiOutlineClose className="close-button" onClick={onClose} />
          </div>
          <div className="modal-content">
            <div className="message">{message}</div>
            <div className="image"></div>
          </div>
          <div className="modal-footer">
            <Button text="Cancel" onClick={onClose} secondary={true} />
            <Button text="Confirm" onClick={action} />
          </div>
        </div>
      </div>
    </CSSTransition>,
    portalDiv,
  );
};
```

**Comment by Slapbox** [comment]
@khan94 did you ever resolve your error? I think we're seeing the same issue.

@krinoid thanks for your suggestion, but for us that results in this error. Any ideas?

` Invalid prop `nodeRef.current` of type `Switch` supplied to `CSSTransition`, expected instance of `Element`.`

And then we still get: `TypeError: Cannot read properties of undefined (reading 'baseVal')`

Our code looks like this:

```js
<TransitionGroup
      component={null} // Prevent rendering wrapper div
    >
      {children.map(() => {
        const itemRef = React.createRef(null);
        return (
        <CSSTransition
          nodeRef={itemRef}
          timeout={timeout}
          classNames={method}
          key={location.pathname}>
            <Switch ref={itemRef} location={location}>{children}</Switch> // NOTE: Tried `child` here instead of `children` but we still get Invalid prop `nodeRef.current`, plus none of our components render anymore
          </CSSTransition>
        );
      })}
    **</TransitionGroup>**

```

**Comment by silvenon** [comment]
@Slapbox I just updated the [example with React Router](https://reactcommunity.org/react-transition-group/with-react-router), the key part is using `useOutlet` instead of `<Outlet>` in order to maintain the exiting route, otherwise it updates to the current one.

To everyone else: we're updating the docs to use `nodeRef`, to make it an official recommendation. As for why your particular case isn't working, please send full CodeSandbox examples so that I can fix them. Regarding changing the `key` prop, the gotcha there is that you have to have a separate ref object for each key, don't reuse the same one.

Shoot more questions at me, I'm ready. 🔥
