### ISSUE TITLE
Problem with minified link from Readme

### ISSUE THREAD

**Issue by dantesolis** [reactjs/react-transition-group#67]
**Do you want to request a *feature* or report a *bug*?**
      Report a bug.

**What is the current behavior?**
       When I clicked on the link to get the minified version of the package, I'm redirected to a non 
working link: `Not found: file "/dist/react-transition-group.min.js" in package react-transition-group@1.1.3`

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**

**What is the expected behavior?**
   To arrive add a working link of the minified version. This link seems to work... [link](https://unpkg.com/react-transition-group@1.1.3/dist/react-transition-group.js)

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**
  Chrome browser. 

**Note:** I could make the change on a pull request if only the readme needs to be updated.

**Comment by virgofx** [comment]
We just pushed it in the previous commit which hasn't been officially released. Thus, the documentation is forward looking. Hopefully the build can get cut soon and then the documentation will work. For now, simply use the non-minified extension in the meantime.

**Comment by virgofx** [comment]
@dantesolis Everything should be working. Can you confirm? If so we can close this.
