### ISSUE TITLE
Allow props to be sent to state.children

### ISSUE THREAD

**Issue by jayasurya-sridharan** [reactjs/react-transition-group#7]
Hi All,

I came across an issue while writing my application, and I believe it can be best solved with a simple addition to the TransitionGroup. Essentially, I need to pass props into the transitioning components within TransitionGroup, however this.props.children does not contain the exiting element. 

You can read the full details of my issue on StackOverflow [here](http://stackoverflow.com/questions/41404232/react-transitiongroup-and-react-cloneelement-do-not-send-updated-props) (no need to post the same thing twice)

My current code to insert props (not sending updated props to exiting components): 

```js

class TransitionContainer extends React.Component{
  render(){
    return(
      <div>
      <TransitionGroup>
      {
        React.Children.map(this.props.children,
         (child) => React.cloneElement(child,
           { key: child.props.route.path + "//" + child.type.displayName,
             dispatch: this.props.dispatch,
             transitionState: this.props.transitionState
           }
         )
        )
      }

      </TransitionGroup>
      </div>
    )
  }
}
      </TransitionGroup>
```

My proposed solution: 

```js
class TransitionContainer extends React.Component{
  render(){
    let {dispatch,transitionState} = this.props
    return(
      <div>
      <TransitionGroup 
          extraProps={{dispatch: dispatch,transitionState:transitionState}}>
        
        {
          React.Children.map(this.props.children,
           (child) => React.cloneElement(child,
             { key: child.props.route.path + "//" + child.type.displayName}
           )
          )
        }
      
      </TransitionGroup>
      </div>
    )
  }
}
```
The `extraProps` prop passed to `TransitionGroup` will be passed to all of `state.children` so that they can receive updates during the transition lifecycle.

Let me know what you think, and thanks for all the great work on this library!! And I can probably write it in and pull request myself if I get a few approving votes on this idea.

-Jay

**Comment by jayasurya-sridharan** [comment]
Figured out i can just use `childFactory`. Hope this helps someone else!

**Comment by Slapbox** [comment]
Is there anything like this for `<SwitchTransition />`? I could always create a context provider, but it seems needlessly complicated.
