### ISSUE TITLE
React deprecated method: deprecated findDOMNode usage

### ISSUE THREAD

**Issue by Kylian030903** [reactjs/react-transition-group#708]
Hi,
I opened this issue to report you a bug on your react-transition-group module. Methods to interact with the DOM and the virtual DOM in React has changed and since this update React has done, when we use transitions by the way of react-transition-group. The error occurred when the transition entered into the DOM.

We have got this following error in the console of the web browser: `Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node`.
![Screenshot_2](https://user-images.githubusercontent.com/47856136/112153970-21c07f00-8be4-11eb-8115-346c94ebe663.png)

I hope you will fix this issue quickly!

**Comment by koba04** [comment]
@Kylian030903 `react-transition-group` has added `nodeRef` as an alternative for `findDONNode`, so you can use `nodeRef` to avoid the warning.
https://github.com/reactjs/react-transition-group/blob/master/CHANGELOG.md#440-2020-05-05

**Comment by nicewaytodoit** [comment]
@koba04  if `nodeRef` is added animation will stop working #709.

**Comment by nicewaytodoit** [comment]
@koba04 I stand corrected both element (Transition and inner animated element <div> in the example) must have nodeRef and then it will be ok:
```jsx
    <CSSTransition 
nodeRef={nodeRef}  <----------------------
in timeout={200} classNames="fade">
      <div 
ref={nodeRef} <----------------------
>Fade</div>
```
