### ISSUE TITLE
react and react-dom listed as both peer and dev dependencies

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [reactjs/react-transition-group#712]
> What is the current behavior?

In `react-transition-group`'s package.json file, `react` and `react-dom` are listed under both `peerDependencies` and `devDependencies`:

```json
"peerDependencies": {
    "react": ">=16.6.0",
    "react-dom": ">=16.6.0"
  },
  "devDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    ...
  }
```

> What is the expected behavior?

Is there a reason for this? It seems like these libraries should only be listed as `peerDependencies`.

**Comment by koba04** [comment]
@Bosch-Eli-Black `react-transition-group` uses `react` and `react-dom` for testing and storybooks, so they should be listed in the `devDependencies`

**Comment by Bosch-Eli-Black** [comment]
@koba04 Got it! Thanks 🙂
