### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Graham1384** [reactjs/react-transition-group#727]
I'm getting this error:

> findDOMNode is deprecated in StrictMode

animation is working well. here is my code:

> <CSSTransition in={ showDeleteModal } classNames="delete-modal" timeout={ 300 } unmountOnExit>
>   <DeleteModal product={ deleteProduct } deleteFunc={ removeProduct } closeFunc={ closeDeleteModal }/>
> </CSSTransition>

I also tried this solution mentioned on #668 suggested by @pixel-fixer 

    <CSSTransition nodeRef={nodeRef} in={ showDeleteModal } classNames="delete-modal" timeout={ 300 } unmountOnExit>
        <div ref={nodeRef}>
            <DeleteModal product={ deleteProduct } deleteFunc={ removeProduct } closeFunc={ closeDeleteModal } />
        </div>
    </CSSTransition>

It removes the error but also disables animation.

Is there any solution available?
![image](https://user-images.githubusercontent.com/62774242/119131396-ad248800-ba4e-11eb-8e79-8797dcbe6269.png)

**Comment by michaeljblum** [comment]
Hey @Graham1384 - did you resolve this?

**Comment by aryaadinulfadlan** [comment]
i also get the same problem. how do you enable animation again? help me please.

**Comment by rajmcablr** [comment]
Seems, the issues persists with SPX 1.14 with Node 14.18.1

**Comment by aryaadinulfadlan** [comment]
> 

so what should i do to run animation again? without warning about findDOMNode is deprecated.

**Comment by pmoieni** [comment]
> > 
> 
> so what should i do to run animation again? without warning about findDOMNode is deprecated.

You can wrap your component inside a div and add the ref to the div instead of the component itself.
