### ISSUE TITLE
Type error when using TypeScript with Transition component

### ISSUE THREAD

**Issue by Mini-ghost** [reactjs/react-transition-group#743]
> What is the current behavior?

When I use TypeScript with Transition component like below:

```tsx
<Transition
  appear={appear}
  in={active}
  nodeRef={nodeRef}
  onEnter={handleEnter}
  onEntered={handleEntered}
  onEntering={handleEntering}
  onExit={handleExit}
  onExited={handleExited}
  onExiting={handleExiting}
  timeout={duration}
  {...rest}
>
  {(state: , childProps) => React.cloneElement(children, {
    ref: handleRef,
    ...childProps,
  })}
 </Transition>
```

This will get an error message: `Parameter 'childProps' implicitly has an 'any' type.  TS7006`

> What is the expected behavior?

In the source code
https://github.com/reactjs/react-transition-group/blob/957a0f034af5f1050106aff32f5984b6290e0710/src/Transition.js#L370-L378

When the children type is a function, `status` and `childProps` will be passed, but there is no mention of `childProps` in the documentation and @types/react-transition-group. Is this deprecated or omitted?

`childProps` is very important when I want to make some components, such as Grow, Fade... etc.

**Comment by rajmcablr** [comment]
we are also experiencing the same issue.

Any pointers would help towards closure !!!
