### ISSUE TITLE
Official Link is Not working.

### ISSUE THREAD

**Issue by anshul2807** [reactjs/react-transition-group#755]
>#  What is the current behavior?
**Link** -- `https://reactcommunity.org/react-transition-group/` 
### It is showing me  the error --
`172.30.83.9 took too long to respond.`

> # What is the expected behavior?
### It should redirect me to the official Page.

># ScreenShot
![Screenshot (48)](https://user-images.githubusercontent.com/56274258/130724075-8973867d-14a6-429a-864e-544d4275dfd7.png)

># EDIT
## ScreenShot (Mobile)
![photo_2021-08-25_09-48-27](https://user-images.githubusercontent.com/56274258/130725888-42cd6cac-5a0b-4c5f-a452-09346c82d805.jpg)

**Comment by Keshavdulal** [comment]
Yep. Can confirm the same.
The entire https://reactcommunity.org domain is down and even on mobile.
I couldn't even locate any .md files on documentation for RTG which would've saved the day for people looking for it.
@silvenon

**Comment by silvenon** [comment]
The domain appears to be back up. 🎉  Not sure what was wrong as I wasn't managing it.
