### ISSUE TITLE
Collapse timeout doesn't go higher then 300ms

### ISSUE THREAD

**Issue by mnai01** [reactjs/react-transition-group#773]
> What is the current behavior?

Collapse timeout only goes up to 300 max

> What is the expected behavior?

timeout with any number value should convert to ms, therefore if i put timeout={5000} it should be a 5sec transition

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

https://codesandbox.io/s/react-bootstrap-collapse-forked-kscsn?file=/src/App.js

**Comment by koba04** [comment]
Collapse is a `react-bootstrap`'s component, so please file an issue in `react-bootstrap`.
