### ISSUE TITLE
Support React v18

### ISSUE THREAD

**Issue by koba04** [reactjs/react-transition-group#775]
React v18 is now in beta, so it's time to prepare for the release.
This is the meta issue for what we need.

- [x] 🏃‍♂️  Test with React 18 #771

**Comment by koba04** [comment]
React v18 RC has been released.

**Comment by koba04** [comment]
I believe react-transition-group works well with React v18, so I'll close this 🎉

**Comment by tranvansang** [comment]
https://github.com/reactjs/react-transition-group/issues/775#issuecomment-1083252931

> I believe react-transition-group works well with React v18, so I'll close this tada

Unfortunately, it is not :'(. I have made another issue on react 18.

https://github.com/reactjs/react-transition-group/issues/816
