### ISSUE TITLE
☄️ Hey guys, I created a lib called `transition-hook` which inspire by this one, but only 0.4kb.

### ISSUE THREAD

**Issue by iamyoki** [reactjs/react-transition-group#776]
## No offends, but exciting to share a great work. (Sorry if it offends and please contact me to delete this issue.)
I open sourced a hook library that is only 0.4kb in size but has almost the same ability as react-transition-group

> react-transition-group is a great library, I've been using it for 4 years. However, there have been some unresolved bugs since react17, and the size of the package has always been large. Personally, I prefer the hook-based development pattern, so I created a hook version like of react-transition-group.

<a href="https://tqgdj.csb.app/">
    <img src="https://github.com/iamyoki/transition-hook/raw/main/example.gif" width="400" alt="example">
  </a>

demo: https://codesandbox.io/s/transition-hook-example-tqgdj
repo: https://github.com/iamyoki/transition-hook

**Comment by koba04** [comment]
@iamyoki Thank you for sharing your work. I'd like to implement a hook version of `react-transition-group` in the future, which can be more simple and minimum.
This is not an issue, so I'll close this.

**Comment by iamyoki** [comment]
@koba04  Thank you for your reply, today I added a new hook - useSwitchTransition, it's updated in the docs, please take a look it might interest you 😋.
https://github.com/iamyoki/transition-hook#%EF%B8%8F-transition-hook
