### ISSUE TITLE
Warning: findDOMNode is deprecated in StrictMode.

### ISSUE THREAD

**Issue by neohan666** [reactjs/react-transition-group#779]
Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node

**Comment by rilexus** [comment]
You can do:
```js
const Some = () => {
  const ref = useRef();
  return (
    <Transition nodeRef={ref}>
      {() => <div ref={ref}/>}
    </Transition>
  )
}
```
as the error message suggest "[...] add a ref directly to the element you want to reference."

**Comment by neohan666** [comment]
> You can do:
> 
> ```js
> const Some = () => {
>   const ref = useRef();
>   return (
>     <Transition nodeRef={ref}>
>       {() => <div ref={ref}/>}
>     </Transition>
>   )
> }
> ```
> 
> as the error message suggest "[...] add a ref directly to the element you want to reference."

It can work. Thanks.
