### ISSUE TITLE
Documentation: misleading FirstChild implementation

### ISSUE THREAD

**Issue by OliverJAsh** [reactjs/react-transition-group#81]
In the documentation, the [`FirstChild` implementation](https://facebook.github.io/react/docs/animation.html#rendering-a-single-child) looks like this:

``` js
function FirstChild(props) {
  const childrenArray = React.Children.toArray(props.children);
  return childrenArray[0] || null;
}
```

Looking at the types and documentation for `React.Children.toArray`, it looks like this can return an array of `string`, `number`, or a `ReactElement`:
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/755b23622a5d782e23d4fc17bbea9104718945d0/types/react/index.d.ts#L2701
- https://facebook.github.io/react/docs/react-api.html#react.children.toarray

I think this would cause a bug in the given `FirstChild` implementation, because stateless components cannot return `string` or `number`:

``` js
{
  const Foo = () => 'foo'
  const foo = React.createElement(Foo)
  const div = document.createElement('div')
  ReactDOM.render(foo, div) // error
}
```

Complete example:

``` js
{
  function FirstChild(props) {
    const childrenArray = React.Children.toArray(props.children);
    return childrenArray[0] || null;
  }
  const Foo = () => React.createElement('div', {}, 'foo')
  const foo = React.createElement(FirstChild, {}, Foo)
  const div = document.createElement('div')
  ReactDOM.render(foo, div)
  div.innerHTML // expected "foo", actual ""
}
```

What would be the correct implementation?

**Comment by jquense** [comment]
The example implementation is correct, children in general can be many things but in this context they have to be elements, because transition group only supports animating elements

**Comment by OliverJAsh** [comment]
If the documentation is correct like you say, can you tell me why I don't see the text child when using FirstChild in the example above?

**Comment by OliverJAsh** [comment]
Ah, my example above was incorrect because I did not wrap `Foo` in `React.createElement`. This works:

``` js
{
  function FirstChild(props) {
    const childrenArray = React.Children.toArray(props.children);
    return childrenArray[0] || null;
  }
  const Foo = () => React.createElement('span', {}, 'foo')
  const foo = React.createElement(FirstChild, {}, React.createElement(Foo, {}))
  const div = document.createElement('div')
  ReactDOM.render(foo, div)
  div.innerHTML // "<span data-reactroot="">foo</span>"
}
```

**Comment by OliverJAsh** [comment]
To conclude, the correct `FirstChild` would only receive non-string and non-number children.
