### ISSUE TITLE
v2  docs

### ISSUE THREAD

**Issue by Noitidart** [reactjs/react-transition-group#82]
I can't find the docs for beta (v2). It doesnt seem it has a `CSSTransitionGroup` anymore, it is now `CSSTransition`, `Transition`, and `TransitionGroup`. I tried each of them in place of CSSTranisitionGroup but it is giving me errors.

**Comment by jquense** [comment]
There are no docs at the moment, except for in comments on the Components, you can poke around the source files for examples and docs

**Comment by Noitidart** [comment]
Thanks jquence very much for the reply. I managed to make do with the new api and am loving it! Love the chane from "leave" -> 'exit' haha

**Comment by jquense** [comment]
gald you like it :)
