### ISSUE TITLE
How to use TransitionGroup's childFactory prop and avoid `findDOMNode is deprecated` error

### ISSUE THREAD

**Issue by qramilq** [reactjs/react-transition-group#820]
I'm trying to use different animations with `childFactory` from [this](https://github.com/reactjs/react-transition-group/issues/182#issuecomment-349235710) message.

> What is the current behavior?

When I try to animate I get an error (warning) in console, that says "Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode...."

> What is the expected behavior?

No errors when animate

> Could you provide a [CodeSandbox](https://codesandbox.io/) demo reproducing the bug?

[CodeSandbox](https://codesandbox.io/s/wizardly-shannon-3reb8b)

**Comment by zzjin** [comment]
same issue here.

**Comment by aderchox** [comment]
> Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
    at div
    at Transition
    at CSSTransition
    at App

**Comment by Stunext** [comment]
Same issue here! Is there any plan to solve this problem in a future version?

**Comment by pingjintao** [comment]
+1

**Comment by ccccooooddddyyyy** [comment]
me too!

**Comment by Tonysmark** [comment]
+1

**Comment by Tonysmark** [comment]
> +1

currently using version 4.4.5

**Comment by groop-moray** [comment]
+1, 4.4.5

**Comment by mikyYun** [comment]
Hi, I just solved by revmoe "StrictMode" from  <React.StrictMode><App /></React.StrickMode> to <App />

I tried React.createRef and useRef to give ref to Transition or children components, but didn't solve problem.
My project does not really necessary the strickMode, so I removed it and worked.

**Comment by codyslex1a** [comment]
> Hi, I just solved by revmoe "StrictMode" from <React.StrictMode></React.StrickMode> to
> 
> I tried React.createRef and useRef to give ref to Transition or children components, but didn't solve problem. My project does not really necessary the strickMode, so I removed it and worked.

The error is only shown in StrictMode, so your "solution" is like clearing console.

**Comment by mikyYun** [comment]
>

Right... was stupid, 
When I give nodeRef=React.useRef() to CSSTransition as a prop, the error is gone but the children do not animate.
If I figure it out, will come back

**Comment by yepyeel** [comment]
Maybe i solved this problem. I use these codes and work well.
```typescript react
// ...some codes
const nodeRef = useRef<HTMLDivElement>(null);

// ...some codes
return (
    <TransitionGroup>
      {list.map(({ content, key }) => (
        <CSSTransition
          key={key}
          nodeRef={nodeRef}
          timeout={delay}
          classNames={{
            enter: styles['messageBox-enter'],
            enterActive: styles['messageBox-enter-active'],
            exit: styles['messageBox-exit'],
            exitActive: styles['messageBox-exit-active']
          }}
        >
          <div
            ref={nodeRef}
            className={classNames(
              'fixed top-16 left-1/2 z-[1001]',
              'rounded-sm bg-primary py-3 min-w-[168px]',
              'flex items-center justify-center'
            )}
          >
            <CheckIcon className="mr-1.5" />
            <span className="text-white text-sm leading-none">{content}</span>
          </div>
        </CSSTransition>
      ))}
    </TransitionGroup>
)
```

**Comment by mikyYun** [comment]
does your code not break the animation? my attemped codes are here, when I add noderef to CSSTransition, all animations were broken
`<TransitionGroup
        className="transition_group"
        childFactory={childFactory(direction)}
      >
        <CSSTransition
          classNames={direction}
          timeout={{ enter: 500, exit: 500 }}
          key={currentProject}
          // nodeRef={ref}
        >
          <div className="projects_contents" ref={ref}>
            {projectsContainer(currentProject)}
          </div>
        </CSSTransition>
      </TransitionGroup>
`

**Comment by b5414** [comment]
same

**Comment by brokuka** [comment]
up

**Comment by denchiklut** [comment]
Hi everyone I had the same problem but I think I found solution.
The problem was when you specify `nodeRef` prop handlers will work a bit differently. You wont receive node in handlers callback as an argument as it was previously. instead you would have to manually specify node you are animating.
  
For example:
See this [code](https://github.com/denchiklut/transitions-kit/blob/main/src/fade/fade.tsx#L46). Basically what I did I store the ref to the node. And then use this ref in all handlers. 

I Hope it will help you.

**Comment by silvenon** [comment]
To close this, this is how I would rewrite your component:

```jsx
const STEPS = [
  { name: "first step", nodeRef: createRef(null) },
  { name: "second step", nodeRef: createRef(null) },
  { name: "third step", nodeRef: createRef(null) },
  { name: "fourth step", nodeRef: createRef(null) }
];

export default function App() {
  const [currentStep, setCurrentStep] = useState(0);
  const isNext = useRef(false);
  const { name: step, nodeRef } = STEPS[currentStep] ?? {};

  return (
    <div className="App">
      {currentStep > 0 ? (
        <button onClick={() => setCurrentStep(currentStep - 1)}>Prev</button>
      ) : null}
      {currentStep < STEPS.length - 1 ? (
        <button onClick={() => setCurrentStep(currentStep + 1)}>Next</button>
      ) : null}

      <TransitionGroup
        childFactory={(child) => {
          return cloneElement(child, {
            classNames: isNext.current ? "right-to-left" : "left-to-right",
            timeout: 500
          });
        }}
      >
        <CSSTransition
          timeout={500}
          classNames="right-to-left"
          key={step}
          nodeRef={nodeRef}
        >
          <h1 ref={nodeRef} className="step">
            {step}
          </h1>
        </CSSTransition>
      </TransitionGroup>
    </div>
  );
}
```

- create a ref object for each step, and pass it as `nodeRef` to `CSSTransition` and as `ref` to `h1`
- hide previous or next button if there is no previous or next step to go to

No warnings for me. Let me know if you have any questions.

**Comment by vukadinFE** [comment]
+1

**Comment by silvenon** [comment]
I'm locking this to avoid more "+1"s. If https://github.com/reactjs/react-transition-group/issues/820#issuecomment-1248508631 doesn't help you resolve your particular use case, please open a new issue.
