### ISSUE TITLE
v2 API Troubles with React Router

### ISSUE THREAD

**Issue by Noitidart** [reactjs/react-transition-group#83]
Am I understanding this correct?

Transition API v2 expects immediate children of `<TransitionGroup>` to be `<CSSTransition>`.

This makes it not possible to use with react router:

React Router `<Switch>` expects immediate children to be of type `<Route>`.

```
            <TransitionGroup id="page_fader" key="page_fader">
                    <Switch key={lockey} location={location}>
                       <CSSTransition ...><Route exact key="landing" path="/landing" render={routerprops => <Page />} /></CSSTransition>
                       <CSSTransition ...><Route exact key="404" render={routerprops => <Page />} /></CSSTransition>
                    </Switch>
            </TransitionGroup>
```

The way we did this in v1 was:

```
            <CSSTransitionGroup id="page_fader" key="page_fader" ...>
                <Switch key={lockey} location={location}>
                    <Route exact key="landing" path="/landing" render={routerprops => <Page />} />
                    <Route exact key="404" render={routerprops => <Page />} />
                </Switch>
            </CSSTransitionGroup>
```

**Comment by jquense** [comment]
> Transition API v2 expects immediate children of <TransitionGroup> to be <CSSTransition>.

This isn't accurate actually, you can use any child as long as it eventually renders something that implements the `Transition` api. I'm not really familiar with the RR v4 api but I'd imagine you need need to wrap the individual `Switch` in the Transition you want?

**Comment by Noitidart** [comment]
Ohhh super cool @jquense thanks very much for that info! That would make this very much possible then. I will update here and the related issue in the RR repo with solution :)

**Comment by virgofx** [comment]
@jquense Notice your updating V2 with more commits. Any change you can push details of this somewhere (maybe into the changelog or current readme)

**Comment by jquense** [comment]
Yes I'll be putting together a migration guide and proper docs. Just haven't had a chance, which is why it's still in beta

**Comment by andrewcroce** [comment]
@Noitidart could you post an example of how you solved this? I'm also having troubles getting react-router v4 to work with react-transition-group v2.

**Comment by Noitidart** [comment]
@andrewcroce - @Horizon-Blue posted nice solutions in the linked topic on the react-router repo - https://github.com/ReactTraining/react-router/issues/5279

**Comment by andrewcroce** [comment]
Thanks @Noitidart

**Comment by cheapsteak** [comment]
Only seems to work for CSS transitions though?
