### ISSUE TITLE
V4.4.3 does not work

### ISSUE THREAD

**Issue by hassanzadeh** [reactjs/react-transition-group#844]
Hey,
I don't know what you have done but V4.4 no longer works, npm install just creates an empty directory.

**Comment by aldwyn** [comment]
Specifically, the failure is in v4.4.3. It has files on v4.4.2 and it still works.

**Comment by melloware** [comment]
+1 seeing the same issue

**Comment by MaxKoldun** [comment]
+1 have problem with the package

**Comment by faizy99** [comment]
+1 seeing the same issue as react-bootstrap relies on it as well.

**Comment by melloware** [comment]
I think this the definition of a "supply chain attack" :) https://en.wikipedia.org/wiki/Supply_chain_attack

**Comment by femesq** [comment]
@aldwyn solution works for me.... 

If the package is a dependency of other package in your project, you may need to use yarn `resolution`...

**Comment by koba04** [comment]
I'll fix it as soon as possible.

**Comment by marborgo** [comment]
Please fix it!!!!

**Comment by korkoraan** [comment]
same issue here

**Comment by marborgo** [comment]
great work team!

**Comment by koba04** [comment]
I've published v4.4.4 which fixes the issue🙏

**Comment by koba04** [comment]
I've also marked 4.4.3 as a deprecated version.
