### ISSUE TITLE
Transition component detected as invalid type

### ISSUE THREAD

**Issue by bkazi** [reactjs/react-transition-group#86]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I am trying to use the v2 API for TransitionGroup and Transition and get the following error

```
warning.js:36 Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in.
```

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/1Lb2qk3v/).**
I have the following basic component
```jsx
class App extends React.Component {
  render() {
    <Transition in={true}>
      <div>Hello World</div>
    </Transition>
  }
}

ReactDOM.render(
  <TransitionGroup>
    <App />
  <TransitionGroup>,
  document.getElementById('root')
);
```

**What is the expected behavior?**
I'm not sure of the usage of TransitionGroup in v2. Are there any examples or docs that I've missed? I might just be missing something very basic

**Which versions, and which browser / OS are affected by this issue? Did this work in previous versions?**

**Comment by bkazi** [comment]
Okay my bad, I'd accidentally installed the 1.x version which does not export Transition
I am still slightly confused about the times the different functions are called at and if any of them are 'animation blocking' as in the 1.x API

**Comment by jquense** [comment]
@bkazi none of the callbacks in the new API "block" in the sense that they pass in a callback. They will transition for as long as the `timeout` is. There is a prop to do that https://github.com/reactjs/react-transition-group/blob/master/src/Transition.js#L324 if you want more control, but it still uses the timeouts as a fallback
