### ISSUE TITLE
Transition animation between route changes in NextJS not working

### ISSUE THREAD

**Issue by anatolii-pyroh** [reactjs/react-transition-group#889]
> What is the current behavior?

Im creating page transition in nextJs and everything worked, but I got an console error about findDOMnode, after some research I find a solution to add nodeRef to CSSTransition component but after this I dont see any animations

> What is the expected behavior?

See animation between route changes

As you can see Im using SwitchTransition alongside with CSSTransition, the key is pathname. Before I added nodeRef everything worked but with error in console, after I added nodeRef the animation is not showing anymore

```````
export default function App({ Component, router, ...rest }: AppProps) {
  const nodeRef = useRef(null);

  return (
        <SwitchTransition mode='out-in'>
          <CSSTransition
            key={router.pathname}
            classNames='pageTransition'
            timeout={300}
            nodeRef={nodeRef}
          >
            <Layout>
              <Component {...props.pageProps} />
            </Layout>
          </CSSTransition>
        </SwitchTransition>
  );
}
```````

**Comment by adnanaslam475** [comment]
any update on this issue

**Comment by agent150891** [comment]
> any update on this issue

Yeah, I managed to fix this problem by also providing nodeRef to my Layout component

`        <SwitchTransition mode='out-in'>
          <CSSTransition
            key={router.pathname}
            classNames='pageTransition'
            timeout={300}
            nodeRef={nodeRef}
          >
            <Layout ref={nodeRef}>
              <Component {...props.pageProps} />
            </Layout>
          </CSSTransition>
        </SwitchTransition>`

**Comment by anatolii-pyroh** [comment]
> any update on this issue

Yeah, I managed to fix this problem by also providing nodeRef to my Layout component

```        <SwitchTransition mode='out-in'>
          <CSSTransition
            key={router.pathname}
            classNames='pageTransition'
            timeout={300}
            nodeRef={nodeRef}
          >
            <Layout ref={nodeRef}>
              <Component {...props.pageProps} />
            </Layout>
          </CSSTransition>
        </SwitchTransition>```

**Comment by adnanaslam475** [comment]
still not working here.. 
@anatolii-pyroh just declared noderef and put into csstransition, right?

**Comment by anatolii-pyroh** [comment]
> @anatolii-pyroh just declared noderef and put into csstransition, right?

Yes, and in Layout component as well


```
export const LayoutComponent = React.forwardRef<
  HTMLDivElement,
  PropsWithChildren
>(({ children }, ref) => {
      <main ref={ref}>
        <Scrolling vertical className='container'>
          {children}
        </Scrolling>
      </main>

**Comment by adnanaslam475** [comment]
all done but still not working @anatolii-pyroh

**Comment by anatolii-pyroh** [comment]
> all done but still not working @anatolii-pyroh

No clue mate, I re-checked it, without Layout ref no animation and no error, without ref at all animation with error in console, you can check it here
https://github.com/anatolii-pyroh/next-js-tolistore/blob/main/src/pages/_app.tsx
