### ISSUE TITLE
Why does the animation effect disappear after triggering the redraw?

### ISSUE THREAD

**Issue by alekoshen712** [reactjs/react-transition-group#89]
I triggered a redraw in the componentDidUpdate of the A component and found that the squares in the B component did not work properly

sorry.my english is not good and maybe the statement is not clear my question, this is [demo](https://codepen.io/anon/pen/awKGgG?editors=0110).Thank you for your viewing.

**Comment by jquense** [comment]
Hi there, this is property of how CSS transitions work in a browser, and it can be kinda frustrating. see https://github.com/reactjs/react-transition-group/issues/10 for a bit more info. Unfortunately there isn't a great answer for how to fix it other than don't reflow at the wrong time. :/

**Comment by alekoshen712** [comment]
Thank you very much for your answer.
